// <auto-generated/>
#nullable enable

/*
 * Copyright 2026-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 *  Do not edit the class manually.
 */


namespace CoinbaseSdk.Prime.Model.Enums
{
  using System.Text.Json.Serialization;

  /// <summary>
  /// - UNKNOWN_BALANCE_TYPE: nil.
  /// - TRADING_BALANCES: Trading balances.
  /// - VAULT_BALANCES: Vault balances.
  /// - TOTAL_BALANCES: Total balances (The sum of vault and trading + prime custody).
  /// - PRIME_CUSTODY_BALANCES: Prime custody balances.
  /// - UNIFIED_TOTAL_BALANCES: Unified total balance across networks and wallet types (vault + trading + prime custody).
  /// </summary>
  [JsonConverter(typeof(JsonStringEnumConverter<PortfolioBalanceType>))]
  public enum PortfolioBalanceType
  {
    TRADING_BALANCES,
    VAULT_BALANCES,
    TOTAL_BALANCES,
    PRIME_CUSTODY_BALANCES,
    UNIFIED_TOTAL_BALANCES
  }
}
