// <auto-generated/>
#nullable enable

/*
 * Copyright 2026-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 *  Do not edit the class manually.
 */


namespace CoinbaseSdk.Prime.Model.Enums
{
  using System.Text.Json.Serialization;

  /// <summary>
  /// - HEALTH_STATUS_HEALTHY: Margin level is healthy.
  /// - HEALTH_STATUS_WARNING: Margin level is breaching the warning threshold (WT) which will result in the issuance of a Margin Call if this is still the case by the scheduled next Margin Call (as defined in the margin methodology). WT is differentiated from DT in that it means margin health is approaching the UMCT.
  /// - HEALTH_STATUS_CRITICAL: Margin level is breaching the UMCT and, as defined in the margin methodology, this will trigger an urgent margin call.
  /// - HEALTH_STATUS_SUSPENDED: Trading and withdrawals are suspended per XM margin methodology.
  /// - HEALTH_STATUS_RESTRICTED: Account is in a restricted state per XM margin methodology.
  /// - HEALTH_STATUS_PRE_LIQUIDATION: Margin level is breaching the liquidation threshold (LT) and, as defined in the margin methodology, this will trigger the SESSION_LOCKED control status and liquidation may commence.
  /// - HEALTH_STATUS_LIQUIDATING: Liquidation has commenced.
  /// - HEALTH_STATUS_IN_DEFICIT: Margin level is breaching the deficit threshold (DT) which will result in the issuance of a Margin Call if this is still the case by the scheduled next Margin Call time (as defined in the margin methodology).
  /// </summary>
  [JsonConverter(typeof(JsonStringEnumConverter<PrimeXMHealthStatus>))]
  public enum PrimeXMHealthStatus
  {
    /// <summary>
    /// Margin level is healthy.
    /// </summary>
    HEALTH_STATUS_HEALTHY,
    /// <summary>
    /// Margin level is breaching the warning threshold (WT) which will result in the issuance of a Margin Call if this is still the case by the scheduled next Margin Call (as defined in the margin methodology). WT is differentiated from DT in that it means margin health is approaching the UMCT.
    /// </summary>
    HEALTH_STATUS_WARNING,
    /// <summary>
    /// Margin level is breaching the UMCT and, as defined in the margin methodology, this will trigger an urgent margin call.
    /// </summary>
    HEALTH_STATUS_CRITICAL,
    /// <summary>
    /// Trading and withdrawals are suspended per XM margin methodology.
    /// </summary>
    HEALTH_STATUS_SUSPENDED,
    /// <summary>
    /// Account is in a restricted state per XM margin methodology.
    /// </summary>
    HEALTH_STATUS_RESTRICTED,
    /// <summary>
    /// Margin level is breaching the liquidation threshold (LT) and, as defined in the margin methodology, this will trigger the SESSION_LOCKED control status and liquidation may commence.
    /// </summary>
    HEALTH_STATUS_PRE_LIQUIDATION,
    /// <summary>
    /// Liquidation has commenced.
    /// </summary>
    HEALTH_STATUS_LIQUIDATING,
    /// <summary>
    /// Margin level is breaching the deficit threshold (DT) which will result in the issuance of a Margin Call if this is still the case by the scheduled next Margin Call time (as defined in the margin methodology).
    /// </summary>
    HEALTH_STATUS_IN_DEFICIT
  }
}
