// <auto-generated/>
#nullable enable

/*
 * Copyright 2026-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 *  Do not edit the class manually.
 */


namespace CoinbaseSdk.Prime.Model.Enums
{
  using System.Text.Json.Serialization;

  /// <summary>
  /// - MARGIN_REQUIREMENT_TYPE_DMR_PLUS_PMR: Integrated (netted) cross-margin requirement for spot assets and all derivatives contracts.
  /// - MARGIN_REQUIREMENT_TYPE_IPMR_PLUS_IFMR: Combined cross-margin requirement: Integrated Portfolio Margin (IPMR) plus Ineligible Futures Margin (IFMR).
  /// </summary>
  [JsonConverter(typeof(JsonStringEnumConverter<PrimeXMMarginRequirementType>))]
  public enum PrimeXMMarginRequirementType
  {
    MARGIN_REQUIREMENT_TYPE_UNSPECIFIED,
    /// <summary>
    /// Integrated (netted) cross-margin requirement for spot assets and all derivatives contracts.
    /// </summary>
    MARGIN_REQUIREMENT_TYPE_DMR_PLUS_PMR,
    /// <summary>
    /// Combined cross-margin requirement: Integrated Portfolio Margin (IPMR) plus Ineligible Futures Margin (IFMR).
    /// </summary>
    MARGIN_REQUIREMENT_TYPE_IPMR_PLUS_IFMR
  }
}
