// <auto-generated/>
#nullable enable

/*
 * Copyright 2026-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 *  Do not edit the class manually.
 */


namespace CoinbaseSdk.Prime.Model.Enums
{
  using System.Text.Json.Serialization;

  /// <summary>
  /// - RISK_MANAGEMENT_TYPE_UNSPECIFIED: Unspecified risk management type.
  /// - RISK_MANAGEMENT_TYPE_MANAGED_BY_FCM: Risk is managed by FCM (Futures Commission Merchant).
  /// - RISK_MANAGEMENT_TYPE_MANAGED_BY_VENUE: Risk is managed by the venue.
  /// </summary>
  [JsonConverter(typeof(JsonStringEnumConverter<RiskManagementType>))]
  public enum RiskManagementType
  {
    /// <summary>
    /// Unspecified risk management type.
    /// </summary>
    RISK_MANAGEMENT_TYPE_UNSPECIFIED,
    /// <summary>
    /// Risk is managed by FCM (Futures Commission Merchant).
    /// </summary>
    RISK_MANAGEMENT_TYPE_MANAGED_BY_FCM,
    /// <summary>
    /// Risk is managed by the venue.
    /// </summary>
    RISK_MANAGEMENT_TYPE_MANAGED_BY_VENUE
  }
}
