// <auto-generated/>
#nullable enable

/*
 * Copyright 2026-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 *  Do not edit the class manually.
 */


namespace CoinbaseSdk.Prime.Model.Enums
{
  using System.Text.Json.Serialization;

  /// <summary>
  /// - USER_ROLE_UNKNOWN: nil value.
  /// - AUDITOR: An auditor.
  /// - SIGNATORY: A signatory.
  /// - ADMIN: An admin.
  /// - INITIATOR: An initiator.
  /// - REVIEWER: A reviewer.
  /// - TRADER: A trader.
  /// - FULL_TRADER: A trader with full permissions.
  /// - TEAM_MANAGER: A team manager.
  /// - APPROVER: An approver.
  /// - TAX_MANAGER: A tax manager.
  /// - BUSINESS_MANAGER: A business manager.
  /// </summary>
  [JsonConverter(typeof(JsonStringEnumConverter<UserRole>))]
  public enum UserRole
  {
    /// <summary>
    /// An auditor.
    /// </summary>
    AUDITOR,
    /// <summary>
    /// A signatory.
    /// </summary>
    SIGNATORY,
    /// <summary>
    /// An admin.
    /// </summary>
    ADMIN,
    /// <summary>
    /// An initiator.
    /// </summary>
    INITIATOR,
    /// <summary>
    /// A reviewer.
    /// </summary>
    REVIEWER,
    /// <summary>
    /// A trader.
    /// </summary>
    TRADER,
    /// <summary>
    /// A trader with full permissions.
    /// </summary>
    FULL_TRADER,
    /// <summary>
    /// A team manager.
    /// </summary>
    TEAM_MANAGER,
    /// <summary>
    /// An approver.
    /// </summary>
    APPROVER,
    /// <summary>
    /// A tax manager.
    /// </summary>
    TAX_MANAGER,
    /// <summary>
    /// A business manager.
    /// </summary>
    BUSINESS_MANAGER
  }
}
