// <auto-generated/>
#nullable enable

/*
 * Copyright 2026-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 *  Do not edit the class manually.
 */


namespace CoinbaseSdk.Prime.Model.Enums
{
  using System.Text.Json.Serialization;

  /// <summary>
  /// ValidatorProvider enumerates the ETH validator service providers that PPA accepts on.
  /// PortfolioStakingUnstakeRequest.validator_provider. The enum names map 1:1 to the display.
  /// names returned by ISS GetUsedValidators (service_provider field) and shown in the Prime.
  /// UI. Keep in sync with staking/internal/asset/ethereum.mapServiceProviderToDisplayName.
  /// </summary>
  [JsonConverter(typeof(JsonStringEnumConverter<ValidatorProvider>))]
  public enum ValidatorProvider
  {
    VALIDATOR_PROVIDER_UNSPECIFIED,
    VALIDATOR_PROVIDER_COINBASE_CLOUD,
    VALIDATOR_PROVIDER_MAVAN,
    VALIDATOR_PROVIDER_FIGMENT,
    VALIDATOR_PROVIDER_CODEFI,
    VALIDATOR_PROVIDER_ATTESTANT,
    VALIDATOR_PROVIDER_GALAXY
  }
}
