// <auto-generated/>
#nullable enable

/*
 * Copyright 2025-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */


namespace CoinbaseSdk.Prime.Model
{
  using System.Text.Json.Serialization;
  using CoinbaseSdk.Prime.Model.Enums;

  public class Activity
  {
    /// <summary>
    /// A unique id for the account activity
    /// </summary>
    [JsonPropertyName("id")]
    public string? Id { get; set; }
    /// <summary>
    /// A reference for orders and transactions, n/a for other category types
    /// </summary>
    [JsonPropertyName("reference_id")]
    public string? ReferenceId { get; set; }
    [JsonPropertyName("category")]
    public ActivityCategory? Category { get; set; }
    [JsonPropertyName("type")]
    public PrimeActivityType? Type { get; set; }
    [JsonPropertyName("secondary_type")]
    public ActivitySecondaryType? SecondaryType { get; set; }
    [JsonPropertyName("status")]
    public ActivityStatus? Status { get; set; }
    /// <summary>
    /// Id of user who created the activity
    /// </summary>
    [JsonPropertyName("created_by")]
    public string? CreatedBy { get; set; }
    /// <summary>
    /// Title of the activity
    /// </summary>
    [JsonPropertyName("title")]
    public string? Title { get; set; }
    /// <summary>
    /// Description detail of the activity
    /// </summary>
    [JsonPropertyName("description")]
    public string? Description { get; set; }
    /// <summary>
    /// Actions related to the Activity
    /// </summary>
    [JsonPropertyName("user_actions")]
    public List<UserAction>? UserActions { get; set; }
    [JsonPropertyName("transactions_metadata")]
    public ActivityMetadataTransactions? TransactionsMetadata { get; set; }
    [JsonPropertyName("account_metadata")]
    public ActivityMetadataAccount? AccountMetadata { get; set; }
    [JsonPropertyName("orders_metadata")]
    public Object? OrdersMetadata { get; set; }
    /// <summary>
    /// List of currencies included in an activity
    /// </summary>
    [JsonPropertyName("symbols")]
    public List<string>? Symbols { get; set; }
    /// <summary>
    /// Time activity was created at
    /// </summary>
    [JsonPropertyName("created_at")]
    public string? CreatedAt { get; set; }
    /// <summary>
    /// Time for latest status update of account activity
    /// </summary>
    [JsonPropertyName("updated_at")]
    public string? UpdatedAt { get; set; }
    [JsonPropertyName("hierarchy_type")]
    public HierarchyType? HierarchyType { get; set; }
    public Activity() { }

    public Activity(Builder builder)
    {
      this.Id = builder.id;
      this.ReferenceId = builder.referenceId;
      this.Category = builder.category;
      this.Type = builder.type;
      this.SecondaryType = builder.secondaryType;
      this.Status = builder.status;
      this.CreatedBy = builder.createdBy;
      this.Title = builder.title;
      this.Description = builder.description;
      this.UserActions = builder.userActions;
      this.TransactionsMetadata = builder.transactionsMetadata;
      this.AccountMetadata = builder.accountMetadata;
      this.OrdersMetadata = builder.ordersMetadata;
      this.Symbols = builder.symbols;
      this.CreatedAt = builder.createdAt;
      this.UpdatedAt = builder.updatedAt;
      this.HierarchyType = builder.hierarchyType;
    }

    public class Builder
    {
#pragma warning disable SA1307, SA1401
      internal string? id;
      internal string? referenceId;
      internal ActivityCategory? category;
      internal PrimeActivityType? type;
      internal ActivitySecondaryType? secondaryType;
      internal ActivityStatus? status;
      internal string? createdBy;
      internal string? title;
      internal string? description;
      internal List<UserAction>? userActions;
      internal ActivityMetadataTransactions? transactionsMetadata;
      internal ActivityMetadataAccount? accountMetadata;
      internal Object? ordersMetadata;
      internal List<string>? symbols;
      internal string? createdAt;
      internal string? updatedAt;
      internal HierarchyType? hierarchyType;
#pragma warning restore SA1307, SA1401
      public Builder WithId(string? id)
      {
        this.id = id;
        return this;
      }
      public Builder WithReferenceId(string? referenceId)
      {
        this.referenceId = referenceId;
        return this;
      }
      public Builder WithCategory(ActivityCategory? category)
      {
        this.category = category;
        return this;
      }
      public Builder WithType(PrimeActivityType? type)
      {
        this.type = type;
        return this;
      }
      public Builder WithSecondaryType(ActivitySecondaryType? secondaryType)
      {
        this.secondaryType = secondaryType;
        return this;
      }
      public Builder WithStatus(ActivityStatus? status)
      {
        this.status = status;
        return this;
      }
      public Builder WithCreatedBy(string? createdBy)
      {
        this.createdBy = createdBy;
        return this;
      }
      public Builder WithTitle(string? title)
      {
        this.title = title;
        return this;
      }
      public Builder WithDescription(string? description)
      {
        this.description = description;
        return this;
      }
      public Builder WithUserActions(List<UserAction>? userActions)
      {
        this.userActions = userActions;
        return this;
      }
      public Builder WithTransactionsMetadata(ActivityMetadataTransactions? transactionsMetadata)
      {
        this.transactionsMetadata = transactionsMetadata;
        return this;
      }
      public Builder WithAccountMetadata(ActivityMetadataAccount? accountMetadata)
      {
        this.accountMetadata = accountMetadata;
        return this;
      }
      public Builder WithOrdersMetadata(Object? ordersMetadata)
      {
        this.ordersMetadata = ordersMetadata;
        return this;
      }
      public Builder WithSymbols(List<string>? symbols)
      {
        this.symbols = symbols;
        return this;
      }
      public Builder WithCreatedAt(string? createdAt)
      {
        this.createdAt = createdAt;
        return this;
      }
      public Builder WithUpdatedAt(string? updatedAt)
      {
        this.updatedAt = updatedAt;
        return this;
      }
      public Builder WithHierarchyType(HierarchyType? hierarchyType)
      {
        this.hierarchyType = hierarchyType;
        return this;
      }
      public Activity Build()
      {
        return new Activity(this);
      }
    }
  }

}
