/*
 * Copyright 2025-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

namespace CoinbaseSdk.Prime.Model
{
  using CoinbaseSdk.Prime.Model.Enums;
  using System.Text.Json.Serialization;

  public class ActivityMetadataConsensus
  {
    /// <summary>
    /// Deadline for approval of an activity
    /// </summary>
    [JsonPropertyName("approval_deadline")]
    public string? approval_deadline { get; set; }

    /// <summary>
    /// If activity has passed consensus threshold
    /// </summary>
    [JsonPropertyName("has_passed_consensus")]
    public bool? has_passed_consensus { get; set; }

    public ActivityMetadataConsensus() { }

    public ActivityMetadataConsensus(Builder builder)
    {
      this.approval_deadline = builder.approval_deadline;
      this.has_passed_consensus = builder.has_passed_consensus;
    }

    public class Builder
    {
      private string? approval_deadline;

      private bool? has_passed_consensus;

      public Builder Withapproval_deadline(string? approval_deadline)
      {
        this.approval_deadline = approval_deadline;
        return this;
      }

      public Builder Withhas_passed_consensus(bool? has_passed_consensus)
      {
        this.has_passed_consensus = has_passed_consensus;
        return this;
      }

      public ActivityMetadataConsensus Build()
      {
        return new ActivityMetadataConsensus(this);
      }
    }
  }

}
