/*
 * Copyright 2025-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

namespace CoinbaseSdk.Prime.Model
{
  using CoinbaseSdk.Prime.Model.Enums;
  using CoinbaseSdk.Prime.Model.AddressEntry;
  using CoinbaseSdk.Prime.Model.NetworkType;
  using System.Text.Json.Serialization;

  public class AddressGroup
  {
    [JsonPropertyName("id")]
    public string? id { get; set; }

    [JsonPropertyName("name")]
    public string? name { get; set; }

    [JsonPropertyName("network_type")]
    public NetworkType? network_type { get; set; }

    [JsonPropertyName("addresses")]
    public List<AddressEntry>? addresses { get; set; }

    [JsonPropertyName("added_at")]
    public DateTime? added_at { get; set; }

    public AddressGroup() { }

    public AddressGroup(Builder builder)
    {
      this.id = builder.id;
      this.name = builder.name;
      this.network_type = builder.network_type;
      this.addresses = builder.addresses;
      this.added_at = builder.added_at;
    }

    public class Builder
    {
      private string? id;

      private string? name;

      private NetworkType? network_type;

      private List<AddressEntry>? addresses;

      private DateTime? added_at;

      public Builder Withid(string? id)
      {
        this.id = id;
        return this;
      }

      public Builder Withname(string? name)
      {
        this.name = name;
        return this;
      }

      public Builder Withnetwork_type(NetworkType? network_type)
      {
        this.network_type = network_type;
        return this;
      }

      public Builder Withaddresses(List<AddressEntry>? addresses)
      {
        this.addresses = addresses;
        return this;
      }

      public Builder Withadded_at(DateTime? added_at)
      {
        this.added_at = added_at;
        return this;
      }

      public AddressGroup Build()
      {
        return new AddressGroup(this);
      }
    }
  }

}
