/*
 * Copyright 2025-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

namespace CoinbaseSdk.Prime.Model
{
  using CoinbaseSdk.Prime.Model.Enums;
  using System.Text.Json.Serialization;

  public class AggregatedFiatBalance
  {
    [JsonPropertyName("total")]
    public string? total { get; set; }

    [JsonPropertyName("holds")]
    public string? holds { get; set; }

    public AggregatedFiatBalance() { }

    public AggregatedFiatBalance(Builder builder)
    {
      this.total = builder.total;
      this.holds = builder.holds;
    }

    public class Builder
    {
      private string? total;

      private string? holds;

      public Builder Withtotal(string? total)
      {
        this.total = total;
        return this;
      }

      public Builder Withholds(string? holds)
      {
        this.holds = holds;
        return this;
      }

      public AggregatedFiatBalance Build()
      {
        return new AggregatedFiatBalance(this);
      }
    }
  }

}
