// <auto-generated/>
#nullable enable

/*
 * Copyright 2026-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 *  Do not edit the class manually.
 */


namespace CoinbaseSdk.Prime.Model
{
  using CoinbaseSdk.Prime.Model.Enums;

  public class Allocation
  {
    /// <summary>
    /// The ID that ties together an allocation and all of its legs.
    /// </summary>
    public string? RootId { get; set; }
    /// <summary>
    /// The ID of the allocation if this allocation is a reversal. In this case, the root_id would be the original allocation ID.
    /// </summary>
    public string? ReversalId { get; set; }
    /// <summary>
    /// Time the final leg of the root allocation was completed.
    /// </summary>
    public DateTime? AllocationCompletedAt { get; set; }
    /// <summary>
    /// The ID of the user that created the allocation.
    /// </summary>
    public string? UserId { get; set; }
    /// <summary>
    /// The ID of the product of the orders allocated.
    /// </summary>
    public string? ProductId { get; set; }
    /// <summary>
    /// - UNKNOWN_ORDER_SIDE: nil value.
    /// - BUY: Buy order.
    /// - SELL: Sell order.
    /// </summary>
    public OrderSide? Side { get; set; }
    /// <summary>
    /// Price the allocation was done at.
    /// </summary>
    public string? AvgPrice { get; set; }
    /// <summary>
    /// Amount allocated in base asset units.
    /// </summary>
    public string? BaseQuantity { get; set; }
    /// <summary>
    /// Amount allocated in quote asset units.
    /// </summary>
    public string? QuoteValue { get; set; }
    /// <summary>
    /// Fees from original trade execution allocated in quote asset units.
    /// </summary>
    public string? FeesAllocated { get; set; }
    public AllocationStatus? Status { get; set; }
    /// <summary>
    /// Portfolio ID of the source portfolio.
    /// </summary>
    public string? Source { get; set; }
    /// <summary>
    /// All order IDs that were aggregated to calculate the avg_price, quantity to allocate in each leg. Each order_id should tie back to the single allocation root_id.
    /// </summary>
    public List<string>? OrderIds { get; set; }
    /// <summary>
    /// Array of objects, each containing the leg ID, destination portfolio ID and amount in chosen units allocated to each portfolio: [{leg_id, portfolio_id, allocation_base, allocation_quote}, {leg_id, portfolio_id, allocation_base, allocation_quote}...]
    /// </summary>
    public List<DestinationAlloc>? Destinations { get; set; }
    /// <summary>
    /// The netting ID of the allocation, not empty if the allocation was submitted as part of a net allocation
    /// </summary>
    public string? NettingId { get; set; }
    public Allocation() { }

    public Allocation(Builder builder)
    {
      this.RootId = builder.rootId;
      this.ReversalId = builder.reversalId;
      this.AllocationCompletedAt = builder.allocationCompletedAt;
      this.UserId = builder.userId;
      this.ProductId = builder.productId;
      this.Side = builder.side;
      this.AvgPrice = builder.avgPrice;
      this.BaseQuantity = builder.baseQuantity;
      this.QuoteValue = builder.quoteValue;
      this.FeesAllocated = builder.feesAllocated;
      this.Status = builder.status;
      this.Source = builder.source;
      this.OrderIds = builder.orderIds;
      this.Destinations = builder.destinations;
      this.NettingId = builder.nettingId;
    }

    public class Builder
    {
#pragma warning disable SA1307, SA1401
      internal string? rootId;
      internal string? reversalId;
      internal DateTime? allocationCompletedAt;
      internal string? userId;
      internal string? productId;
      internal OrderSide? side;
      internal string? avgPrice;
      internal string? baseQuantity;
      internal string? quoteValue;
      internal string? feesAllocated;
      internal AllocationStatus? status;
      internal string? source;
      internal List<string>? orderIds;
      internal List<DestinationAlloc>? destinations;
      internal string? nettingId;
#pragma warning restore SA1307, SA1401
      public Builder WithRootId(string? rootId)
      {
        this.rootId = rootId;
        return this;
      }
      public Builder WithReversalId(string? reversalId)
      {
        this.reversalId = reversalId;
        return this;
      }
      public Builder WithAllocationCompletedAt(DateTime? allocationCompletedAt)
      {
        this.allocationCompletedAt = allocationCompletedAt;
        return this;
      }
      public Builder WithUserId(string? userId)
      {
        this.userId = userId;
        return this;
      }
      public Builder WithProductId(string? productId)
      {
        this.productId = productId;
        return this;
      }
      public Builder WithSide(OrderSide? side)
      {
        this.side = side;
        return this;
      }
      public Builder WithAvgPrice(string? avgPrice)
      {
        this.avgPrice = avgPrice;
        return this;
      }
      public Builder WithBaseQuantity(string? baseQuantity)
      {
        this.baseQuantity = baseQuantity;
        return this;
      }
      public Builder WithQuoteValue(string? quoteValue)
      {
        this.quoteValue = quoteValue;
        return this;
      }
      public Builder WithFeesAllocated(string? feesAllocated)
      {
        this.feesAllocated = feesAllocated;
        return this;
      }
      public Builder WithStatus(AllocationStatus? status)
      {
        this.status = status;
        return this;
      }
      public Builder WithSource(string? source)
      {
        this.source = source;
        return this;
      }
      public Builder WithOrderIds(List<string>? orderIds)
      {
        this.orderIds = orderIds;
        return this;
      }
      public Builder WithDestinations(List<DestinationAlloc>? destinations)
      {
        this.destinations = destinations;
        return this;
      }
      public Builder WithNettingId(string? nettingId)
      {
        this.nettingId = nettingId;
        return this;
      }
      public Allocation Build()
      {
        return new Allocation(this);
      }
    }
  }

}
