// <auto-generated/>
#nullable enable

/*
 * Copyright 2025-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */


namespace CoinbaseSdk.Prime.Model
{
  using System.Text.Json.Serialization;
  using CoinbaseSdk.Prime.Model.Enums;

  public class AssetChange
  {
    [JsonPropertyName("type")]
    public AssetChangeType? Type { get; set; }
    /// <summary>
    /// The currency symbol associated with the balance operation
    /// </summary>
    [JsonPropertyName("symbol")]
    public string? Symbol { get; set; }
    /// <summary>
    /// The amount in whole units being transferred or approved
    /// </summary>
    [JsonPropertyName("amount")]
    public string? Amount { get; set; }
    [JsonPropertyName("collection")]
    public NftCollection? Collection { get; set; }
    [JsonPropertyName("item")]
    public NftItem? Item { get; set; }
    public AssetChange() { }

    public AssetChange(Builder builder)
    {
      this.Type = builder.type;
      this.Symbol = builder.symbol;
      this.Amount = builder.amount;
      this.Collection = builder.collection;
      this.Item = builder.item;
    }

    public class Builder
    {
#pragma warning disable SA1307, SA1401
      internal AssetChangeType? type;
      internal string? symbol;
      internal string? amount;
      internal NftCollection? collection;
      internal NftItem? item;
#pragma warning restore SA1307, SA1401
      public Builder WithType(AssetChangeType? type)
      {
        this.type = type;
        return this;
      }
      public Builder WithSymbol(string? symbol)
      {
        this.symbol = symbol;
        return this;
      }
      public Builder WithAmount(string? amount)
      {
        this.amount = amount;
        return this;
      }
      public Builder WithCollection(NftCollection? collection)
      {
        this.collection = collection;
        return this;
      }
      public Builder WithItem(NftItem? item)
      {
        this.item = item;
        return this;
      }
      public AssetChange Build()
      {
        return new AssetChange(this);
      }
    }
  }

}
