// <auto-generated/>
#nullable enable

/*
 * Copyright 2025-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */


namespace CoinbaseSdk.Prime.Model
{
  using System.Text.Json.Serialization;

  public class Balance
  {
    /// <summary>
    /// The display symbol for the asset
    /// </summary>
    [JsonPropertyName("symbol")]
    public string? Symbol { get; set; }
    /// <summary>
    /// The total amount in whole units with full precision. Includes the &#x60;holds&#x60; amount.
    /// </summary>
    [JsonPropertyName("amount")]
    public string? Amount { get; set; }
    /// <summary>
    /// Amount that is currently held in obligation to an open order&#39;s position or a pending withdrawal
    /// </summary>
    [JsonPropertyName("holds")]
    public string? Holds { get; set; }
    /// <summary>
    /// Amount that is currently locked due to bonding/staking, potentially subject to an unbonding period, in whole units
    /// </summary>
    [JsonPropertyName("bonded_amount")]
    public string? BondedAmount { get; set; }
    /// <summary>
    /// Amount that must remain in the wallet due to the protocol, in whole units
    /// </summary>
    [JsonPropertyName("reserved_amount")]
    public string? ReservedAmount { get; set; }
    /// <summary>
    /// Amount that is in the process of unbonding, in whole units
    /// </summary>
    [JsonPropertyName("unbonding_amount")]
    public string? UnbondingAmount { get; set; }
    /// <summary>
    /// Unrealized amount subject to a vesting schedule, in whole units
    /// </summary>
    [JsonPropertyName("unvested_amount")]
    public string? UnvestedAmount { get; set; }
    /// <summary>
    /// Pending bonding/staking rewards that have not yet been realized, in whole units
    /// </summary>
    [JsonPropertyName("pending_rewards_amount")]
    public string? PendingRewardsAmount { get; set; }
    /// <summary>
    /// Previously realized bonding/staking rewards, in whole units
    /// </summary>
    [JsonPropertyName("past_rewards_amount")]
    public string? PastRewardsAmount { get; set; }
    /// <summary>
    /// Amount available for bonding/staking, in whole units
    /// </summary>
    [JsonPropertyName("bondable_amount")]
    public string? BondableAmount { get; set; }
    /// <summary>
    /// Amount available to withdraw, in whole units
    /// </summary>
    [JsonPropertyName("withdrawable_amount")]
    public string? WithdrawableAmount { get; set; }
    /// <summary>
    /// The total amount in fiat unit
    /// </summary>
    [JsonPropertyName("fiat_amount")]
    public string? FiatAmount { get; set; }
    /// <summary>
    /// Amount available for unbonding/unstaking, in whole units
    /// </summary>
    [JsonPropertyName("unbondable_amount")]
    public string? UnbondableAmount { get; set; }
    public Balance() { }

    public Balance(Builder builder)
    {
      this.Symbol = builder.symbol;
      this.Amount = builder.amount;
      this.Holds = builder.holds;
      this.BondedAmount = builder.bondedAmount;
      this.ReservedAmount = builder.reservedAmount;
      this.UnbondingAmount = builder.unbondingAmount;
      this.UnvestedAmount = builder.unvestedAmount;
      this.PendingRewardsAmount = builder.pendingRewardsAmount;
      this.PastRewardsAmount = builder.pastRewardsAmount;
      this.BondableAmount = builder.bondableAmount;
      this.WithdrawableAmount = builder.withdrawableAmount;
      this.FiatAmount = builder.fiatAmount;
      this.UnbondableAmount = builder.unbondableAmount;
    }

    public class Builder
    {
#pragma warning disable SA1307, SA1401
      internal string? symbol;
      internal string? amount;
      internal string? holds;
      internal string? bondedAmount;
      internal string? reservedAmount;
      internal string? unbondingAmount;
      internal string? unvestedAmount;
      internal string? pendingRewardsAmount;
      internal string? pastRewardsAmount;
      internal string? bondableAmount;
      internal string? withdrawableAmount;
      internal string? fiatAmount;
      internal string? unbondableAmount;
#pragma warning restore SA1307, SA1401
      public Builder WithSymbol(string? symbol)
      {
        this.symbol = symbol;
        return this;
      }
      public Builder WithAmount(string? amount)
      {
        this.amount = amount;
        return this;
      }
      public Builder WithHolds(string? holds)
      {
        this.holds = holds;
        return this;
      }
      public Builder WithBondedAmount(string? bondedAmount)
      {
        this.bondedAmount = bondedAmount;
        return this;
      }
      public Builder WithReservedAmount(string? reservedAmount)
      {
        this.reservedAmount = reservedAmount;
        return this;
      }
      public Builder WithUnbondingAmount(string? unbondingAmount)
      {
        this.unbondingAmount = unbondingAmount;
        return this;
      }
      public Builder WithUnvestedAmount(string? unvestedAmount)
      {
        this.unvestedAmount = unvestedAmount;
        return this;
      }
      public Builder WithPendingRewardsAmount(string? pendingRewardsAmount)
      {
        this.pendingRewardsAmount = pendingRewardsAmount;
        return this;
      }
      public Builder WithPastRewardsAmount(string? pastRewardsAmount)
      {
        this.pastRewardsAmount = pastRewardsAmount;
        return this;
      }
      public Builder WithBondableAmount(string? bondableAmount)
      {
        this.bondableAmount = bondableAmount;
        return this;
      }
      public Builder WithWithdrawableAmount(string? withdrawableAmount)
      {
        this.withdrawableAmount = withdrawableAmount;
        return this;
      }
      public Builder WithFiatAmount(string? fiatAmount)
      {
        this.fiatAmount = fiatAmount;
        return this;
      }
      public Builder WithUnbondableAmount(string? unbondableAmount)
      {
        this.unbondableAmount = unbondableAmount;
        return this;
      }
      public Balance Build()
      {
        return new Balance(this);
      }
    }
  }

}
