// <auto-generated/>
#nullable enable

/*
 * Copyright 2025-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */


namespace CoinbaseSdk.Prime.Model
{
  using System.Text.Json.Serialization;

  public class BlockchainAddress
  {
    /// <summary>
    /// The address on the network
    /// </summary>
    [JsonPropertyName("address")]
    public string? Address { get; set; }
    /// <summary>
    /// The account identifier (used on some chains to distinguish accounts using the same address)
    /// </summary>
    [JsonPropertyName("account_identifier")]
    public string? AccountIdentifier { get; set; }
    [JsonPropertyName("network")]
    public Network? Network { get; set; }
    public BlockchainAddress() { }

    public BlockchainAddress(Builder builder)
    {
      this.Address = builder.address;
      this.AccountIdentifier = builder.accountIdentifier;
      this.Network = builder.network;
    }

    public class Builder
    {
#pragma warning disable SA1307, SA1401
      internal string? address;
      internal string? accountIdentifier;
      internal Network? network;
#pragma warning restore SA1307, SA1401
      public Builder WithAddress(string? address)
      {
        this.address = address;
        return this;
      }
      public Builder WithAccountIdentifier(string? accountIdentifier)
      {
        this.accountIdentifier = accountIdentifier;
        return this;
      }
      public Builder WithNetwork(Network? network)
      {
        this.network = network;
        return this;
      }
      public BlockchainAddress Build()
      {
        return new BlockchainAddress(this);
      }
    }
  }

}
