// <auto-generated/>
#nullable enable

/*
 * Copyright 2025-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */


namespace CoinbaseSdk.Prime.Model
{
  using System.Text.Json.Serialization;

  public class BuyingPower
  {
    /// <summary>
    /// The unique ID of the portfolio
    /// </summary>
    [JsonPropertyName("portfolio_id")]
    public string? PortfolioId { get; set; }
    /// <summary>
    /// The symbol for the base currency
    /// </summary>
    [JsonPropertyName("base_currency")]
    public string? BaseCurrency { get; set; }
    /// <summary>
    /// The symbol for the quote currency
    /// </summary>
    [JsonPropertyName("quote_currency")]
    public string? QuoteCurrency { get; set; }
    /// <summary>
    /// The buying power for the base currency
    /// </summary>
    [JsonPropertyName("base_buying_power")]
    public string? BaseBuyingPower { get; set; }
    /// <summary>
    /// The buying power for the quote currency
    /// </summary>
    [JsonPropertyName("quote_buying_power")]
    public string? QuoteBuyingPower { get; set; }
    public BuyingPower() { }

    public BuyingPower(Builder builder)
    {
      this.PortfolioId = builder.portfolioId;
      this.BaseCurrency = builder.baseCurrency;
      this.QuoteCurrency = builder.quoteCurrency;
      this.BaseBuyingPower = builder.baseBuyingPower;
      this.QuoteBuyingPower = builder.quoteBuyingPower;
    }

    public class Builder
    {
#pragma warning disable SA1307, SA1401
      internal string? portfolioId;
      internal string? baseCurrency;
      internal string? quoteCurrency;
      internal string? baseBuyingPower;
      internal string? quoteBuyingPower;
#pragma warning restore SA1307, SA1401
      public Builder WithPortfolioId(string? portfolioId)
      {
        this.portfolioId = portfolioId;
        return this;
      }
      public Builder WithBaseCurrency(string? baseCurrency)
      {
        this.baseCurrency = baseCurrency;
        return this;
      }
      public Builder WithQuoteCurrency(string? quoteCurrency)
      {
        this.quoteCurrency = quoteCurrency;
        return this;
      }
      public Builder WithBaseBuyingPower(string? baseBuyingPower)
      {
        this.baseBuyingPower = baseBuyingPower;
        return this;
      }
      public Builder WithQuoteBuyingPower(string? quoteBuyingPower)
      {
        this.quoteBuyingPower = quoteBuyingPower;
        return this;
      }
      public BuyingPower Build()
      {
        return new BuyingPower(this);
      }
    }
  }

}
