/*
 * Copyright 2025-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

namespace CoinbaseSdk.Prime.Model
{
  using CoinbaseSdk.Prime.Model.Enums;
  using System.Text.Json.Serialization;

  public class BuyingPower
  {
    /// <summary>
    /// The unique ID of the portfolio
    /// </summary>
    [JsonPropertyName("portfolio_id")]
    public string? portfolio_id { get; set; }

    /// <summary>
    /// The symbol for the base currency
    /// </summary>
    [JsonPropertyName("base_currency")]
    public string? base_currency { get; set; }

    /// <summary>
    /// The symbol for the quote currency
    /// </summary>
    [JsonPropertyName("quote_currency")]
    public string? quote_currency { get; set; }

    /// <summary>
    /// The buying power for the base currency
    /// </summary>
    [JsonPropertyName("base_buying_power")]
    public string? base_buying_power { get; set; }

    /// <summary>
    /// The buying power for the quote currency
    /// </summary>
    [JsonPropertyName("quote_buying_power")]
    public string? quote_buying_power { get; set; }

    public BuyingPower() { }

    public BuyingPower(Builder builder)
    {
      this.portfolio_id = builder.portfolio_id;
      this.base_currency = builder.base_currency;
      this.quote_currency = builder.quote_currency;
      this.base_buying_power = builder.base_buying_power;
      this.quote_buying_power = builder.quote_buying_power;
    }

    public static class Builder
    {
      private string? portfolio_id;

      private string? base_currency;

      private string? quote_currency;

      private string? base_buying_power;

      private string? quote_buying_power;

      public Builder portfolio_id(string? portfolio_id)
      {
        this.portfolio_id = portfolio_id;
        return this;
      }

      public Builder base_currency(string? base_currency)
      {
        this.base_currency = base_currency;
        return this;
      }

      public Builder quote_currency(string? quote_currency)
      {
        this.quote_currency = quote_currency;
        return this;
      }

      public Builder base_buying_power(string? base_buying_power)
      {
        this.base_buying_power = base_buying_power;
        return this;
      }

      public Builder quote_buying_power(string? quote_buying_power)
      {
        this.quote_buying_power = quote_buying_power;
        return this;
      }

      public BuyingPower Build()
      {
        return new BuyingPower(this);
      }
    }
  }

}
