/*
 * Copyright 2025-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

namespace CoinbaseSdk.Prime.Model
{
  using CoinbaseSdk.Prime.Model.Enums;
  using System.Text.Json.Serialization;

  public class Commission
  {
    /// <summary>
    /// Fee model (all_in or cost_plus)
    /// </summary>
    [JsonPropertyName("type")]
    public string? type { get; set; }

    /// <summary>
    /// Commission rate (in whole percentage. Commission of 15bps is \&quot;0.0015\&quot;)
    /// </summary>
    [JsonPropertyName("rate")]
    public string? rate { get; set; }

    /// <summary>
    /// Average 30 days over past 3 months (e.g. 90 days divided by 3)
    /// </summary>
    [JsonPropertyName("trading_volume")]
    public string? trading_volume { get; set; }

    public Commission() { }

    public Commission(Builder builder)
    {
      this.type = builder.type;
      this.rate = builder.rate;
      this.trading_volume = builder.trading_volume;
    }

    public static class Builder
    {
      private string? type;

      private string? rate;

      private string? trading_volume;

      public Builder type(string? type)
      {
        this.type = type;
        return this;
      }

      public Builder rate(string? rate)
      {
        this.rate = rate;
        return this;
      }

      public Builder trading_volume(string? trading_volume)
      {
        this.trading_volume = trading_volume;
        return this;
      }

      public Commission Build()
      {
        return new Commission(this);
      }
    }
  }

}
