// <auto-generated/>
#nullable enable

/*
 * Copyright 2026-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 *  Do not edit the class manually.
 */


namespace CoinbaseSdk.Prime.Model
{

  public class CommissionDetailTotal
  {
    public string? TotalCommission { get; set; }
    /// <summary>
    /// CB fee
    /// </summary>
    public string? ClientCommission { get; set; }
    /// <summary>
    /// Exchange fees
    /// </summary>
    public string? VenueCommission { get; set; }
    public string? CesCommission { get; set; }
    public string? FinancingCommission { get; set; }
    /// <summary>
    /// NFA fees
    /// </summary>
    public string? RegulatoryCommission { get; set; }
    /// <summary>
    /// Clearing fees
    /// </summary>
    public string? ClearingCommission { get; set; }
    public CommissionDetailTotal() { }

    public CommissionDetailTotal(Builder builder)
    {
      this.TotalCommission = builder.totalCommission;
      this.ClientCommission = builder.clientCommission;
      this.VenueCommission = builder.venueCommission;
      this.CesCommission = builder.cesCommission;
      this.FinancingCommission = builder.financingCommission;
      this.RegulatoryCommission = builder.regulatoryCommission;
      this.ClearingCommission = builder.clearingCommission;
    }

    public class Builder
    {
#pragma warning disable SA1307, SA1401
      internal string? totalCommission;
      internal string? clientCommission;
      internal string? venueCommission;
      internal string? cesCommission;
      internal string? financingCommission;
      internal string? regulatoryCommission;
      internal string? clearingCommission;
#pragma warning restore SA1307, SA1401
      public Builder WithTotalCommission(string? totalCommission)
      {
        this.totalCommission = totalCommission;
        return this;
      }
      public Builder WithClientCommission(string? clientCommission)
      {
        this.clientCommission = clientCommission;
        return this;
      }
      public Builder WithVenueCommission(string? venueCommission)
      {
        this.venueCommission = venueCommission;
        return this;
      }
      public Builder WithCesCommission(string? cesCommission)
      {
        this.cesCommission = cesCommission;
        return this;
      }
      public Builder WithFinancingCommission(string? financingCommission)
      {
        this.financingCommission = financingCommission;
        return this;
      }
      public Builder WithRegulatoryCommission(string? regulatoryCommission)
      {
        this.regulatoryCommission = regulatoryCommission;
        return this;
      }
      public Builder WithClearingCommission(string? clearingCommission)
      {
        this.clearingCommission = clearingCommission;
        return this;
      }
      public CommissionDetailTotal Build()
      {
        return new CommissionDetailTotal(this);
      }
    }
  }

}
