// <auto-generated/>
#nullable enable

/*
 * Copyright 2025-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */


namespace CoinbaseSdk.Prime.Model
{
  using System.Text.Json.Serialization;

  public class Conversion
  {
    /// <summary>
    /// Conversion details
    /// </summary>
    [JsonPropertyName("conversion_details")]
    public List<ConversionDetail>? ConversionDetails { get; set; }
    [JsonPropertyName("short_collateral")]
    public ShortCollateral? ShortCollateral { get; set; }
    /// <summary>
    /// The UTC date time used for conversion
    /// </summary>
    [JsonPropertyName("conversion_datetime")]
    public string? ConversionDatetime { get; set; }
    /// <summary>
    /// Portfolio Id
    /// </summary>
    [JsonPropertyName("portfolio_id")]
    public string? PortfolioId { get; set; }
    public Conversion() { }

    public Conversion(Builder builder)
    {
      this.ConversionDetails = builder.conversionDetails;
      this.ShortCollateral = builder.shortCollateral;
      this.ConversionDatetime = builder.conversionDatetime;
      this.PortfolioId = builder.portfolioId;
    }

    public class Builder
    {
#pragma warning disable SA1307, SA1401
      internal List<ConversionDetail>? conversionDetails;
      internal ShortCollateral? shortCollateral;
      internal string? conversionDatetime;
      internal string? portfolioId;
#pragma warning restore SA1307, SA1401
      public Builder WithConversionDetails(List<ConversionDetail>? conversionDetails)
      {
        this.conversionDetails = conversionDetails;
        return this;
      }
      public Builder WithShortCollateral(ShortCollateral? shortCollateral)
      {
        this.shortCollateral = shortCollateral;
        return this;
      }
      public Builder WithConversionDatetime(string? conversionDatetime)
      {
        this.conversionDatetime = conversionDatetime;
        return this;
      }
      public Builder WithPortfolioId(string? portfolioId)
      {
        this.portfolioId = portfolioId;
        return this;
      }
      public Conversion Build()
      {
        return new Conversion(this);
      }
    }
  }

}
