// <auto-generated/>
#nullable enable

/*
 * Copyright 2025-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */


namespace CoinbaseSdk.Prime.Model
{
  using System.Text.Json.Serialization;

  public class Counterparty
  {
    /// <summary>
    /// The unique counterparty ID for the portfolio
    /// </summary>
    [JsonPropertyName("counterparty_id")]
    public string? CounterpartyId { get; set; }
    public Counterparty() { }

    public Counterparty(Builder builder)
    {
      this.CounterpartyId = builder.counterpartyId;
    }

    public class Builder
    {
#pragma warning disable SA1307, SA1401
      internal string? counterpartyId;
#pragma warning restore SA1307, SA1401
      public Builder WithCounterpartyId(string? counterpartyId)
      {
        this.counterpartyId = counterpartyId;
        return this;
      }
      public Counterparty Build()
      {
        return new Counterparty(this);
      }
    }
  }

}
