// <auto-generated/>
#nullable enable

/*
 * Copyright 2025-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */


namespace CoinbaseSdk.Prime.Model
{
  using System.Text.Json.Serialization;

  public class CreateNetAllocationResponseBody
  {
    /// <summary>
    /// The success boolean for the post net allocation
    /// </summary>
    [JsonPropertyName("success")]
    public bool Success { get; set; } = default!;
    /// <summary>
    /// The netting_id for the post net allocation
    /// </summary>
    [JsonPropertyName("netting_id")]
    public string NettingId { get; set; } = default!;
    /// <summary>
    /// The allocation id of the buy allocation in net allocation
    /// </summary>
    [JsonPropertyName("buy_allocation_id")]
    public string BuyAllocationId { get; set; } = default!;
    /// <summary>
    /// The allocation id of the sell allocation in net allocation
    /// </summary>
    [JsonPropertyName("sell_allocation_id")]
    public string SellAllocationId { get; set; } = default!;
    /// <summary>
    /// The failure reason for the post net allocation
    /// </summary>
    [JsonPropertyName("failure_reason")]
    public string FailureReason { get; set; } = default!;
    public CreateNetAllocationResponseBody() { }

    public CreateNetAllocationResponseBody(Builder builder)
    {
      this.Success = builder.success;
      this.NettingId = builder.nettingId;
      this.BuyAllocationId = builder.buyAllocationId;
      this.SellAllocationId = builder.sellAllocationId;
      this.FailureReason = builder.failureReason;
    }

    public class Builder
    {
#pragma warning disable SA1307, SA1401
      internal bool success = default!;
      internal string nettingId = default!;
      internal string buyAllocationId = default!;
      internal string sellAllocationId = default!;
      internal string failureReason = default!;
#pragma warning restore SA1307, SA1401
      public Builder WithSuccess(bool success)
      {
        this.success = success;
        return this;
      }
      public Builder WithNettingId(string nettingId)
      {
        this.nettingId = nettingId;
        return this;
      }
      public Builder WithBuyAllocationId(string buyAllocationId)
      {
        this.buyAllocationId = buyAllocationId;
        return this;
      }
      public Builder WithSellAllocationId(string sellAllocationId)
      {
        this.sellAllocationId = sellAllocationId;
        return this;
      }
      public Builder WithFailureReason(string failureReason)
      {
        this.failureReason = failureReason;
        return this;
      }
      public CreateNetAllocationResponseBody Build()
      {
        return new CreateNetAllocationResponseBody(this);
      }
    }
  }

}
