// <auto-generated/>
#nullable enable

/*
 * Copyright 2025-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */


namespace CoinbaseSdk.Prime.Model
{
  using System.Text.Json.Serialization;

  public class CreateAllocationResponseBody
  {
    /// <summary>
    /// The success boolean for the post allocation
    /// </summary>
    [JsonPropertyName("success")]
    public bool Success { get; set; } = default!;
    /// <summary>
    /// The allocation id for the post allocation
    /// </summary>
    [JsonPropertyName("allocation_id")]
    public string AllocationId { get; set; } = default!;
    /// <summary>
    /// The failure reason for the post allocation
    /// </summary>
    [JsonPropertyName("failure_reason")]
    public string FailureReason { get; set; } = default!;
    public CreateAllocationResponseBody() { }

    public CreateAllocationResponseBody(Builder builder)
    {
      this.Success = builder.success;
      this.AllocationId = builder.allocationId;
      this.FailureReason = builder.failureReason;
    }

    public class Builder
    {
#pragma warning disable SA1307, SA1401
      internal bool success = default!;
      internal string allocationId = default!;
      internal string failureReason = default!;
#pragma warning restore SA1307, SA1401
      public Builder WithSuccess(bool success)
      {
        this.success = success;
        return this;
      }
      public Builder WithAllocationId(string allocationId)
      {
        this.allocationId = allocationId;
        return this;
      }
      public Builder WithFailureReason(string failureReason)
      {
        this.failureReason = failureReason;
        return this;
      }
      public CreateAllocationResponseBody Build()
      {
        return new CreateAllocationResponseBody(this);
      }
    }
  }

}
