// <auto-generated/>
#nullable enable

/*
 * Copyright 2026-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 *  Do not edit the class manually.
 */


namespace CoinbaseSdk.Prime.Model
{
  /// <summary>
  /// Breakdown of the components of spot equity.
  /// </summary>

  public class CrossMarginPrimeSpotEquityBreakdown
  {
    /// <summary>
    /// Pm cash balance component of spot equity.
    /// </summary>
    public string? CashBalance { get; set; }
    /// <summary>
    /// Long market value component of spot equity.
    /// </summary>
    public string? LongMarketValue { get; set; }
    /// <summary>
    /// Short market value component of spot equity.
    /// </summary>
    public string? ShortMarketValue { get; set; }
    /// <summary>
    /// Short collateral component of spot equity.
    /// </summary>
    public string? ShortCollateral { get; set; }
    /// <summary>
    /// Pending transfers affecting spot equity.
    /// </summary>
    public string? PendingTransfers { get; set; }
    public CrossMarginPrimeSpotEquityBreakdown() { }

    public CrossMarginPrimeSpotEquityBreakdown(Builder builder)
    {
      this.CashBalance = builder.cashBalance;
      this.LongMarketValue = builder.longMarketValue;
      this.ShortMarketValue = builder.shortMarketValue;
      this.ShortCollateral = builder.shortCollateral;
      this.PendingTransfers = builder.pendingTransfers;
    }

    public class Builder
    {
#pragma warning disable SA1307, SA1401
      internal string? cashBalance;
      internal string? longMarketValue;
      internal string? shortMarketValue;
      internal string? shortCollateral;
      internal string? pendingTransfers;
#pragma warning restore SA1307, SA1401
      public Builder WithCashBalance(string? cashBalance)
      {
        this.cashBalance = cashBalance;
        return this;
      }
      public Builder WithLongMarketValue(string? longMarketValue)
      {
        this.longMarketValue = longMarketValue;
        return this;
      }
      public Builder WithShortMarketValue(string? shortMarketValue)
      {
        this.shortMarketValue = shortMarketValue;
        return this;
      }
      public Builder WithShortCollateral(string? shortCollateral)
      {
        this.shortCollateral = shortCollateral;
        return this;
      }
      public Builder WithPendingTransfers(string? pendingTransfers)
      {
        this.pendingTransfers = pendingTransfers;
        return this;
      }
      public CrossMarginPrimeSpotEquityBreakdown Build()
      {
        return new CrossMarginPrimeSpotEquityBreakdown(this);
      }
    }
  }

}
