// <auto-generated/>
#nullable enable

/*
 * Copyright 2026-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 *  Do not edit the class manually.
 */


namespace CoinbaseSdk.Prime.Model
{

  public class CrossMarginPrimeRiskNettingInfo
  {
    /// <summary>
    /// Derivatives Clearing Organization Margin Requirement (DMR) is the margin requirement for all futures positions, derived from the Derivatives Clearing Organization model
    /// </summary>
    public string? DcoMarginRequirement { get; set; }
    /// <summary>
    /// Portfolio Margin Requirement (PmR) is the margin requirement for all spot positions, derived from the Xm model
    /// </summary>
    public string? PortfolioMarginRequirement { get; set; }
    /// <summary>
    /// Integrated Portfolio Margin Requirement (IPMR) is the margin requirement for all spot positions + futures positions with underlying assets eligible in Portfolio Margin.
    /// </summary>
    public string? IntegratedPortfolioMarginRequirement { get; set; }
    /// <summary>
    /// Ineligible Futures Margin Requirement (IFMR) is the margin requirement for IPMR-ineligible futures contracts
    /// </summary>
    public string? IneligibleFuturesMarginRequirement { get; set; }
    public PrimeXMMarginRequirementBreakdown? PmrBreakdown { get; set; }
    public PrimeXMMarginRequirementBreakdown? IpmrBreakdown { get; set; }
    public PrimeXMOffsetCreditBreakdown? PortfolioMarginOffsetCreditBreakdown { get; set; }
    public PrimeXMOffsetCreditBreakdown? IntegratedPortfolioMarginOffsetCreditBreakdown { get; set; }
    /// <summary>
    /// Netted positions used in the model calculation.
    /// </summary>
    public List<CrossMarginPrimeXMPosition>? XmPositions { get; set; }
    public CrossMarginPrimeRiskNettingInfo() { }

    public CrossMarginPrimeRiskNettingInfo(Builder builder)
    {
      this.DcoMarginRequirement = builder.dcoMarginRequirement;
      this.PortfolioMarginRequirement = builder.portfolioMarginRequirement;
      this.IntegratedPortfolioMarginRequirement = builder.integratedPortfolioMarginRequirement;
      this.IneligibleFuturesMarginRequirement = builder.ineligibleFuturesMarginRequirement;
      this.PmrBreakdown = builder.pmrBreakdown;
      this.IpmrBreakdown = builder.ipmrBreakdown;
      this.PortfolioMarginOffsetCreditBreakdown = builder.portfolioMarginOffsetCreditBreakdown;
      this.IntegratedPortfolioMarginOffsetCreditBreakdown = builder.integratedPortfolioMarginOffsetCreditBreakdown;
      this.XmPositions = builder.xmPositions;
    }

    public class Builder
    {
#pragma warning disable SA1307, SA1401
      internal string? dcoMarginRequirement;
      internal string? portfolioMarginRequirement;
      internal string? integratedPortfolioMarginRequirement;
      internal string? ineligibleFuturesMarginRequirement;
      internal PrimeXMMarginRequirementBreakdown? pmrBreakdown;
      internal PrimeXMMarginRequirementBreakdown? ipmrBreakdown;
      internal PrimeXMOffsetCreditBreakdown? portfolioMarginOffsetCreditBreakdown;
      internal PrimeXMOffsetCreditBreakdown? integratedPortfolioMarginOffsetCreditBreakdown;
      internal List<CrossMarginPrimeXMPosition>? xmPositions;
#pragma warning restore SA1307, SA1401
      public Builder WithDcoMarginRequirement(string? dcoMarginRequirement)
      {
        this.dcoMarginRequirement = dcoMarginRequirement;
        return this;
      }
      public Builder WithPortfolioMarginRequirement(string? portfolioMarginRequirement)
      {
        this.portfolioMarginRequirement = portfolioMarginRequirement;
        return this;
      }
      public Builder WithIntegratedPortfolioMarginRequirement(string? integratedPortfolioMarginRequirement)
      {
        this.integratedPortfolioMarginRequirement = integratedPortfolioMarginRequirement;
        return this;
      }
      public Builder WithIneligibleFuturesMarginRequirement(string? ineligibleFuturesMarginRequirement)
      {
        this.ineligibleFuturesMarginRequirement = ineligibleFuturesMarginRequirement;
        return this;
      }
      public Builder WithPmrBreakdown(PrimeXMMarginRequirementBreakdown? pmrBreakdown)
      {
        this.pmrBreakdown = pmrBreakdown;
        return this;
      }
      public Builder WithIpmrBreakdown(PrimeXMMarginRequirementBreakdown? ipmrBreakdown)
      {
        this.ipmrBreakdown = ipmrBreakdown;
        return this;
      }
      public Builder WithPortfolioMarginOffsetCreditBreakdown(PrimeXMOffsetCreditBreakdown? portfolioMarginOffsetCreditBreakdown)
      {
        this.portfolioMarginOffsetCreditBreakdown = portfolioMarginOffsetCreditBreakdown;
        return this;
      }
      public Builder WithIntegratedPortfolioMarginOffsetCreditBreakdown(PrimeXMOffsetCreditBreakdown? integratedPortfolioMarginOffsetCreditBreakdown)
      {
        this.integratedPortfolioMarginOffsetCreditBreakdown = integratedPortfolioMarginOffsetCreditBreakdown;
        return this;
      }
      public Builder WithXmPositions(List<CrossMarginPrimeXMPosition>? xmPositions)
      {
        this.xmPositions = xmPositions;
        return this;
      }
      public CrossMarginPrimeRiskNettingInfo Build()
      {
        return new CrossMarginPrimeRiskNettingInfo(this);
      }
    }
  }

}
