// <auto-generated/>
#nullable enable

/*
 * Copyright 2026-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 *  Do not edit the class manually.
 */


namespace CoinbaseSdk.Prime.Model
{

  public class CrossMarginPrimeDerivativesEquityBreakdown
  {
    /// <summary>
    /// Derivatives cash balance component.
    /// </summary>
    public string? CashBalance { get; set; }
    /// <summary>
    /// Unrealized PnL component of derivatives equity.
    /// </summary>
    public string? UnrealizedPnl { get; set; }
    /// <summary>
    /// Realized PnL component of derivatives equity.
    /// </summary>
    public string? RealizedPnl { get; set; }
    /// <summary>
    /// Accrued funding PnL component of derivatives equity.
    /// </summary>
    public string? AccruedFundingPnl { get; set; }
    public CrossMarginPrimeDerivativesEquityBreakdown() { }

    public CrossMarginPrimeDerivativesEquityBreakdown(Builder builder)
    {
      this.CashBalance = builder.cashBalance;
      this.UnrealizedPnl = builder.unrealizedPnl;
      this.RealizedPnl = builder.realizedPnl;
      this.AccruedFundingPnl = builder.accruedFundingPnl;
    }

    public class Builder
    {
#pragma warning disable SA1307, SA1401
      internal string? cashBalance;
      internal string? unrealizedPnl;
      internal string? realizedPnl;
      internal string? accruedFundingPnl;
#pragma warning restore SA1307, SA1401
      public Builder WithCashBalance(string? cashBalance)
      {
        this.cashBalance = cashBalance;
        return this;
      }
      public Builder WithUnrealizedPnl(string? unrealizedPnl)
      {
        this.unrealizedPnl = unrealizedPnl;
        return this;
      }
      public Builder WithRealizedPnl(string? realizedPnl)
      {
        this.realizedPnl = realizedPnl;
        return this;
      }
      public Builder WithAccruedFundingPnl(string? accruedFundingPnl)
      {
        this.accruedFundingPnl = accruedFundingPnl;
        return this;
      }
      public CrossMarginPrimeDerivativesEquityBreakdown Build()
      {
        return new CrossMarginPrimeDerivativesEquityBreakdown(this);
      }
    }
  }

}
