// <auto-generated/>
#nullable enable

/*
 * Copyright 2026-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 *  Do not edit the class manually.
 */


namespace CoinbaseSdk.Prime.Model
{

  public class CrossMarginPrimeXMPosition
  {
    /// <summary>
    /// Position currency
    /// </summary>
    public string? Currency { get; set; }
    /// <summary>
    /// Current market price
    /// </summary>
    public string? MarketPrice { get; set; }
    /// <summary>
    /// Xm spot balance nominal
    /// </summary>
    public string? SpotBalance { get; set; }
    /// <summary>
    /// Xm spot balance notional
    /// </summary>
    public string? SpotBalanceNotional { get; set; }
    /// <summary>
    /// Xm futures balance nominal
    /// </summary>
    public string? FuturesBalance { get; set; }
    /// <summary>
    /// Xm futures balance notional
    /// </summary>
    public string? FuturesBalanceNotional { get; set; }
    /// <summary>
    /// Base margin requirement notional
    /// </summary>
    public string? BaseRequirement { get; set; }
    /// <summary>
    /// Total margin required
    /// </summary>
    public string? TotalPositionMargin { get; set; }
    /// <summary>
    /// Basis offset credit applied to this asset row.
    /// </summary>
    public string? BasisCredit { get; set; }
    /// <summary>
    /// Post-netting USD notional for futures on this asset
    /// </summary>
    public string? FuturesNettedNotional { get; set; }
    /// <summary>
    /// Margin attributed to futures netting for this asset row.
    /// </summary>
    public string? FuturesNettingMargin { get; set; }
    /// <summary>
    /// Per-asset long amount from position_summary.
    /// </summary>
    public string? LongAmount { get; set; }
    /// <summary>
    /// Per-asset short amount from position_summary.
    /// </summary>
    public string? ShortAmount { get; set; }
    /// <summary>
    /// Volatility margin add-on for this asset.
    /// </summary>
    public string? VolatilityAddon { get; set; }
    /// <summary>
    /// Liquidity margin add-on for this asset.
    /// </summary>
    public string? LiquidityAddon { get; set; }
    public CrossMarginPrimeXMPosition() { }

    public CrossMarginPrimeXMPosition(Builder builder)
    {
      this.Currency = builder.currency;
      this.MarketPrice = builder.marketPrice;
      this.SpotBalance = builder.spotBalance;
      this.SpotBalanceNotional = builder.spotBalanceNotional;
      this.FuturesBalance = builder.futuresBalance;
      this.FuturesBalanceNotional = builder.futuresBalanceNotional;
      this.BaseRequirement = builder.baseRequirement;
      this.TotalPositionMargin = builder.totalPositionMargin;
      this.BasisCredit = builder.basisCredit;
      this.FuturesNettedNotional = builder.futuresNettedNotional;
      this.FuturesNettingMargin = builder.futuresNettingMargin;
      this.LongAmount = builder.longAmount;
      this.ShortAmount = builder.shortAmount;
      this.VolatilityAddon = builder.volatilityAddon;
      this.LiquidityAddon = builder.liquidityAddon;
    }

    public class Builder
    {
#pragma warning disable SA1307, SA1401
      internal string? currency;
      internal string? marketPrice;
      internal string? spotBalance;
      internal string? spotBalanceNotional;
      internal string? futuresBalance;
      internal string? futuresBalanceNotional;
      internal string? baseRequirement;
      internal string? totalPositionMargin;
      internal string? basisCredit;
      internal string? futuresNettedNotional;
      internal string? futuresNettingMargin;
      internal string? longAmount;
      internal string? shortAmount;
      internal string? volatilityAddon;
      internal string? liquidityAddon;
#pragma warning restore SA1307, SA1401
      public Builder WithCurrency(string? currency)
      {
        this.currency = currency;
        return this;
      }
      public Builder WithMarketPrice(string? marketPrice)
      {
        this.marketPrice = marketPrice;
        return this;
      }
      public Builder WithSpotBalance(string? spotBalance)
      {
        this.spotBalance = spotBalance;
        return this;
      }
      public Builder WithSpotBalanceNotional(string? spotBalanceNotional)
      {
        this.spotBalanceNotional = spotBalanceNotional;
        return this;
      }
      public Builder WithFuturesBalance(string? futuresBalance)
      {
        this.futuresBalance = futuresBalance;
        return this;
      }
      public Builder WithFuturesBalanceNotional(string? futuresBalanceNotional)
      {
        this.futuresBalanceNotional = futuresBalanceNotional;
        return this;
      }
      public Builder WithBaseRequirement(string? baseRequirement)
      {
        this.baseRequirement = baseRequirement;
        return this;
      }
      public Builder WithTotalPositionMargin(string? totalPositionMargin)
      {
        this.totalPositionMargin = totalPositionMargin;
        return this;
      }
      public Builder WithBasisCredit(string? basisCredit)
      {
        this.basisCredit = basisCredit;
        return this;
      }
      public Builder WithFuturesNettedNotional(string? futuresNettedNotional)
      {
        this.futuresNettedNotional = futuresNettedNotional;
        return this;
      }
      public Builder WithFuturesNettingMargin(string? futuresNettingMargin)
      {
        this.futuresNettingMargin = futuresNettingMargin;
        return this;
      }
      public Builder WithLongAmount(string? longAmount)
      {
        this.longAmount = longAmount;
        return this;
      }
      public Builder WithShortAmount(string? shortAmount)
      {
        this.shortAmount = shortAmount;
        return this;
      }
      public Builder WithVolatilityAddon(string? volatilityAddon)
      {
        this.volatilityAddon = volatilityAddon;
        return this;
      }
      public Builder WithLiquidityAddon(string? liquidityAddon)
      {
        this.liquidityAddon = liquidityAddon;
        return this;
      }
      public CrossMarginPrimeXMPosition Build()
      {
        return new CrossMarginPrimeXMPosition(this);
      }
    }
  }

}
