// <auto-generated/>
#nullable enable

/*
 * Copyright 2026-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 *  Do not edit the class manually.
 */


namespace CoinbaseSdk.Prime.Model
{
  using CoinbaseSdk.Prime.Model.Enums;

  public class CrossMarginOverview
  {
    /// <summary>
    /// - TRADES_AND_WITHDRAWALS: Allowed to trade and withdraw. See XM Margin Methodology for full description of when trading and withdrawals are enabled or disabled.
    /// - TRADES_ONLY: Allowed to trade but not withdraw. See XM Margin Methodology for full description of when trading and withdrawals are enabled or disabled.
    /// - SESSION_LOCKED: Not allowed to trade or withdraw. See XM Margin Methodology for full description of when trading and withdrawals are enabled or disabled.
    /// </summary>
    public XmControlStatus? ControlStatus { get; set; }
    /// <summary>
    /// XMEntityCallStatus summarizes the state of open margin calls or debit calls. When multiple calls exist, the status reflects the highest priority call type.
    /// Priority order (highest to lowest): aged &gt; urgent &gt; standard &gt; debit.
    /// - ENTITY_NO_CALL: There are no margin calls or debit calls.
    /// - ENTITY_OPEN_STANDARD_CALL: There is a standard margin call. There may also be debit calls, but there are no urgent margin calls or expired calls..
    /// - ENTITY_OPEN_URGENT_CALL: There is an urgent margin call. There may also be standard margin calls or debit calls, but there are no expired calls.
    /// - ENTITY_AGED_CALL: At least one open margin call (standard or urgent) or debit call is aged. This will trigger the SESSION_LOCKED control status.
    /// - ENTITY_OPEN_DEBIT_CALL: There is a debit call. There are no standard margin calls, urgent margin calls, or expired calls.
    /// </summary>
    public XmEntityCallStatus? CallStatus { get; set; }
    /// <summary>
    /// - HEALTHY_THRESHOLD: Margin level is healthy.
    /// - DEFICIT_THRESHOLD: Margin level is breaching the deficit threshold (DT) which will result in the issuance of a Margin Call if this is still the case by the scheduled next Margin Call time (as defined in the margin methodology).
    /// - WARNING_THRESHOLD: Margin level is breaching the warning threshold (WT) which will result in the issuance of a Margin Call if this is still the case by the scheduled next Margin Call (as defined in the margin methodology). WT is differentiated from DT in that it means margin health is approaching the UMCT.
    /// - URGENT_MARGIN_CALL_THRESHOLD: Margin level is breaching the UMCT and, as defined in the margin methodology, this will trigger an urgent margin call.
    /// - LIQUIDATION_THRESHOLD: Margin level is breaching the liquidation threshold (LT) and, as defined in the margin methodology, this will trigger the SESSION_LOCKED control status and liquidation may commence.
    /// </summary>
    public XmMarginLevel? MarginLevel { get; set; }
    /// <summary>
    /// XMSummary is the realtime evaluated XM margin model, containing positions and netting info.
    /// </summary>
    public XmSummary? MarginSummary { get; set; }
    /// <summary>
    /// List of active Xm margin calls
    /// </summary>
    public List<XmMarginCall>? ActiveMarginCalls { get; set; }
    /// <summary>
    /// List of active Xm loans
    /// </summary>
    public List<XmLoan>? ActiveLoans { get; set; }
    /// <summary>
    /// ActiveLiquidationSummary provides a summary of the active or most recent XM liquidation.
    /// </summary>
    public ActiveLiquidationSummary? ActiveLiquidation { get; set; }
    public CrossMarginOverview() { }

    public CrossMarginOverview(Builder builder)
    {
      this.ControlStatus = builder.controlStatus;
      this.CallStatus = builder.callStatus;
      this.MarginLevel = builder.marginLevel;
      this.MarginSummary = builder.marginSummary;
      this.ActiveMarginCalls = builder.activeMarginCalls;
      this.ActiveLoans = builder.activeLoans;
      this.ActiveLiquidation = builder.activeLiquidation;
    }

    public class Builder
    {
#pragma warning disable SA1307, SA1401
      internal XmControlStatus? controlStatus;
      internal XmEntityCallStatus? callStatus;
      internal XmMarginLevel? marginLevel;
      internal XmSummary? marginSummary;
      internal List<XmMarginCall>? activeMarginCalls;
      internal List<XmLoan>? activeLoans;
      internal ActiveLiquidationSummary? activeLiquidation;
#pragma warning restore SA1307, SA1401
      public Builder WithControlStatus(XmControlStatus? controlStatus)
      {
        this.controlStatus = controlStatus;
        return this;
      }
      public Builder WithCallStatus(XmEntityCallStatus? callStatus)
      {
        this.callStatus = callStatus;
        return this;
      }
      public Builder WithMarginLevel(XmMarginLevel? marginLevel)
      {
        this.marginLevel = marginLevel;
        return this;
      }
      public Builder WithMarginSummary(XmSummary? marginSummary)
      {
        this.marginSummary = marginSummary;
        return this;
      }
      public Builder WithActiveMarginCalls(List<XmMarginCall>? activeMarginCalls)
      {
        this.activeMarginCalls = activeMarginCalls;
        return this;
      }
      public Builder WithActiveLoans(List<XmLoan>? activeLoans)
      {
        this.activeLoans = activeLoans;
        return this;
      }
      public Builder WithActiveLiquidation(ActiveLiquidationSummary? activeLiquidation)
      {
        this.activeLiquidation = activeLiquidation;
        return this;
      }
      public CrossMarginOverview Build()
      {
        return new CrossMarginOverview(this);
      }
    }
  }

}
