// <auto-generated/>
#nullable enable

/*
 * Copyright 2026-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 *  Do not edit the class manually.
 */


namespace CoinbaseSdk.Prime.Model
{

  public class CrossMarginRiskParameters
  {
    /// <summary>
    /// Asset tier identifier.
    /// </summary>
    public string? AssetTier { get; set; }
    /// <summary>
    /// Base ratio for long positions.
    /// </summary>
    public string? BaseRatioLong { get; set; }
    /// <summary>
    /// Base ratio for short positions.
    /// </summary>
    public string? BaseRatioShort { get; set; }
    /// <summary>
    /// Volatility rate for long positions.
    /// </summary>
    public string? VolatilityRateLong { get; set; }
    /// <summary>
    /// Volatility rate for short positions.
    /// </summary>
    public string? VolatilityRateShort { get; set; }
    /// <summary>
    /// Volatility low threshold.
    /// </summary>
    public string? VolatilityLowThreshold { get; set; }
    /// <summary>
    /// Volatility high threshold.
    /// </summary>
    public string? VolatilityHighThreshold { get; set; }
    /// <summary>
    /// Liquidity A for long positions.
    /// </summary>
    public string? LiquidityALong { get; set; }
    /// <summary>
    /// Liquidity A for short positions.
    /// </summary>
    public string? LiquidityAShort { get; set; }
    /// <summary>
    /// Liquidity B for short positions.
    /// </summary>
    public string? LiquidityBShort { get; set; }
    /// <summary>
    /// Liquidity threshold.
    /// </summary>
    public string? LiquidityThreshold { get; set; }
    /// <summary>
    /// Basis offset credit rate.
    /// </summary>
    public string? BasisOffsetCreditRate { get; set; }
    public CrossMarginRiskParameters() { }

    public CrossMarginRiskParameters(Builder builder)
    {
      this.AssetTier = builder.assetTier;
      this.BaseRatioLong = builder.baseRatioLong;
      this.BaseRatioShort = builder.baseRatioShort;
      this.VolatilityRateLong = builder.volatilityRateLong;
      this.VolatilityRateShort = builder.volatilityRateShort;
      this.VolatilityLowThreshold = builder.volatilityLowThreshold;
      this.VolatilityHighThreshold = builder.volatilityHighThreshold;
      this.LiquidityALong = builder.liquidityALong;
      this.LiquidityAShort = builder.liquidityAShort;
      this.LiquidityBShort = builder.liquidityBShort;
      this.LiquidityThreshold = builder.liquidityThreshold;
      this.BasisOffsetCreditRate = builder.basisOffsetCreditRate;
    }

    public class Builder
    {
#pragma warning disable SA1307, SA1401
      internal string? assetTier;
      internal string? baseRatioLong;
      internal string? baseRatioShort;
      internal string? volatilityRateLong;
      internal string? volatilityRateShort;
      internal string? volatilityLowThreshold;
      internal string? volatilityHighThreshold;
      internal string? liquidityALong;
      internal string? liquidityAShort;
      internal string? liquidityBShort;
      internal string? liquidityThreshold;
      internal string? basisOffsetCreditRate;
#pragma warning restore SA1307, SA1401
      public Builder WithAssetTier(string? assetTier)
      {
        this.assetTier = assetTier;
        return this;
      }
      public Builder WithBaseRatioLong(string? baseRatioLong)
      {
        this.baseRatioLong = baseRatioLong;
        return this;
      }
      public Builder WithBaseRatioShort(string? baseRatioShort)
      {
        this.baseRatioShort = baseRatioShort;
        return this;
      }
      public Builder WithVolatilityRateLong(string? volatilityRateLong)
      {
        this.volatilityRateLong = volatilityRateLong;
        return this;
      }
      public Builder WithVolatilityRateShort(string? volatilityRateShort)
      {
        this.volatilityRateShort = volatilityRateShort;
        return this;
      }
      public Builder WithVolatilityLowThreshold(string? volatilityLowThreshold)
      {
        this.volatilityLowThreshold = volatilityLowThreshold;
        return this;
      }
      public Builder WithVolatilityHighThreshold(string? volatilityHighThreshold)
      {
        this.volatilityHighThreshold = volatilityHighThreshold;
        return this;
      }
      public Builder WithLiquidityALong(string? liquidityALong)
      {
        this.liquidityALong = liquidityALong;
        return this;
      }
      public Builder WithLiquidityAShort(string? liquidityAShort)
      {
        this.liquidityAShort = liquidityAShort;
        return this;
      }
      public Builder WithLiquidityBShort(string? liquidityBShort)
      {
        this.liquidityBShort = liquidityBShort;
        return this;
      }
      public Builder WithLiquidityThreshold(string? liquidityThreshold)
      {
        this.liquidityThreshold = liquidityThreshold;
        return this;
      }
      public Builder WithBasisOffsetCreditRate(string? basisOffsetCreditRate)
      {
        this.basisOffsetCreditRate = basisOffsetCreditRate;
        return this;
      }
      public CrossMarginRiskParameters Build()
      {
        return new CrossMarginRiskParameters(this);
      }
    }
  }

}
