// <auto-generated/>
#nullable enable

/*
 * Copyright 2025-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */


namespace CoinbaseSdk.Prime.Model
{
  using System.Text.Json.Serialization;

  public class DateOfBirth
  {
    [JsonPropertyName("year")]
    public long? Year { get; set; }
    [JsonPropertyName("month")]
    public long? Month { get; set; }
    [JsonPropertyName("day")]
    public long? Day { get; set; }
    public DateOfBirth() { }

    public DateOfBirth(Builder builder)
    {
      this.Year = builder.year;
      this.Month = builder.month;
      this.Day = builder.day;
    }

    public class Builder
    {
#pragma warning disable SA1307, SA1401
      internal long? year;
      internal long? month;
      internal long? day;
#pragma warning restore SA1307, SA1401
      public Builder WithYear(long? year)
      {
        this.year = year;
        return this;
      }
      public Builder WithMonth(long? month)
      {
        this.month = month;
        return this;
      }
      public Builder WithDay(long? day)
      {
        this.day = day;
        return this;
      }
      public DateOfBirth Build()
      {
        return new DateOfBirth(this);
      }
    }
  }

}
