/*
 * Copyright 2025-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

namespace CoinbaseSdk.Prime.Model
{
  using CoinbaseSdk.Prime.Model.Enums;
  using System.Text.Json.Serialization;

  public class DefiBalance
  {
    [JsonPropertyName("network")]
    public string? network { get; set; }

    [JsonPropertyName("protocol")]
    public string? protocol { get; set; }

    [JsonPropertyName("net_usd_value")]
    public string? net_usd_value { get; set; }

    public DefiBalance() { }

    public DefiBalance(Builder builder)
    {
      this.network = builder.network;
      this.protocol = builder.protocol;
      this.net_usd_value = builder.net_usd_value;
    }

    public class Builder
    {
      private string? network;

      private string? protocol;

      private string? net_usd_value;

      public Builder Withnetwork(string? network)
      {
        this.network = network;
        return this;
      }

      public Builder Withprotocol(string? protocol)
      {
        this.protocol = protocol;
        return this;
      }

      public Builder Withnet_usd_value(string? net_usd_value)
      {
        this.net_usd_value = net_usd_value;
        return this;
      }

      public DefiBalance Build()
      {
        return new DefiBalance(this);
      }
    }
  }

}
