// <auto-generated/>
#nullable enable

/*
 * Copyright 2025-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */


namespace CoinbaseSdk.Prime.Model
{
  using System.Text.Json.Serialization;

  public class DefiBalance
  {
    [JsonPropertyName("network")]
    public string? Network { get; set; }
    [JsonPropertyName("protocol")]
    public string? Protocol { get; set; }
    [JsonPropertyName("net_usd_value")]
    public string? NetUsdValue { get; set; }
    public DefiBalance() { }

    public DefiBalance(Builder builder)
    {
      this.Network = builder.network;
      this.Protocol = builder.protocol;
      this.NetUsdValue = builder.netUsdValue;
    }

    public class Builder
    {
#pragma warning disable SA1307, SA1401
      internal string? network;
      internal string? protocol;
      internal string? netUsdValue;
#pragma warning restore SA1307, SA1401
      public Builder WithNetwork(string? network)
      {
        this.network = network;
        return this;
      }
      public Builder WithProtocol(string? protocol)
      {
        this.protocol = protocol;
        return this;
      }
      public Builder WithNetUsdValue(string? netUsdValue)
      {
        this.netUsdValue = netUsdValue;
        return this;
      }
      public DefiBalance Build()
      {
        return new DefiBalance(this);
      }
    }
  }

}
