/*
 * Copyright 2025-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

namespace CoinbaseSdk.Prime.Model
{
  using CoinbaseSdk.Prime.Model.Enums;
  using System.Text.Json.Serialization;

  public class DetailedAddress
  {
    [JsonPropertyName("address_1")]
    public string? address_1 { get; set; }

    [JsonPropertyName("address_2")]
    public string? address_2 { get; set; }

    [JsonPropertyName("address_3")]
    public string? address_3 { get; set; }

    [JsonPropertyName("city")]
    public string? city { get; set; }

    [JsonPropertyName("state")]
    public string? state { get; set; }

    [JsonPropertyName("country_code")]
    public string? country_code { get; set; }

    [JsonPropertyName("postal_code")]
    public string? postal_code { get; set; }

    public DetailedAddress() { }

    public DetailedAddress(Builder builder)
    {
      this.address_1 = builder.address_1;
      this.address_2 = builder.address_2;
      this.address_3 = builder.address_3;
      this.city = builder.city;
      this.state = builder.state;
      this.country_code = builder.country_code;
      this.postal_code = builder.postal_code;
    }

    public static class Builder
    {
      private string? address_1;

      private string? address_2;

      private string? address_3;

      private string? city;

      private string? state;

      private string? country_code;

      private string? postal_code;

      public Builder address_1(string? address_1)
      {
        this.address_1 = address_1;
        return this;
      }

      public Builder address_2(string? address_2)
      {
        this.address_2 = address_2;
        return this;
      }

      public Builder address_3(string? address_3)
      {
        this.address_3 = address_3;
        return this;
      }

      public Builder city(string? city)
      {
        this.city = city;
        return this;
      }

      public Builder state(string? state)
      {
        this.state = state;
        return this;
      }

      public Builder country_code(string? country_code)
      {
        this.country_code = country_code;
        return this;
      }

      public Builder postal_code(string? postal_code)
      {
        this.postal_code = postal_code;
        return this;
      }

      public DetailedAddress Build()
      {
        return new DetailedAddress(this);
      }
    }
  }

}
