// <auto-generated/>
#nullable enable

/*
 * Copyright 2025-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */


namespace CoinbaseSdk.Prime.Model
{
  using System.Text.Json.Serialization;

  public class DisplayUser
  {
    /// <summary>
    /// User UUID
    /// </summary>
    [JsonPropertyName("id")]
    public string Id { get; set; } = default!;
    /// <summary>
    /// User full name
    /// </summary>
    [JsonPropertyName("name")]
    public string Name { get; set; } = default!;
    /// <summary>
    /// User avatar URL
    /// </summary>
    [JsonPropertyName("avatar_url")]
    public string AvatarUrl { get; set; } = default!;
    public DisplayUser() { }

    public DisplayUser(Builder builder)
    {
      this.Id = builder.id;
      this.Name = builder.name;
      this.AvatarUrl = builder.avatarUrl;
    }

    public class Builder
    {
#pragma warning disable SA1307, SA1401
      internal string id = default!;
      internal string name = default!;
      internal string avatarUrl = default!;
#pragma warning restore SA1307, SA1401
      public Builder WithId(string id)
      {
        this.id = id;
        return this;
      }
      public Builder WithName(string name)
      {
        this.name = name;
        return this;
      }
      public Builder WithAvatarUrl(string avatarUrl)
      {
        this.avatarUrl = avatarUrl;
        return this;
      }
      public DisplayUser Build()
      {
        return new DisplayUser(this);
      }
    }
  }

}
