/*
 * Copyright 2025-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

namespace CoinbaseSdk.Prime.Model
{
  using CoinbaseSdk.Prime.Model.Enums;
  using System.Text.Json.Serialization;

  public class DisplayUser
  {
    /// <summary>
    /// User UUID
    /// </summary>
    [JsonPropertyName("id")]
    public string id { get; set; }

    /// <summary>
    /// User full name
    /// </summary>
    [JsonPropertyName("name")]
    public string name { get; set; }

    /// <summary>
    /// User avatar URL
    /// </summary>
    [JsonPropertyName("avatar_url")]
    public string avatar_url { get; set; }

    public DisplayUser() { }

    public DisplayUser(Builder builder)
    {
      this.id = builder.id;
      this.name = builder.name;
      this.avatar_url = builder.avatar_url;
    }

    public class Builder
    {
      private string id;

      private string name;

      private string avatar_url;

      public Builder Withid(string id)
      {
        this.id = id;
        return this;
      }

      public Builder Withname(string name)
      {
        this.name = name;
        return this;
      }

      public Builder Withavatar_url(string avatar_url)
      {
        this.avatar_url = avatar_url;
        return this;
      }

      public DisplayUser Build()
      {
        return new DisplayUser(this);
      }
    }
  }

}
