// <auto-generated/>
#nullable enable

/*
 * Copyright 2025-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */


namespace CoinbaseSdk.Prime.Model
{
  using System.Text.Json.Serialization;

  public class EntityBalance
  {
    /// <summary>
    /// The display symbol for the asset
    /// </summary>
    [JsonPropertyName("symbol")]
    public string? Symbol { get; set; }
    /// <summary>
    /// The long balance
    /// </summary>
    [JsonPropertyName("long_amount")]
    public string? LongAmount { get; set; }
    /// <summary>
    /// The long balance in notional value
    /// </summary>
    [JsonPropertyName("long_notional")]
    public string? LongNotional { get; set; }
    /// <summary>
    /// The short balance
    /// </summary>
    [JsonPropertyName("short_amount")]
    public string? ShortAmount { get; set; }
    /// <summary>
    /// The short balance in notional value
    /// </summary>
    [JsonPropertyName("short_notional")]
    public string? ShortNotional { get; set; }
    public EntityBalance() { }

    public EntityBalance(Builder builder)
    {
      this.Symbol = builder.symbol;
      this.LongAmount = builder.longAmount;
      this.LongNotional = builder.longNotional;
      this.ShortAmount = builder.shortAmount;
      this.ShortNotional = builder.shortNotional;
    }

    public class Builder
    {
#pragma warning disable SA1307, SA1401
      internal string? symbol;
      internal string? longAmount;
      internal string? longNotional;
      internal string? shortAmount;
      internal string? shortNotional;
#pragma warning restore SA1307, SA1401
      public Builder WithSymbol(string? symbol)
      {
        this.symbol = symbol;
        return this;
      }
      public Builder WithLongAmount(string? longAmount)
      {
        this.longAmount = longAmount;
        return this;
      }
      public Builder WithLongNotional(string? longNotional)
      {
        this.longNotional = longNotional;
        return this;
      }
      public Builder WithShortAmount(string? shortAmount)
      {
        this.shortAmount = shortAmount;
        return this;
      }
      public Builder WithShortNotional(string? shortNotional)
      {
        this.shortNotional = shortNotional;
        return this;
      }
      public EntityBalance Build()
      {
        return new EntityBalance(this);
      }
    }
  }

}
