// <auto-generated/>
#nullable enable

/*
 * Copyright 2025-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */


namespace CoinbaseSdk.Prime.Model
{
  using System.Text.Json.Serialization;

  public class EstimatedNetworkFees
  {
    /// <summary>
    /// Estimated lower bound for networks fees (in whole units)
    /// </summary>
    [JsonPropertyName("lower_bound")]
    public string? LowerBound { get; set; }
    /// <summary>
    /// Estimated upper bound for network fees (in whole units)
    /// </summary>
    [JsonPropertyName("upper_bound")]
    public string? UpperBound { get; set; }
    public EstimatedNetworkFees() { }

    public EstimatedNetworkFees(Builder builder)
    {
      this.LowerBound = builder.lowerBound;
      this.UpperBound = builder.upperBound;
    }

    public class Builder
    {
#pragma warning disable SA1307, SA1401
      internal string? lowerBound;
      internal string? upperBound;
#pragma warning restore SA1307, SA1401
      public Builder WithLowerBound(string? lowerBound)
      {
        this.lowerBound = lowerBound;
        return this;
      }
      public Builder WithUpperBound(string? upperBound)
      {
        this.upperBound = upperBound;
        return this;
      }
      public EstimatedNetworkFees Build()
      {
        return new EstimatedNetworkFees(this);
      }
    }
  }

}
