/*
 * Copyright 2025-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

namespace CoinbaseSdk.Prime.Model
{
  using CoinbaseSdk.Prime.Model.Enums;
  using System.Text.Json.Serialization;

  public class ExistingLocate
  {
    /// <summary>
    /// The locate ID
    /// </summary>
    [JsonPropertyName("locate_id")]
    public string? locate_id { get; set; }

    /// <summary>
    /// The unique ID of the entity
    /// </summary>
    [JsonPropertyName("entity_id")]
    public string? entity_id { get; set; }

    /// <summary>
    /// The unique ID of the portfolio
    /// </summary>
    [JsonPropertyName("portfolio_id")]
    public string? portfolio_id { get; set; }

    /// <summary>
    /// The currency symbol
    /// </summary>
    [JsonPropertyName("symbol")]
    public string? symbol { get; set; }

    /// <summary>
    /// The requested locate amount
    /// </summary>
    [JsonPropertyName("requested_amount")]
    public string? requested_amount { get; set; }

    /// <summary>
    /// The interest rate of PM loan
    /// </summary>
    [JsonPropertyName("interest_rate")]
    public string? interest_rate { get; set; }

    /// <summary>
    /// The locate status
    /// </summary>
    [JsonPropertyName("status")]
    public string? status { get; set; }

    /// <summary>
    /// The approved locate amount
    /// </summary>
    [JsonPropertyName("approved_amount")]
    public string? approved_amount { get; set; }

    /// <summary>
    /// Deprecated: Use locate_date instead
    /// </summary>
    [JsonPropertyName("conversion_date")]
    public string? conversion_date { get; set; }

    /// <summary>
    /// The date when the locate was submitted in RFC3339 format
    /// </summary>
    [JsonPropertyName("created_at")]
    public string? created_at { get; set; }

    /// <summary>
    /// The locate date from the CreateNewLocatesRequest in RFC3339 format
    /// </summary>
    [JsonPropertyName("locate_date")]
    public string? locate_date { get; set; }

    public ExistingLocate() { }

    public ExistingLocate(Builder builder)
    {
      this.locate_id = builder.locate_id;
      this.entity_id = builder.entity_id;
      this.portfolio_id = builder.portfolio_id;
      this.symbol = builder.symbol;
      this.requested_amount = builder.requested_amount;
      this.interest_rate = builder.interest_rate;
      this.status = builder.status;
      this.approved_amount = builder.approved_amount;
      this.conversion_date = builder.conversion_date;
      this.created_at = builder.created_at;
      this.locate_date = builder.locate_date;
    }

    public static class Builder
    {
      private string? locate_id;

      private string? entity_id;

      private string? portfolio_id;

      private string? symbol;

      private string? requested_amount;

      private string? interest_rate;

      private string? status;

      private string? approved_amount;

      private string? conversion_date;

      private string? created_at;

      private string? locate_date;

      public Builder locate_id(string? locate_id)
      {
        this.locate_id = locate_id;
        return this;
      }

      public Builder entity_id(string? entity_id)
      {
        this.entity_id = entity_id;
        return this;
      }

      public Builder portfolio_id(string? portfolio_id)
      {
        this.portfolio_id = portfolio_id;
        return this;
      }

      public Builder symbol(string? symbol)
      {
        this.symbol = symbol;
        return this;
      }

      public Builder requested_amount(string? requested_amount)
      {
        this.requested_amount = requested_amount;
        return this;
      }

      public Builder interest_rate(string? interest_rate)
      {
        this.interest_rate = interest_rate;
        return this;
      }

      public Builder status(string? status)
      {
        this.status = status;
        return this;
      }

      public Builder approved_amount(string? approved_amount)
      {
        this.approved_amount = approved_amount;
        return this;
      }

      public Builder conversion_date(string? conversion_date)
      {
        this.conversion_date = conversion_date;
        return this;
      }

      public Builder created_at(string? created_at)
      {
        this.created_at = created_at;
        return this;
      }

      public Builder locate_date(string? locate_date)
      {
        this.locate_date = locate_date;
        return this;
      }

      public ExistingLocate Build()
      {
        return new ExistingLocate(this);
      }
    }
  }

}
