// <auto-generated/>
#nullable enable

/*
 * Copyright 2025-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */


namespace CoinbaseSdk.Prime.Model
{
  using System.Text.Json.Serialization;
  using CoinbaseSdk.Prime.Model.Enums;

  public class FcmMarginCall
  {
    [JsonPropertyName("type")]
    public FcmMarginCallType? Type { get; set; }
    [JsonPropertyName("state")]
    public FcmMarginCallState? State { get; set; }
    /// <summary>
    /// Initial margin call amount to settle
    /// </summary>
    [JsonPropertyName("initial_amount")]
    public string? InitialAmount { get; set; }
    /// <summary>
    /// Remaining margin call amount to settle
    /// </summary>
    [JsonPropertyName("remaining_amount")]
    public string? RemainingAmount { get; set; }
    /// <summary>
    /// Business date when the margin call was opened
    /// </summary>
    [JsonPropertyName("business_date")]
    public DateTime? BusinessDate { get; set; }
    /// <summary>
    /// The deadline by which the margin call must be satisfied
    /// </summary>
    [JsonPropertyName("cure_deadline")]
    public DateTime? CureDeadline { get; set; }
    public FcmMarginCall() { }

    public FcmMarginCall(Builder builder)
    {
      this.Type = builder.type;
      this.State = builder.state;
      this.InitialAmount = builder.initialAmount;
      this.RemainingAmount = builder.remainingAmount;
      this.BusinessDate = builder.businessDate;
      this.CureDeadline = builder.cureDeadline;
    }

    public class Builder
    {
#pragma warning disable SA1307, SA1401
      internal FcmMarginCallType? type;
      internal FcmMarginCallState? state;
      internal string? initialAmount;
      internal string? remainingAmount;
      internal DateTime? businessDate;
      internal DateTime? cureDeadline;
#pragma warning restore SA1307, SA1401
      public Builder WithType(FcmMarginCallType? type)
      {
        this.type = type;
        return this;
      }
      public Builder WithState(FcmMarginCallState? state)
      {
        this.state = state;
        return this;
      }
      public Builder WithInitialAmount(string? initialAmount)
      {
        this.initialAmount = initialAmount;
        return this;
      }
      public Builder WithRemainingAmount(string? remainingAmount)
      {
        this.remainingAmount = remainingAmount;
        return this;
      }
      public Builder WithBusinessDate(DateTime? businessDate)
      {
        this.businessDate = businessDate;
        return this;
      }
      public Builder WithCureDeadline(DateTime? cureDeadline)
      {
        this.cureDeadline = cureDeadline;
        return this;
      }
      public FcmMarginCall Build()
      {
        return new FcmMarginCall(this);
      }
    }
  }

}
