// <auto-generated/>
#nullable enable

/*
 * Copyright 2025-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */


namespace CoinbaseSdk.Prime.Model
{
  using System.Text.Json.Serialization;

  public class FcmScheduledMaintenance
  {
    /// <summary>
    /// Maintenance window start time
    /// </summary>
    [JsonPropertyName("start_time")]
    public DateTime? StartTime { get; set; }
    /// <summary>
    /// Maintenance window end time
    /// </summary>
    [JsonPropertyName("end_time")]
    public DateTime? EndTime { get; set; }
    public FcmScheduledMaintenance() { }

    public FcmScheduledMaintenance(Builder builder)
    {
      this.StartTime = builder.startTime;
      this.EndTime = builder.endTime;
    }

    public class Builder
    {
#pragma warning disable SA1307, SA1401
      internal DateTime? startTime;
      internal DateTime? endTime;
#pragma warning restore SA1307, SA1401
      public Builder WithStartTime(DateTime? startTime)
      {
        this.startTime = startTime;
        return this;
      }
      public Builder WithEndTime(DateTime? endTime)
      {
        this.endTime = endTime;
        return this;
      }
      public FcmScheduledMaintenance Build()
      {
        return new FcmScheduledMaintenance(this);
      }
    }
  }

}
