// <auto-generated/>
#nullable enable

/*
 * Copyright 2025-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */


namespace CoinbaseSdk.Prime.Model
{
  using System.Text.Json.Serialization;
  using CoinbaseSdk.Prime.Model.Enums;

  public class Fill
  {
    /// <summary>
    /// The unique ID of the fill
    /// </summary>
    [JsonPropertyName("id")]
    public string? Id { get; set; }
    /// <summary>
    /// The order ID of the fill
    /// </summary>
    [JsonPropertyName("order_id")]
    public string? OrderId { get; set; }
    /// <summary>
    /// The product ID of the fill
    /// </summary>
    [JsonPropertyName("product_id")]
    public string? ProductId { get; set; }
    /// <summary>
    /// The client product ID of the fill indictating the settlment currency
    /// </summary>
    [JsonPropertyName("client_product_id")]
    public string? ClientProductId { get; set; }
    [JsonPropertyName("side")]
    public OrderSide? Side { get; set; }
    /// <summary>
    /// Filled size (in base asset units)
    /// </summary>
    [JsonPropertyName("filled_quantity")]
    public string? FilledQuantity { get; set; }
    /// <summary>
    /// Filled value (in quote asset units)
    /// </summary>
    [JsonPropertyName("filled_value")]
    public string? FilledValue { get; set; }
    /// <summary>
    /// The price of the fill
    /// </summary>
    [JsonPropertyName("price")]
    public string? Price { get; set; }
    /// <summary>
    /// The date and time of the fill
    /// </summary>
    [JsonPropertyName("time")]
    public DateTime? Time { get; set; }
    /// <summary>
    /// The commission incurred for the fill
    /// </summary>
    [JsonPropertyName("commission")]
    public string? Commission { get; set; }
    /// <summary>
    /// The name of the venue
    /// </summary>
    [JsonPropertyName("venue")]
    public string? Venue { get; set; }
    /// <summary>
    /// The venue fees incurred for the fill
    /// </summary>
    [JsonPropertyName("venue_fees")]
    public string? VenueFees { get; set; }
    /// <summary>
    /// The CES commission incurred for the fill
    /// </summary>
    [JsonPropertyName("ces_commission")]
    public string? CesCommission { get; set; }
    public Fill() { }

    public Fill(Builder builder)
    {
      this.Id = builder.id;
      this.OrderId = builder.orderId;
      this.ProductId = builder.productId;
      this.ClientProductId = builder.clientProductId;
      this.Side = builder.side;
      this.FilledQuantity = builder.filledQuantity;
      this.FilledValue = builder.filledValue;
      this.Price = builder.price;
      this.Time = builder.time;
      this.Commission = builder.commission;
      this.Venue = builder.venue;
      this.VenueFees = builder.venueFees;
      this.CesCommission = builder.cesCommission;
    }

    public class Builder
    {
#pragma warning disable SA1307, SA1401
      internal string? id;
      internal string? orderId;
      internal string? productId;
      internal string? clientProductId;
      internal OrderSide? side;
      internal string? filledQuantity;
      internal string? filledValue;
      internal string? price;
      internal DateTime? time;
      internal string? commission;
      internal string? venue;
      internal string? venueFees;
      internal string? cesCommission;
#pragma warning restore SA1307, SA1401
      public Builder WithId(string? id)
      {
        this.id = id;
        return this;
      }
      public Builder WithOrderId(string? orderId)
      {
        this.orderId = orderId;
        return this;
      }
      public Builder WithProductId(string? productId)
      {
        this.productId = productId;
        return this;
      }
      public Builder WithClientProductId(string? clientProductId)
      {
        this.clientProductId = clientProductId;
        return this;
      }
      public Builder WithSide(OrderSide? side)
      {
        this.side = side;
        return this;
      }
      public Builder WithFilledQuantity(string? filledQuantity)
      {
        this.filledQuantity = filledQuantity;
        return this;
      }
      public Builder WithFilledValue(string? filledValue)
      {
        this.filledValue = filledValue;
        return this;
      }
      public Builder WithPrice(string? price)
      {
        this.price = price;
        return this;
      }
      public Builder WithTime(DateTime? time)
      {
        this.time = time;
        return this;
      }
      public Builder WithCommission(string? commission)
      {
        this.commission = commission;
        return this;
      }
      public Builder WithVenue(string? venue)
      {
        this.venue = venue;
        return this;
      }
      public Builder WithVenueFees(string? venueFees)
      {
        this.venueFees = venueFees;
        return this;
      }
      public Builder WithCesCommission(string? cesCommission)
      {
        this.cesCommission = cesCommission;
        return this;
      }
      public Fill Build()
      {
        return new Fill(this);
      }
    }
  }

}
