/*
 * Copyright 2025-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

namespace CoinbaseSdk.Prime.Model
{
  using CoinbaseSdk.Prime.Model.Enums;
  using System.Text.Json.Serialization;

  public class Fill
  {
    /// <summary>
    /// The unique ID of the fill
    /// </summary>
    [JsonPropertyName("id")]
    public string? id { get; set; }

    /// <summary>
    /// The order ID of the fill
    /// </summary>
    [JsonPropertyName("order_id")]
    public string? order_id { get; set; }

    /// <summary>
    /// The product ID of the fill
    /// </summary>
    [JsonPropertyName("product_id")]
    public string? product_id { get; set; }

    /// <summary>
    /// The client product ID of the fill indictating the settlment currency
    /// </summary>
    [JsonPropertyName("client_product_id")]
    public string? client_product_id { get; set; }

    [JsonPropertyName("side")]
    public OrderSide? side { get; set; }

    /// <summary>
    /// Filled size (in base asset units)
    /// </summary>
    [JsonPropertyName("filled_quantity")]
    public string? filled_quantity { get; set; }

    /// <summary>
    /// Filled value (in quote asset units)
    /// </summary>
    [JsonPropertyName("filled_value")]
    public string? filled_value { get; set; }

    /// <summary>
    /// The price of the fill
    /// </summary>
    [JsonPropertyName("price")]
    public string? price { get; set; }

    /// <summary>
    /// The date and time of the fill
    /// </summary>
    [JsonPropertyName("time")]
    public DateTime? time { get; set; }

    /// <summary>
    /// The commission incurred for the fill
    /// </summary>
    [JsonPropertyName("commission")]
    public string? commission { get; set; }

    /// <summary>
    /// The name of the venue
    /// </summary>
    [JsonPropertyName("venue")]
    public string? venue { get; set; }

    /// <summary>
    /// The venue fees incurred for the fill
    /// </summary>
    [JsonPropertyName("venue_fees")]
    public string? venue_fees { get; set; }

    /// <summary>
    /// The CES commission incurred for the fill
    /// </summary>
    [JsonPropertyName("ces_commission")]
    public string? ces_commission { get; set; }

    public Fill() { }

    public Fill(Builder builder)
    {
      this.id = builder.id;
      this.order_id = builder.order_id;
      this.product_id = builder.product_id;
      this.client_product_id = builder.client_product_id;
      this.side = builder.side;
      this.filled_quantity = builder.filled_quantity;
      this.filled_value = builder.filled_value;
      this.price = builder.price;
      this.time = builder.time;
      this.commission = builder.commission;
      this.venue = builder.venue;
      this.venue_fees = builder.venue_fees;
      this.ces_commission = builder.ces_commission;
    }

    public class Builder
    {
      private string? id;

      private string? order_id;

      private string? product_id;

      private string? client_product_id;

      private OrderSide? side;

      private string? filled_quantity;

      private string? filled_value;

      private string? price;

      private DateTime? time;

      private string? commission;

      private string? venue;

      private string? venue_fees;

      private string? ces_commission;

      public Builder Withid(string? id)
      {
        this.id = id;
        return this;
      }

      public Builder Withorder_id(string? order_id)
      {
        this.order_id = order_id;
        return this;
      }

      public Builder Withproduct_id(string? product_id)
      {
        this.product_id = product_id;
        return this;
      }

      public Builder Withclient_product_id(string? client_product_id)
      {
        this.client_product_id = client_product_id;
        return this;
      }

      public Builder Withside(OrderSide? side)
      {
        this.side = side;
        return this;
      }

      public Builder Withfilled_quantity(string? filled_quantity)
      {
        this.filled_quantity = filled_quantity;
        return this;
      }

      public Builder Withfilled_value(string? filled_value)
      {
        this.filled_value = filled_value;
        return this;
      }

      public Builder Withprice(string? price)
      {
        this.price = price;
        return this;
      }

      public Builder Withtime(DateTime? time)
      {
        this.time = time;
        return this;
      }

      public Builder Withcommission(string? commission)
      {
        this.commission = commission;
        return this;
      }

      public Builder Withvenue(string? venue)
      {
        this.venue = venue;
        return this;
      }

      public Builder Withvenue_fees(string? venue_fees)
      {
        this.venue_fees = venue_fees;
        return this;
      }

      public Builder Withces_commission(string? ces_commission)
      {
        this.ces_commission = ces_commission;
        return this;
      }

      public Fill Build()
      {
        return new Fill(this);
      }
    }
  }

}
