// <auto-generated/>
#nullable enable

/*
 * Copyright 2026-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 *  Do not edit the class manually.
 */


namespace CoinbaseSdk.Prime.Model
{
  using CoinbaseSdk.Prime.Model.Enums;

  public class InvoiceItem
  {
    public string? Description { get; set; }
    public string? CurrencySymbol { get; set; }
    public InvoiceType? InvoiceType { get; set; }
    public double? Rate { get; set; }
    public double? Quantity { get; set; }
    public double? Price { get; set; }
    public double? AverageAuc { get; set; }
    public double? Total { get; set; }
    public InvoiceItem() { }

    public InvoiceItem(Builder builder)
    {
      this.Description = builder.description;
      this.CurrencySymbol = builder.currencySymbol;
      this.InvoiceType = builder.invoiceType;
      this.Rate = builder.rate;
      this.Quantity = builder.quantity;
      this.Price = builder.price;
      this.AverageAuc = builder.averageAuc;
      this.Total = builder.total;
    }

    public class Builder
    {
#pragma warning disable SA1307, SA1401
      internal string? description;
      internal string? currencySymbol;
      internal InvoiceType? invoiceType;
      internal double? rate;
      internal double? quantity;
      internal double? price;
      internal double? averageAuc;
      internal double? total;
#pragma warning restore SA1307, SA1401
      public Builder WithDescription(string? description)
      {
        this.description = description;
        return this;
      }
      public Builder WithCurrencySymbol(string? currencySymbol)
      {
        this.currencySymbol = currencySymbol;
        return this;
      }
      public Builder WithInvoiceType(InvoiceType? invoiceType)
      {
        this.invoiceType = invoiceType;
        return this;
      }
      public Builder WithRate(double? rate)
      {
        this.rate = rate;
        return this;
      }
      public Builder WithQuantity(double? quantity)
      {
        this.quantity = quantity;
        return this;
      }
      public Builder WithPrice(double? price)
      {
        this.price = price;
        return this;
      }
      public Builder WithAverageAuc(double? averageAuc)
      {
        this.averageAuc = averageAuc;
        return this;
      }
      public Builder WithTotal(double? total)
      {
        this.total = total;
        return this;
      }
      public InvoiceItem Build()
      {
        return new InvoiceItem(this);
      }
    }
  }

}
