/*
 * Copyright 2025-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

namespace CoinbaseSdk.Prime.Model
{
  using CoinbaseSdk.Prime.Model.Enums;
  using System.Text.Json.Serialization;

  public class LimitOrderEdit
  {
    [JsonPropertyName("price")]
    public string? price { get; set; }

    [JsonPropertyName("size")]
    public string? size { get; set; }

    [JsonPropertyName("display_size")]
    public string? display_size { get; set; }

    [JsonPropertyName("stop_price")]
    public string? stop_price { get; set; }

    [JsonPropertyName("stop_limit_price")]
    public string? stop_limit_price { get; set; }

    [JsonPropertyName("end_time")]
    public DateTime? end_time { get; set; }

    [JsonPropertyName("accept_time")]
    public DateTime? accept_time { get; set; }

    [JsonPropertyName("client_order_id")]
    public string? client_order_id { get; set; }

    public LimitOrderEdit() { }

    public LimitOrderEdit(Builder builder)
    {
      this.price = builder.price;
      this.size = builder.size;
      this.display_size = builder.display_size;
      this.stop_price = builder.stop_price;
      this.stop_limit_price = builder.stop_limit_price;
      this.end_time = builder.end_time;
      this.accept_time = builder.accept_time;
      this.client_order_id = builder.client_order_id;
    }

    public class Builder
    {
      private string? price;

      private string? size;

      private string? display_size;

      private string? stop_price;

      private string? stop_limit_price;

      private DateTime? end_time;

      private DateTime? accept_time;

      private string? client_order_id;

      public Builder Withprice(string? price)
      {
        this.price = price;
        return this;
      }

      public Builder Withsize(string? size)
      {
        this.size = size;
        return this;
      }

      public Builder Withdisplay_size(string? display_size)
      {
        this.display_size = display_size;
        return this;
      }

      public Builder Withstop_price(string? stop_price)
      {
        this.stop_price = stop_price;
        return this;
      }

      public Builder Withstop_limit_price(string? stop_limit_price)
      {
        this.stop_limit_price = stop_limit_price;
        return this;
      }

      public Builder Withend_time(DateTime? end_time)
      {
        this.end_time = end_time;
        return this;
      }

      public Builder Withaccept_time(DateTime? accept_time)
      {
        this.accept_time = accept_time;
        return this;
      }

      public Builder Withclient_order_id(string? client_order_id)
      {
        this.client_order_id = client_order_id;
        return this;
      }

      public LimitOrderEdit Build()
      {
        return new LimitOrderEdit(this);
      }
    }
  }

}
