// <auto-generated/>
#nullable enable

/*
 * Copyright 2025-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */


namespace CoinbaseSdk.Prime.Model
{
  using System.Text.Json.Serialization;

  public class LimitOrderEdit
  {
    [JsonPropertyName("price")]
    public string? Price { get; set; }
    [JsonPropertyName("size")]
    public string? Size { get; set; }
    [JsonPropertyName("display_size")]
    public string? DisplaySize { get; set; }
    [JsonPropertyName("stop_price")]
    public string? StopPrice { get; set; }
    [JsonPropertyName("stop_limit_price")]
    public string? StopLimitPrice { get; set; }
    [JsonPropertyName("end_time")]
    public DateTime? EndTime { get; set; }
    [JsonPropertyName("accept_time")]
    public DateTime? AcceptTime { get; set; }
    [JsonPropertyName("client_order_id")]
    public string? ClientOrderId { get; set; }
    public LimitOrderEdit() { }

    public LimitOrderEdit(Builder builder)
    {
      this.Price = builder.price;
      this.Size = builder.size;
      this.DisplaySize = builder.displaySize;
      this.StopPrice = builder.stopPrice;
      this.StopLimitPrice = builder.stopLimitPrice;
      this.EndTime = builder.endTime;
      this.AcceptTime = builder.acceptTime;
      this.ClientOrderId = builder.clientOrderId;
    }

    public class Builder
    {
#pragma warning disable SA1307, SA1401
      internal string? price;
      internal string? size;
      internal string? displaySize;
      internal string? stopPrice;
      internal string? stopLimitPrice;
      internal DateTime? endTime;
      internal DateTime? acceptTime;
      internal string? clientOrderId;
#pragma warning restore SA1307, SA1401
      public Builder WithPrice(string? price)
      {
        this.price = price;
        return this;
      }
      public Builder WithSize(string? size)
      {
        this.size = size;
        return this;
      }
      public Builder WithDisplaySize(string? displaySize)
      {
        this.displaySize = displaySize;
        return this;
      }
      public Builder WithStopPrice(string? stopPrice)
      {
        this.stopPrice = stopPrice;
        return this;
      }
      public Builder WithStopLimitPrice(string? stopLimitPrice)
      {
        this.stopLimitPrice = stopLimitPrice;
        return this;
      }
      public Builder WithEndTime(DateTime? endTime)
      {
        this.endTime = endTime;
        return this;
      }
      public Builder WithAcceptTime(DateTime? acceptTime)
      {
        this.acceptTime = acceptTime;
        return this;
      }
      public Builder WithClientOrderId(string? clientOrderId)
      {
        this.clientOrderId = clientOrderId;
        return this;
      }
      public LimitOrderEdit Build()
      {
        return new LimitOrderEdit(this);
      }
    }
  }

}
