/*
 * Copyright 2025-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

namespace CoinbaseSdk.Prime.Model
{
  using CoinbaseSdk.Prime.Model.Enums;
  using CoinbaseSdk.Prime.Model.MarginCallRecord;
  using CoinbaseSdk.Prime.Model.MarginSummary;
  using System.Text.Json.Serialization;

  public class MarginInformation
  {
    /// <summary>
    /// The current margin call records
    /// </summary>
    [JsonPropertyName("margin_call_records")]
    public List<MarginCallRecord>? margin_call_records { get; set; }

    [JsonPropertyName("margin_summary")]
    public MarginSummary? margin_summary { get; set; }

    public MarginInformation() { }

    public MarginInformation(Builder builder)
    {
      this.margin_call_records = builder.margin_call_records;
      this.margin_summary = builder.margin_summary;
    }

    public class Builder
    {
      private List<MarginCallRecord>? margin_call_records;

      private MarginSummary? margin_summary;

      public Builder Withmargin_call_records(List<MarginCallRecord>? margin_call_records)
      {
        this.margin_call_records = margin_call_records;
        return this;
      }

      public Builder Withmargin_summary(MarginSummary? margin_summary)
      {
        this.margin_summary = margin_summary;
        return this;
      }

      public MarginInformation Build()
      {
        return new MarginInformation(this);
      }
    }
  }

}
