/*
 * Copyright 2025-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

namespace CoinbaseSdk.Prime.Model
{
  using CoinbaseSdk.Prime.Model.Enums;
  using System.Text.Json.Serialization;

  public class MarginCallRecord
  {
    /// <summary>
    /// The unique ID of the margin call
    /// </summary>
    [JsonPropertyName("margin_call_id")]
    public string? margin_call_id { get; set; }

    /// <summary>
    /// The initial margin call amount in notional value
    /// </summary>
    [JsonPropertyName("initial_notional_amount")]
    public string? initial_notional_amount { get; set; }

    /// <summary>
    /// The outstanding margin call amount in notional value
    /// </summary>
    [JsonPropertyName("outstanding_notional_amount")]
    public string? outstanding_notional_amount { get; set; }

    /// <summary>
    /// The time the margin call is created in RFC3330 format
    /// </summary>
    [JsonPropertyName("created_at")]
    public string? created_at { get; set; }

    /// <summary>
    /// The time the margin call is due in RFC3339 format
    /// </summary>
    [JsonPropertyName("due_at")]
    public string? due_at { get; set; }

    public MarginCallRecord() { }

    public MarginCallRecord(Builder builder)
    {
      this.margin_call_id = builder.margin_call_id;
      this.initial_notional_amount = builder.initial_notional_amount;
      this.outstanding_notional_amount = builder.outstanding_notional_amount;
      this.created_at = builder.created_at;
      this.due_at = builder.due_at;
    }

    public static class Builder
    {
      private string? margin_call_id;

      private string? initial_notional_amount;

      private string? outstanding_notional_amount;

      private string? created_at;

      private string? due_at;

      public Builder margin_call_id(string? margin_call_id)
      {
        this.margin_call_id = margin_call_id;
        return this;
      }

      public Builder initial_notional_amount(string? initial_notional_amount)
      {
        this.initial_notional_amount = initial_notional_amount;
        return this;
      }

      public Builder outstanding_notional_amount(string? outstanding_notional_amount)
      {
        this.outstanding_notional_amount = outstanding_notional_amount;
        return this;
      }

      public Builder created_at(string? created_at)
      {
        this.created_at = created_at;
        return this;
      }

      public Builder due_at(string? due_at)
      {
        this.due_at = due_at;
        return this;
      }

      public MarginCallRecord Build()
      {
        return new MarginCallRecord(this);
      }
    }
  }

}
