/*
 * Copyright 2025-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

namespace CoinbaseSdk.Prime.Model
{
  using CoinbaseSdk.Prime.Model.Enums;
  using CoinbaseSdk.Prime.Model.AssetBalance;
  using CoinbaseSdk.Prime.Model.LoanInfo;
  using CoinbaseSdk.Prime.Model.MarginAddOn;
  using CoinbaseSdk.Prime.Model.MarketRate;
  using CoinbaseSdk.Prime.Model.PMAssetInfo;
  using System.Text.Json.Serialization;

  public class MarginSummary
  {
    /// <summary>
    /// The unique ID of the entity
    /// </summary>
    [JsonPropertyName("entity_id")]
    public string? entity_id { get; set; }

    /// <summary>
    /// The margin equity at the entity level. Margin Equity &#x3D; LMV + SMV + Trading Cash Balance + Short Collateral - Pending Withdrawals
    /// </summary>
    [JsonPropertyName("margin_equity")]
    public string? margin_equity { get; set; }

    /// <summary>
    /// USD notional value of required equity in entity portfolios
    /// </summary>
    [JsonPropertyName("margin_requirement")]
    public string? margin_requirement { get; set; }

    /// <summary>
    /// margin_equity - margin_requirement
    /// </summary>
    [JsonPropertyName("excess_deficit")]
    public string? excess_deficit { get; set; }

    /// <summary>
    /// The raw amount of portfolio margin credit used
    /// </summary>
    [JsonPropertyName("pm_credit_consumed")]
    public string? pm_credit_consumed { get; set; }

    /// <summary>
    /// The maximum trade finance credit limit. This field is deprecated and will be removed in the future.
    /// </summary>
    [JsonPropertyName("tf_credit_limit")]
    public string? tf_credit_limit { get; set; }

    /// <summary>
    /// The amount of trade finance credit used (USD). This field is deprecated and will be removed in the future.
    /// </summary>
    [JsonPropertyName("tf_credit_consumed")]
    public string? tf_credit_consumed { get; set; }

    /// <summary>
    /// TF Asset Adjusted Value (USD). This field is deprecated and will be removed in the future.
    /// </summary>
    [JsonPropertyName("tf_adjusted_asset_value")]
    public string? tf_adjusted_asset_value { get; set; }

    /// <summary>
    /// TF Adjusted Liability Value (USD). This field is deprecated and will be removed in the future.
    /// </summary>
    [JsonPropertyName("tf_adjusted_liability_value")]
    public string? tf_adjusted_liability_value { get; set; }

    /// <summary>
    /// The amount of adjusted credit used. This field is deprecated and will be removed in the future.
    /// </summary>
    [JsonPropertyName("tf_adjusted_credit_consumed")]
    public string? tf_adjusted_credit_consumed { get; set; }

    /// <summary>
    /// The amount of adjusted equity. This field is deprecated and will be removed in the future.
    /// </summary>
    [JsonPropertyName("tf_adjusted_equity")]
    public string? tf_adjusted_equity { get; set; }

    /// <summary>
    /// Whether or not a entity is frozen due to balance outstanding or other reason
    /// </summary>
    [JsonPropertyName("frozen")]
    public bool? frozen { get; set; }

    /// <summary>
    /// The reason why a entity is frozen
    /// </summary>
    [JsonPropertyName("frozen_reason")]
    public string? frozen_reason { get; set; }

    /// <summary>
    /// Whether TF is enabled for the entity. This field is deprecated and will be removed in the future.
    /// </summary>
    [JsonPropertyName("tf_enabled")]
    public bool? tf_enabled { get; set; }

    /// <summary>
    /// Whether PM is enabled for the entity
    /// </summary>
    [JsonPropertyName("pm_enabled")]
    public bool? pm_enabled { get; set; }

    /// <summary>
    /// Market rates for the list of assets
    /// </summary>
    [JsonPropertyName("market_rates")]
    public List<MarketRate>? market_rates { get; set; }

    /// <summary>
    /// Asset Balances across portfolios
    /// </summary>
    [JsonPropertyName("asset_balances")]
    public List<AssetBalance>? asset_balances { get; set; }

    /// <summary>
    /// Trade finance debit loan amounts. This field is deprecated and will be removed in the future.
    /// </summary>
    [JsonPropertyName("tf_loans")]
    public List<LoanInfo>? tf_loans { get; set; }

    /// <summary>
    /// Portfolio Margin debit loan amounts
    /// </summary>
    [JsonPropertyName("pm_loans")]
    public List<LoanInfo>? pm_loans { get; set; }

    /// <summary>
    /// Short collateral amounts
    /// </summary>
    [JsonPropertyName("short_collateral")]
    public List<LoanInfo>? short_collateral { get; set; }

    /// <summary>
    /// Gross market value (GMV) &#x3D; LMV + Abs (SMV)
    /// </summary>
    [JsonPropertyName("gross_market_value")]
    public string? gross_market_value { get; set; }

    /// <summary>
    /// Net Market Value (NMV) &#x3D; LMV + SMV
    /// </summary>
    [JsonPropertyName("net_market_value")]
    public string? net_market_value { get; set; }

    /// <summary>
    /// Long Market Value (LMV) &#x3D; Sum of positive notional for all assets
    /// </summary>
    [JsonPropertyName("long_market_value")]
    public string? long_market_value { get; set; }

    /// <summary>
    /// Non_Marginable LMV: Sum of positive notional for each non-margin eligible coin
    /// </summary>
    [JsonPropertyName("non_marginable_long_market_value")]
    public string? non_marginable_long_market_value { get; set; }

    /// <summary>
    /// Short Market Value (SMV) &#x3D; Sum of negative notional for each margin eligible coin
    /// </summary>
    [JsonPropertyName("short_market_value")]
    public string? short_market_value { get; set; }

    /// <summary>
    /// Gross Leverage &#x3D; GMV / Margin Requirement
    /// </summary>
    [JsonPropertyName("gross_leverage")]
    public string? gross_leverage { get; set; }

    /// <summary>
    /// Net Exposure &#x3D; (LMV + SMV) / GMV
    /// </summary>
    [JsonPropertyName("net_exposure")]
    public string? net_exposure { get; set; }

    [JsonPropertyName("portfolio_stress_triggered")]
    public MarginAddOn? portfolio_stress_triggered { get; set; }

    /// <summary>
    /// PM asset info netted across the entity
    /// </summary>
    [JsonPropertyName("pm_asset_info")]
    public List<PMAssetInfo>? pm_asset_info { get; set; }

    /// <summary>
    /// PM limit that monitors gross notional borrowings (crypto + fiat)
    /// </summary>
    [JsonPropertyName("pm_credit_limit")]
    public string? pm_credit_limit { get; set; }

    /// <summary>
    /// PM limit that monitors excess deficit
    /// </summary>
    [JsonPropertyName("pm_margin_limit")]
    public string? pm_margin_limit { get; set; }

    /// <summary>
    /// The amount of the margin limit that is consumed by the excess deficit
    /// </summary>
    [JsonPropertyName("pm_margin_consumed")]
    public string? pm_margin_consumed { get; set; }

    public MarginSummary() { }

    public MarginSummary(Builder builder)
    {
      this.entity_id = builder.entity_id;
      this.margin_equity = builder.margin_equity;
      this.margin_requirement = builder.margin_requirement;
      this.excess_deficit = builder.excess_deficit;
      this.pm_credit_consumed = builder.pm_credit_consumed;
      this.tf_credit_limit = builder.tf_credit_limit;
      this.tf_credit_consumed = builder.tf_credit_consumed;
      this.tf_adjusted_asset_value = builder.tf_adjusted_asset_value;
      this.tf_adjusted_liability_value = builder.tf_adjusted_liability_value;
      this.tf_adjusted_credit_consumed = builder.tf_adjusted_credit_consumed;
      this.tf_adjusted_equity = builder.tf_adjusted_equity;
      this.frozen = builder.frozen;
      this.frozen_reason = builder.frozen_reason;
      this.tf_enabled = builder.tf_enabled;
      this.pm_enabled = builder.pm_enabled;
      this.market_rates = builder.market_rates;
      this.asset_balances = builder.asset_balances;
      this.tf_loans = builder.tf_loans;
      this.pm_loans = builder.pm_loans;
      this.short_collateral = builder.short_collateral;
      this.gross_market_value = builder.gross_market_value;
      this.net_market_value = builder.net_market_value;
      this.long_market_value = builder.long_market_value;
      this.non_marginable_long_market_value = builder.non_marginable_long_market_value;
      this.short_market_value = builder.short_market_value;
      this.gross_leverage = builder.gross_leverage;
      this.net_exposure = builder.net_exposure;
      this.portfolio_stress_triggered = builder.portfolio_stress_triggered;
      this.pm_asset_info = builder.pm_asset_info;
      this.pm_credit_limit = builder.pm_credit_limit;
      this.pm_margin_limit = builder.pm_margin_limit;
      this.pm_margin_consumed = builder.pm_margin_consumed;
    }

    public class Builder
    {
      private string? entity_id;

      private string? margin_equity;

      private string? margin_requirement;

      private string? excess_deficit;

      private string? pm_credit_consumed;

      private string? tf_credit_limit;

      private string? tf_credit_consumed;

      private string? tf_adjusted_asset_value;

      private string? tf_adjusted_liability_value;

      private string? tf_adjusted_credit_consumed;

      private string? tf_adjusted_equity;

      private bool? frozen;

      private string? frozen_reason;

      private bool? tf_enabled;

      private bool? pm_enabled;

      private List<MarketRate>? market_rates;

      private List<AssetBalance>? asset_balances;

      private List<LoanInfo>? tf_loans;

      private List<LoanInfo>? pm_loans;

      private List<LoanInfo>? short_collateral;

      private string? gross_market_value;

      private string? net_market_value;

      private string? long_market_value;

      private string? non_marginable_long_market_value;

      private string? short_market_value;

      private string? gross_leverage;

      private string? net_exposure;

      private MarginAddOn? portfolio_stress_triggered;

      private List<PMAssetInfo>? pm_asset_info;

      private string? pm_credit_limit;

      private string? pm_margin_limit;

      private string? pm_margin_consumed;

      public Builder Withentity_id(string? entity_id)
      {
        this.entity_id = entity_id;
        return this;
      }

      public Builder Withmargin_equity(string? margin_equity)
      {
        this.margin_equity = margin_equity;
        return this;
      }

      public Builder Withmargin_requirement(string? margin_requirement)
      {
        this.margin_requirement = margin_requirement;
        return this;
      }

      public Builder Withexcess_deficit(string? excess_deficit)
      {
        this.excess_deficit = excess_deficit;
        return this;
      }

      public Builder Withpm_credit_consumed(string? pm_credit_consumed)
      {
        this.pm_credit_consumed = pm_credit_consumed;
        return this;
      }

      public Builder Withtf_credit_limit(string? tf_credit_limit)
      {
        this.tf_credit_limit = tf_credit_limit;
        return this;
      }

      public Builder Withtf_credit_consumed(string? tf_credit_consumed)
      {
        this.tf_credit_consumed = tf_credit_consumed;
        return this;
      }

      public Builder Withtf_adjusted_asset_value(string? tf_adjusted_asset_value)
      {
        this.tf_adjusted_asset_value = tf_adjusted_asset_value;
        return this;
      }

      public Builder Withtf_adjusted_liability_value(string? tf_adjusted_liability_value)
      {
        this.tf_adjusted_liability_value = tf_adjusted_liability_value;
        return this;
      }

      public Builder Withtf_adjusted_credit_consumed(string? tf_adjusted_credit_consumed)
      {
        this.tf_adjusted_credit_consumed = tf_adjusted_credit_consumed;
        return this;
      }

      public Builder Withtf_adjusted_equity(string? tf_adjusted_equity)
      {
        this.tf_adjusted_equity = tf_adjusted_equity;
        return this;
      }

      public Builder Withfrozen(bool? frozen)
      {
        this.frozen = frozen;
        return this;
      }

      public Builder Withfrozen_reason(string? frozen_reason)
      {
        this.frozen_reason = frozen_reason;
        return this;
      }

      public Builder Withtf_enabled(bool? tf_enabled)
      {
        this.tf_enabled = tf_enabled;
        return this;
      }

      public Builder Withpm_enabled(bool? pm_enabled)
      {
        this.pm_enabled = pm_enabled;
        return this;
      }

      public Builder Withmarket_rates(List<MarketRate>? market_rates)
      {
        this.market_rates = market_rates;
        return this;
      }

      public Builder Withasset_balances(List<AssetBalance>? asset_balances)
      {
        this.asset_balances = asset_balances;
        return this;
      }

      public Builder Withtf_loans(List<LoanInfo>? tf_loans)
      {
        this.tf_loans = tf_loans;
        return this;
      }

      public Builder Withpm_loans(List<LoanInfo>? pm_loans)
      {
        this.pm_loans = pm_loans;
        return this;
      }

      public Builder Withshort_collateral(List<LoanInfo>? short_collateral)
      {
        this.short_collateral = short_collateral;
        return this;
      }

      public Builder Withgross_market_value(string? gross_market_value)
      {
        this.gross_market_value = gross_market_value;
        return this;
      }

      public Builder Withnet_market_value(string? net_market_value)
      {
        this.net_market_value = net_market_value;
        return this;
      }

      public Builder Withlong_market_value(string? long_market_value)
      {
        this.long_market_value = long_market_value;
        return this;
      }

      public Builder Withnon_marginable_long_market_value(string? non_marginable_long_market_value)
      {
        this.non_marginable_long_market_value = non_marginable_long_market_value;
        return this;
      }

      public Builder Withshort_market_value(string? short_market_value)
      {
        this.short_market_value = short_market_value;
        return this;
      }

      public Builder Withgross_leverage(string? gross_leverage)
      {
        this.gross_leverage = gross_leverage;
        return this;
      }

      public Builder Withnet_exposure(string? net_exposure)
      {
        this.net_exposure = net_exposure;
        return this;
      }

      public Builder Withportfolio_stress_triggered(MarginAddOn? portfolio_stress_triggered)
      {
        this.portfolio_stress_triggered = portfolio_stress_triggered;
        return this;
      }

      public Builder Withpm_asset_info(List<PMAssetInfo>? pm_asset_info)
      {
        this.pm_asset_info = pm_asset_info;
        return this;
      }

      public Builder Withpm_credit_limit(string? pm_credit_limit)
      {
        this.pm_credit_limit = pm_credit_limit;
        return this;
      }

      public Builder Withpm_margin_limit(string? pm_margin_limit)
      {
        this.pm_margin_limit = pm_margin_limit;
        return this;
      }

      public Builder Withpm_margin_consumed(string? pm_margin_consumed)
      {
        this.pm_margin_consumed = pm_margin_consumed;
        return this;
      }

      public MarginSummary Build()
      {
        return new MarginSummary(this);
      }
    }
  }

}
