/*
 * Copyright 2025-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

namespace CoinbaseSdk.Prime.Model
{
  using CoinbaseSdk.Prime.Model.Enums;
  using CoinbaseSdk.Prime.Model.MarginSummary;
  using System.Text.Json.Serialization;

  public class MarginSummaryHistorical
  {
    /// <summary>
    /// The UTC date time used for conversion
    /// </summary>
    [JsonPropertyName("conversion_datetime")]
    public string? conversion_datetime { get; set; }

    /// <summary>
    /// The date used for conversion
    /// </summary>
    [JsonPropertyName("conversion_date")]
    public string? conversion_date { get; set; }

    [JsonPropertyName("margin_summary")]
    public MarginSummary? margin_summary { get; set; }

    public MarginSummaryHistorical() { }

    public MarginSummaryHistorical(Builder builder)
    {
      this.conversion_datetime = builder.conversion_datetime;
      this.conversion_date = builder.conversion_date;
      this.margin_summary = builder.margin_summary;
    }

    public class Builder
    {
      private string? conversion_datetime;

      private string? conversion_date;

      private MarginSummary? margin_summary;

      public Builder Withconversion_datetime(string? conversion_datetime)
      {
        this.conversion_datetime = conversion_datetime;
        return this;
      }

      public Builder Withconversion_date(string? conversion_date)
      {
        this.conversion_date = conversion_date;
        return this;
      }

      public Builder Withmargin_summary(MarginSummary? margin_summary)
      {
        this.margin_summary = margin_summary;
        return this;
      }

      public MarginSummaryHistorical Build()
      {
        return new MarginSummaryHistorical(this);
      }
    }
  }

}
