/*
 * Copyright 2025-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

namespace CoinbaseSdk.Prime.Model
{
  using CoinbaseSdk.Prime.Model.Enums;
  using System.Text.Json.Serialization;

  public class Network
  {
    /// <summary>
    /// The network id: base, bitcoin, ethereum, solana etc
    /// </summary>
    [JsonPropertyName("id")]
    public string? id { get; set; }

    /// <summary>
    /// The network type: mainnet, testnet, etc
    /// </summary>
    [JsonPropertyName("type")]
    public string? type { get; set; }

    public Network() { }

    public Network(Builder builder)
    {
      this.id = builder.id;
      this.type = builder.type;
    }

    public static class Builder
    {
      private string? id;

      private string? type;

      public Builder id(string? id)
      {
        this.id = id;
        return this;
      }

      public Builder type(string? type)
      {
        this.type = type;
        return this;
      }

      public Network Build()
      {
        return new Network(this);
      }
    }
  }

}
