// <auto-generated/>
#nullable enable

/*
 * Copyright 2025-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */


namespace CoinbaseSdk.Prime.Model
{
  using System.Text.Json.Serialization;
  using CoinbaseSdk.Prime.Model.Enums;

  public class OnchainTransactionDetails
  {
    /// <summary>
    /// The signed transaction data
    /// </summary>
    [JsonPropertyName("signed_transaction")]
    public string? SignedTransaction { get; set; }
    [JsonPropertyName("risk_assessment")]
    public RiskAssessment? RiskAssessment { get; set; }
    /// <summary>
    /// The blockchain network chain ID. Will be empty for Solana transactions.
    /// </summary>
    [JsonPropertyName("chain_id")]
    public string? ChainId { get; set; }
    /// <summary>
    /// The transaction nonce. Only present for EVM-based blockchain transactions.
    /// </summary>
    [JsonPropertyName("nonce")]
    public string? Nonce { get; set; }
    /// <summary>
    /// The ID of the transaction that this transaction replaced
    /// </summary>
    [JsonPropertyName("replaced_transaction_id")]
    public string? ReplacedTransactionId { get; set; }
    /// <summary>
    /// The destination address for the transaction
    /// </summary>
    [JsonPropertyName("destination_address")]
    public string? DestinationAddress { get; set; }
    /// <summary>
    /// If set to true, the transaction will not be broadcast to the network. You can still retrieve the signed transaction from the GetTransaction endpoint by transaction ID once the transaction is created.
    /// </summary>
    [JsonPropertyName("skip_broadcast")]
    public bool? SkipBroadcast { get; set; }
    /// <summary>
    /// Reason for transaction failure if applicable
    /// </summary>
    [JsonPropertyName("failure_reason")]
    public string? FailureReason { get; set; }
    [JsonPropertyName("signing_status")]
    public SigningStatus? SigningStatus { get; set; }
    public OnchainTransactionDetails() { }

    public OnchainTransactionDetails(Builder builder)
    {
      this.SignedTransaction = builder.signedTransaction;
      this.RiskAssessment = builder.riskAssessment;
      this.ChainId = builder.chainId;
      this.Nonce = builder.nonce;
      this.ReplacedTransactionId = builder.replacedTransactionId;
      this.DestinationAddress = builder.destinationAddress;
      this.SkipBroadcast = builder.skipBroadcast;
      this.FailureReason = builder.failureReason;
      this.SigningStatus = builder.signingStatus;
    }

    public class Builder
    {
#pragma warning disable SA1307, SA1401
      internal string? signedTransaction;
      internal RiskAssessment? riskAssessment;
      internal string? chainId;
      internal string? nonce;
      internal string? replacedTransactionId;
      internal string? destinationAddress;
      internal bool? skipBroadcast;
      internal string? failureReason;
      internal SigningStatus? signingStatus;
#pragma warning restore SA1307, SA1401
      public Builder WithSignedTransaction(string? signedTransaction)
      {
        this.signedTransaction = signedTransaction;
        return this;
      }
      public Builder WithRiskAssessment(RiskAssessment? riskAssessment)
      {
        this.riskAssessment = riskAssessment;
        return this;
      }
      public Builder WithChainId(string? chainId)
      {
        this.chainId = chainId;
        return this;
      }
      public Builder WithNonce(string? nonce)
      {
        this.nonce = nonce;
        return this;
      }
      public Builder WithReplacedTransactionId(string? replacedTransactionId)
      {
        this.replacedTransactionId = replacedTransactionId;
        return this;
      }
      public Builder WithDestinationAddress(string? destinationAddress)
      {
        this.destinationAddress = destinationAddress;
        return this;
      }
      public Builder WithSkipBroadcast(bool? skipBroadcast)
      {
        this.skipBroadcast = skipBroadcast;
        return this;
      }
      public Builder WithFailureReason(string? failureReason)
      {
        this.failureReason = failureReason;
        return this;
      }
      public Builder WithSigningStatus(SigningStatus? signingStatus)
      {
        this.signingStatus = signingStatus;
        return this;
      }
      public OnchainTransactionDetails Build()
      {
        return new OnchainTransactionDetails(this);
      }
    }
  }

}
