/*
 * Copyright 2025-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

namespace CoinbaseSdk.Prime.Model
{
  using CoinbaseSdk.Prime.Model.Enums;
  using System.Text.Json.Serialization;

  public class OnchainAsset
  {
    [JsonPropertyName("network")]
    public string? network { get; set; }

    /// <summary>
    /// Contract Address of this asset (empty for native assets).
    /// </summary>
    [JsonPropertyName("contract_address")]
    public string? contract_address { get; set; }

    /// <summary>
    /// Symbol of this asset.
    /// </summary>
    [JsonPropertyName("symbol")]
    public string? symbol { get; set; }

    /// <summary>
    /// Token ID of this asset (empty for non  NFT assets).
    /// </summary>
    [JsonPropertyName("token_id")]
    public string? token_id { get; set; }

    /// <summary>
    /// Name of this asset, either the name of the crypto token or the NFT collection name.
    /// </summary>
    [JsonPropertyName("name")]
    public string? name { get; set; }

    public OnchainAsset() { }

    public OnchainAsset(Builder builder)
    {
      this.network = builder.network;
      this.contract_address = builder.contract_address;
      this.symbol = builder.symbol;
      this.token_id = builder.token_id;
      this.name = builder.name;
    }

    public static class Builder
    {
      private string? network;

      private string? contract_address;

      private string? symbol;

      private string? token_id;

      private string? name;

      public Builder network(string? network)
      {
        this.network = network;
        return this;
      }

      public Builder contract_address(string? contract_address)
      {
        this.contract_address = contract_address;
        return this;
      }

      public Builder symbol(string? symbol)
      {
        this.symbol = symbol;
        return this;
      }

      public Builder token_id(string? token_id)
      {
        this.token_id = token_id;
        return this;
      }

      public Builder name(string? name)
      {
        this.name = name;
        return this;
      }

      public OnchainAsset Build()
      {
        return new OnchainAsset(this);
      }
    }
  }

}
