// <auto-generated/>
#nullable enable

/*
 * Copyright 2025-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */


namespace CoinbaseSdk.Prime.Model
{
  using System.Text.Json.Serialization;

  public class OnchainTransactionMetadata
  {
    /// <summary>
    /// The transaction type label of the confirmed transaction post settlement
    /// </summary>
    [JsonPropertyName("label")]
    public string? Label { get; set; }
    /// <summary>
    /// The confirmed asset changes (onchain)
    /// </summary>
    [JsonPropertyName("confirmed_asset_changes")]
    public List<AssetChange>? ConfirmedAssetChanges { get; set; }
    public OnchainTransactionMetadata() { }

    public OnchainTransactionMetadata(Builder builder)
    {
      this.Label = builder.label;
      this.ConfirmedAssetChanges = builder.confirmedAssetChanges;
    }

    public class Builder
    {
#pragma warning disable SA1307, SA1401
      internal string? label;
      internal List<AssetChange>? confirmedAssetChanges;
#pragma warning restore SA1307, SA1401
      public Builder WithLabel(string? label)
      {
        this.label = label;
        return this;
      }
      public Builder WithConfirmedAssetChanges(List<AssetChange>? confirmedAssetChanges)
      {
        this.confirmedAssetChanges = confirmedAssetChanges;
        return this;
      }
      public OnchainTransactionMetadata Build()
      {
        return new OnchainTransactionMetadata(this);
      }
    }
  }

}
