// <auto-generated/>
#nullable enable

/*
 * Copyright 2025-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */


namespace CoinbaseSdk.Prime.Model
{
  using System.Text.Json.Serialization;
  using CoinbaseSdk.Prime.Model.Enums;

  public class OnchainBalance
  {
    [JsonPropertyName("asset")]
    public OnchainAsset? Asset { get; set; }
    /// <summary>
    /// The total amount in whole units with full precision.
    /// </summary>
    [JsonPropertyName("amount")]
    public string? Amount { get; set; }
    [JsonPropertyName("visibility_status")]
    public VisibilityStatus? VisibilityStatus { get; set; }
    public OnchainBalance() { }

    public OnchainBalance(Builder builder)
    {
      this.Asset = builder.asset;
      this.Amount = builder.amount;
      this.VisibilityStatus = builder.visibilityStatus;
    }

    public class Builder
    {
#pragma warning disable SA1307, SA1401
      internal OnchainAsset? asset;
      internal string? amount;
      internal VisibilityStatus? visibilityStatus;
#pragma warning restore SA1307, SA1401
      public Builder WithAsset(OnchainAsset? asset)
      {
        this.asset = asset;
        return this;
      }
      public Builder WithAmount(string? amount)
      {
        this.amount = amount;
        return this;
      }
      public Builder WithVisibilityStatus(VisibilityStatus? visibilityStatus)
      {
        this.visibilityStatus = visibilityStatus;
        return this;
      }
      public OnchainBalance Build()
      {
        return new OnchainBalance(this);
      }
    }
  }

}
