// <auto-generated/>
#nullable enable

/*
 * Copyright 2025-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */


namespace CoinbaseSdk.Prime.Model
{
  using System.Text.Json.Serialization;

  public class OrderEdit
  {
    [JsonPropertyName("price")]
    public string? Price { get; set; }
    [JsonPropertyName("base_quantity")]
    public string? BaseQuantity { get; set; }
    [JsonPropertyName("quote_value")]
    public string? QuoteValue { get; set; }
    [JsonPropertyName("display_base_size")]
    public string? DisplayBaseSize { get; set; }
    [JsonPropertyName("display_quote_size")]
    public string? DisplayQuoteSize { get; set; }
    [JsonPropertyName("stop_price")]
    public string? StopPrice { get; set; }
    [JsonPropertyName("expiry_time")]
    public DateTime? ExpiryTime { get; set; }
    [JsonPropertyName("accept_time")]
    public DateTime? AcceptTime { get; set; }
    [JsonPropertyName("client_order_id")]
    public string? ClientOrderId { get; set; }
    public OrderEdit() { }

    public OrderEdit(Builder builder)
    {
      this.Price = builder.price;
      this.BaseQuantity = builder.baseQuantity;
      this.QuoteValue = builder.quoteValue;
      this.DisplayBaseSize = builder.displayBaseSize;
      this.DisplayQuoteSize = builder.displayQuoteSize;
      this.StopPrice = builder.stopPrice;
      this.ExpiryTime = builder.expiryTime;
      this.AcceptTime = builder.acceptTime;
      this.ClientOrderId = builder.clientOrderId;
    }

    public class Builder
    {
#pragma warning disable SA1307, SA1401
      internal string? price;
      internal string? baseQuantity;
      internal string? quoteValue;
      internal string? displayBaseSize;
      internal string? displayQuoteSize;
      internal string? stopPrice;
      internal DateTime? expiryTime;
      internal DateTime? acceptTime;
      internal string? clientOrderId;
#pragma warning restore SA1307, SA1401
      public Builder WithPrice(string? price)
      {
        this.price = price;
        return this;
      }
      public Builder WithBaseQuantity(string? baseQuantity)
      {
        this.baseQuantity = baseQuantity;
        return this;
      }
      public Builder WithQuoteValue(string? quoteValue)
      {
        this.quoteValue = quoteValue;
        return this;
      }
      public Builder WithDisplayBaseSize(string? displayBaseSize)
      {
        this.displayBaseSize = displayBaseSize;
        return this;
      }
      public Builder WithDisplayQuoteSize(string? displayQuoteSize)
      {
        this.displayQuoteSize = displayQuoteSize;
        return this;
      }
      public Builder WithStopPrice(string? stopPrice)
      {
        this.stopPrice = stopPrice;
        return this;
      }
      public Builder WithExpiryTime(DateTime? expiryTime)
      {
        this.expiryTime = expiryTime;
        return this;
      }
      public Builder WithAcceptTime(DateTime? acceptTime)
      {
        this.acceptTime = acceptTime;
        return this;
      }
      public Builder WithClientOrderId(string? clientOrderId)
      {
        this.clientOrderId = clientOrderId;
        return this;
      }
      public OrderEdit Build()
      {
        return new OrderEdit(this);
      }
    }
  }

}
