// <auto-generated/>
#nullable enable

/*
 * Copyright 2026-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 *  Do not edit the class manually.
 */


namespace CoinbaseSdk.Prime.Model
{
  using CoinbaseSdk.Prime.Model.Enums;

  public class Order
  {
    /// <summary>
    /// The unique order ID generated by Coinbase
    /// </summary>
    public string? Id { get; set; }
    /// <summary>
    /// The ID of the user that created the order
    /// </summary>
    public string? UserId { get; set; }
    /// <summary>
    /// The ID of the portfolio that owns the order
    /// </summary>
    public string? PortfolioId { get; set; }
    /// <summary>
    /// The ID of the product being traded by the order
    /// </summary>
    public string? ProductId { get; set; }
    public OrderSide? Side { get; set; }
    /// <summary>
    /// A client-generated order ID used for reference purposes (note: order will be rejected if this ID is not unique among all currently active orders)
    /// </summary>
    public string? ClientOrderId { get; set; }
    public OrderType? Type { get; set; }
    /// <summary>
    /// Order size in base asset units (either &#x60;base_quantity&#x60; or &#x60;quote_value&#x60; is required)
    /// </summary>
    public string? BaseQuantity { get; set; }
    /// <summary>
    /// Order size in quote asset units, i.e. the amount the user wants to spend (when buying) or receive (when selling); the quantity in base units will be determined based on the market liquidity and indicated &#x60;quote_value&#x60;. Either &#x60;base_quantity&#x60; or &#x60;quote_value&#x60; is required
    /// </summary>
    public string? QuoteValue { get; set; }
    /// <summary>
    /// The limit price (required for TWAP, VWAP, LIMIT and STOP_LIMIT orders)
    /// </summary>
    public string? LimitPrice { get; set; }
    /// <summary>
    /// The start time of the order in UTC (only applies to TWAP, VWAP orders.)
    /// </summary>
    public DateTime? StartTime { get; set; }
    /// <summary>
    /// The expiry time of the order in UTC (applies to TWAP, VWAP, LIMIT, and STOP_LIMIT orders with &#x60;time_in_force&#x60; set to &#x60;GTD&#x60;)
    /// </summary>
    public DateTime? ExpiryTime { get; set; }
    public OrderStatus? Status { get; set; }
    public TimeInForceType? TimeInForce { get; set; }
    /// <summary>
    /// The order creation time as a UTC timestamp
    /// </summary>
    public DateTime? CreatedAt { get; set; }
    /// <summary>
    /// Size filled (in base asset units)
    /// </summary>
    public string? FilledQuantity { get; set; }
    /// <summary>
    /// Market value filled (in quote asset units)
    /// </summary>
    public string? FilledValue { get; set; }
    /// <summary>
    /// Indicates the average &#x60;filled_price&#x60;
    /// </summary>
    public string? AverageFilledPrice { get; set; }
    /// <summary>
    /// Total commission paid on this order (in quote asset units) - - only applicable for partially- or fully-filled orders
    /// </summary>
    public string? Commission { get; set; }
    /// <summary>
    /// Fee charged by the exchange for Cost Plus commission configurations. Exchange fee will be 0 for All In commission configurations.
    /// </summary>
    public string? ExchangeFee { get; set; }
    /// <summary>
    /// historical pov for the order
    /// </summary>
    public string? HistoricalPov { get; set; }
    /// <summary>
    /// Specifies the stop price at which the order activates. The order is activated if the last trade price on Coinbase Exchange crosses the stop price specified on the order
    /// </summary>
    public string? StopPrice { get; set; }
    /// <summary>
    /// Indicates the average &#x60;filled_price&#x60; net of commissions and fees
    /// </summary>
    public string? NetAverageFilledPrice { get; set; }
    /// <summary>
    /// Indicates a user friendly message for regarding various aspects of the order such as cancellation or rejection reasons
    /// </summary>
    public string? UserContext { get; set; }
    /// <summary>
    /// The client product ID of the fill indictating the settlment currency
    /// </summary>
    public string? ClientProductId { get; set; }
    /// <summary>
    /// Post-only flag - indicates whether the order was placed as post-only
    /// </summary>
    public bool? PostOnly { get; set; }
    /// <summary>
    /// The history of order edits (deprecated: use edit_history instead)
    /// </summary>
    public List<LimitOrderEdit>? OrderEditHistory { get; set; }
    /// <summary>
    /// Indicates if this was a raise exact order (size inclusive of fees for sell orders in quote)
    /// </summary>
    public bool? IsRaiseExact { get; set; }
    /// <summary>
    /// Display size for the order
    /// </summary>
    public string? DisplaySize { get; set; }
    /// <summary>
    /// The history of order edits
    /// </summary>
    public List<OrderEdit>? EditHistory { get; set; }
    /// <summary>
    /// The maximum order size that will show up on venue order books (in quote currency).
    /// </summary>
    public string? DisplayQuoteSize { get; set; }
    /// <summary>
    /// The maximum order size that will show up on venue order books (in base currency).
    /// </summary>
    public string? DisplayBaseSize { get; set; }
    /// <summary>
    /// The peg offset type for PEG orders (PRICE, BASIS_POINTS, or CUMULATIVE_DEPTH_IN_BASE_UNITS)
    /// </summary>
    public string? PegOffsetType { get; set; }
    /// <summary>
    /// The offset value for PEG orders
    /// </summary>
    public string? Offset { get; set; }
    /// <summary>
    /// The wig (would if good) level for PEG orders - best price opposite to limit_price
    /// </summary>
    public string? WigLevel { get; set; }
    public ProductType? ProductType { get; set; }
    public CommissionDetailTotal? CommissionDetailTotal { get; set; }
    public Order() { }

    public Order(Builder builder)
    {
      this.Id = builder.id;
      this.UserId = builder.userId;
      this.PortfolioId = builder.portfolioId;
      this.ProductId = builder.productId;
      this.Side = builder.side;
      this.ClientOrderId = builder.clientOrderId;
      this.Type = builder.type;
      this.BaseQuantity = builder.baseQuantity;
      this.QuoteValue = builder.quoteValue;
      this.LimitPrice = builder.limitPrice;
      this.StartTime = builder.startTime;
      this.ExpiryTime = builder.expiryTime;
      this.Status = builder.status;
      this.TimeInForce = builder.timeInForce;
      this.CreatedAt = builder.createdAt;
      this.FilledQuantity = builder.filledQuantity;
      this.FilledValue = builder.filledValue;
      this.AverageFilledPrice = builder.averageFilledPrice;
      this.Commission = builder.commission;
      this.ExchangeFee = builder.exchangeFee;
      this.HistoricalPov = builder.historicalPov;
      this.StopPrice = builder.stopPrice;
      this.NetAverageFilledPrice = builder.netAverageFilledPrice;
      this.UserContext = builder.userContext;
      this.ClientProductId = builder.clientProductId;
      this.PostOnly = builder.postOnly;
      this.OrderEditHistory = builder.orderEditHistory;
      this.IsRaiseExact = builder.isRaiseExact;
      this.DisplaySize = builder.displaySize;
      this.EditHistory = builder.editHistory;
      this.DisplayQuoteSize = builder.displayQuoteSize;
      this.DisplayBaseSize = builder.displayBaseSize;
      this.PegOffsetType = builder.pegOffsetType;
      this.Offset = builder.offset;
      this.WigLevel = builder.wigLevel;
      this.ProductType = builder.productType;
      this.CommissionDetailTotal = builder.commissionDetailTotal;
    }

    public class Builder
    {
#pragma warning disable SA1307, SA1401
      internal string? id;
      internal string? userId;
      internal string? portfolioId;
      internal string? productId;
      internal OrderSide? side;
      internal string? clientOrderId;
      internal OrderType? type;
      internal string? baseQuantity;
      internal string? quoteValue;
      internal string? limitPrice;
      internal DateTime? startTime;
      internal DateTime? expiryTime;
      internal OrderStatus? status;
      internal TimeInForceType? timeInForce;
      internal DateTime? createdAt;
      internal string? filledQuantity;
      internal string? filledValue;
      internal string? averageFilledPrice;
      internal string? commission;
      internal string? exchangeFee;
      internal string? historicalPov;
      internal string? stopPrice;
      internal string? netAverageFilledPrice;
      internal string? userContext;
      internal string? clientProductId;
      internal bool? postOnly;
      internal List<LimitOrderEdit>? orderEditHistory;
      internal bool? isRaiseExact;
      internal string? displaySize;
      internal List<OrderEdit>? editHistory;
      internal string? displayQuoteSize;
      internal string? displayBaseSize;
      internal string? pegOffsetType;
      internal string? offset;
      internal string? wigLevel;
      internal ProductType? productType;
      internal CommissionDetailTotal? commissionDetailTotal;
#pragma warning restore SA1307, SA1401
      public Builder WithId(string? id)
      {
        this.id = id;
        return this;
      }
      public Builder WithUserId(string? userId)
      {
        this.userId = userId;
        return this;
      }
      public Builder WithPortfolioId(string? portfolioId)
      {
        this.portfolioId = portfolioId;
        return this;
      }
      public Builder WithProductId(string? productId)
      {
        this.productId = productId;
        return this;
      }
      public Builder WithSide(OrderSide? side)
      {
        this.side = side;
        return this;
      }
      public Builder WithClientOrderId(string? clientOrderId)
      {
        this.clientOrderId = clientOrderId;
        return this;
      }
      public Builder WithType(OrderType? type)
      {
        this.type = type;
        return this;
      }
      public Builder WithBaseQuantity(string? baseQuantity)
      {
        this.baseQuantity = baseQuantity;
        return this;
      }
      public Builder WithQuoteValue(string? quoteValue)
      {
        this.quoteValue = quoteValue;
        return this;
      }
      public Builder WithLimitPrice(string? limitPrice)
      {
        this.limitPrice = limitPrice;
        return this;
      }
      public Builder WithStartTime(DateTime? startTime)
      {
        this.startTime = startTime;
        return this;
      }
      public Builder WithExpiryTime(DateTime? expiryTime)
      {
        this.expiryTime = expiryTime;
        return this;
      }
      public Builder WithStatus(OrderStatus? status)
      {
        this.status = status;
        return this;
      }
      public Builder WithTimeInForce(TimeInForceType? timeInForce)
      {
        this.timeInForce = timeInForce;
        return this;
      }
      public Builder WithCreatedAt(DateTime? createdAt)
      {
        this.createdAt = createdAt;
        return this;
      }
      public Builder WithFilledQuantity(string? filledQuantity)
      {
        this.filledQuantity = filledQuantity;
        return this;
      }
      public Builder WithFilledValue(string? filledValue)
      {
        this.filledValue = filledValue;
        return this;
      }
      public Builder WithAverageFilledPrice(string? averageFilledPrice)
      {
        this.averageFilledPrice = averageFilledPrice;
        return this;
      }
      public Builder WithCommission(string? commission)
      {
        this.commission = commission;
        return this;
      }
      public Builder WithExchangeFee(string? exchangeFee)
      {
        this.exchangeFee = exchangeFee;
        return this;
      }
      public Builder WithHistoricalPov(string? historicalPov)
      {
        this.historicalPov = historicalPov;
        return this;
      }
      public Builder WithStopPrice(string? stopPrice)
      {
        this.stopPrice = stopPrice;
        return this;
      }
      public Builder WithNetAverageFilledPrice(string? netAverageFilledPrice)
      {
        this.netAverageFilledPrice = netAverageFilledPrice;
        return this;
      }
      public Builder WithUserContext(string? userContext)
      {
        this.userContext = userContext;
        return this;
      }
      public Builder WithClientProductId(string? clientProductId)
      {
        this.clientProductId = clientProductId;
        return this;
      }
      public Builder WithPostOnly(bool? postOnly)
      {
        this.postOnly = postOnly;
        return this;
      }
      public Builder WithOrderEditHistory(List<LimitOrderEdit>? orderEditHistory)
      {
        this.orderEditHistory = orderEditHistory;
        return this;
      }
      public Builder WithIsRaiseExact(bool? isRaiseExact)
      {
        this.isRaiseExact = isRaiseExact;
        return this;
      }
      public Builder WithDisplaySize(string? displaySize)
      {
        this.displaySize = displaySize;
        return this;
      }
      public Builder WithEditHistory(List<OrderEdit>? editHistory)
      {
        this.editHistory = editHistory;
        return this;
      }
      public Builder WithDisplayQuoteSize(string? displayQuoteSize)
      {
        this.displayQuoteSize = displayQuoteSize;
        return this;
      }
      public Builder WithDisplayBaseSize(string? displayBaseSize)
      {
        this.displayBaseSize = displayBaseSize;
        return this;
      }
      public Builder WithPegOffsetType(string? pegOffsetType)
      {
        this.pegOffsetType = pegOffsetType;
        return this;
      }
      public Builder WithOffset(string? offset)
      {
        this.offset = offset;
        return this;
      }
      public Builder WithWigLevel(string? wigLevel)
      {
        this.wigLevel = wigLevel;
        return this;
      }
      public Builder WithProductType(ProductType? productType)
      {
        this.productType = productType;
        return this;
      }
      public Builder WithCommissionDetailTotal(CommissionDetailTotal? commissionDetailTotal)
      {
        this.commissionDetailTotal = commissionDetailTotal;
        return this;
      }
      public Order Build()
      {
        return new Order(this);
      }
    }
  }

}
