/*
 * Copyright 2025-present Coinbase Global, Inc.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

namespace CoinbaseSdk.Prime.Model
{
  using System.Text.Json.Serialization;

  /// <summary>
  /// Represents a trading order in the Coinbase Prime system.
  /// </summary>
  public class Order
  {
    /// <summary>
    /// The unique order ID generated by Coinbase.
    /// </summary>
    public string? Id { get; set; }

    /// <summary>
    /// The ID of the user that created the order.
    /// </summary>
    [JsonPropertyName("user_id")]
    public string? UserId { get; set; }

    /// <summary>
    /// The ID of the portfolio that owns the order.
    /// </summary>
    [JsonPropertyName("portfolio_id")]
    public string? PortfolioId { get; set; }

    /// <summary>
    /// The ID of the product being traded by the order.
    /// </summary>
    [JsonPropertyName("product_id")]
    public string? ProductId { get; set; }

    /// <summary>
    /// The side of the order (BUY or SELL).
    /// </summary>
    public OrderSide? Side { get; set; }

    /// <summary>
    /// A client-generated order ID used for reference purposes (note: order will be rejected if this ID is not unique among all currently active orders).
    /// </summary>
    [JsonPropertyName("client_order_id")]
    public string? ClientOrderId { get; set; }

    /// <summary>
    /// Strategy (execution algorithm) for the order.
    /// </summary>
    public OrderType? Type { get; set; }

    /// <summary>
    /// Order size in base asset units (either base_quantity or quote_value is required).
    /// </summary>
    [JsonPropertyName("base_quantity")]
    public string? BaseQuantity { get; set; }

    /// <summary>
    /// Order size in quote asset units, i.e. the amount the user wants to spend (when buying) or receive (when selling); the quantity in base units will be determined based on the market liquidity and indicated quote_value. Either base_quantity or quote_value is required.
    /// </summary>
    [JsonPropertyName("quote_value")]
    public string? QuoteValue { get; set; }

    /// <summary>
    /// The limit price (required for TWAP, VWAP, LIMIT and STOP_LIMIT orders).
    /// </summary>
    [JsonPropertyName("limit_price")]
    public string? LimitPrice { get; set; }

    /// <summary>
    /// Specifies the stop price at which the order activates. The order is activated if the last trade price on Coinbase Exchange crosses the stop price specified on the order.
    /// </summary>
    [JsonPropertyName("stop_price")]
    public string? StopPrice { get; set; }

    /// <summary>
    /// The start time of the order in UTC (only applies to TWAP, VWAP orders.).
    /// </summary>
    [JsonPropertyName("start_time")]
    public string? StartTime { get; set; }

    /// <summary>
    /// The expiry time of the order in UTC (applies to TWAP, VWAP, LIMIT, and STOP_LIMIT orders with time_in_force set to GTD).
    /// </summary>
    [JsonPropertyName("expiry_time")]
    public string? ExpiryTime { get; set; }

    /// <summary>
    /// Indicates the order status.
    /// </summary>
    public OrderStatus? Status { get; set; }

    /// <summary>
    /// Indicates the order time validity.
    /// </summary>
    [JsonPropertyName("time_in_force")]
    public TimeInForce? TimeInForce { get; set; }

    /// <summary>
    /// The order creation time as a UTC timestamp.
    /// </summary>
    [JsonPropertyName("created_at")]
    public string? CreatedAt { get; set; }

    /// <summary>
    /// Size filled (in base asset units).
    /// </summary>
    [JsonPropertyName("filled_quantity")]
    public string? FilledQuantity { get; set; }

    /// <summary>
    /// Market value filled (in quote asset units).
    /// </summary>
    [JsonPropertyName("filled_value")]
    public string? FilledValue { get; set; }

    /// <summary>
    /// Indicates the average filled_price.
    /// </summary>
    [JsonPropertyName("average_filled_price")]
    public string? AverageFilledPrice { get; set; }

    /// <summary>
    /// Total commission paid on this order (in quote asset units) -- only applicable for partially- or fully-filled orders.
    /// </summary>
    public string? Commission { get; set; }

    /// <summary>
    /// Fee charged by the exchange for Cost Plus commission configurations. Exchange fee will be 0 for All In commission configurations.
    /// </summary>
    [JsonPropertyName("exchange_fee")]
    public string? ExchangeFee { get; set; }

    /// <summary>
    /// Historical pov for the order.
    /// </summary>
    [JsonPropertyName("historical_pov")]
    public string? HistoricalPov { get; set; }

    public Order() { }

    /// <summary>
    /// Builder class for creating Order instances.
    /// </summary>
    public class OrderBuilder
    {
      private string? _id;
      private string? _userId;
      private string? _portfolioId;
      private string? _productId;
      private OrderSide? _side;
      private string? _clientOrderId;
      private OrderType? _type;
      private string? _baseQuantity;
      private string? _quoteValue;
      private string? _limitPrice;
      private string? _stopPrice;
      private string? _startTime;
      private string? _expiryTime;
      private OrderStatus? _status;
      private TimeInForce? _timeInForce;
      private string? _createdAt;
      private string? _filledQuantity;
      private string? _filledValue;
      private string? _averageFilledPrice;
      private string? _commission;
      private string? _exchangeFee;
      private string? _historicalPov;

      public OrderBuilder WithId(string id)
      {
        this._id = id;
        return this;
      }

      public OrderBuilder WithUserId(string userId)
      {
        this._userId = userId;
        return this;
      }

      public OrderBuilder WithPortfolioId(string portfolioId)
      {
        this._portfolioId = portfolioId;
        return this;
      }

      public OrderBuilder WithProductId(string productId)
      {
        this._productId = productId;
        return this;
      }

      public OrderBuilder WithSide(OrderSide side)
      {
        this._side = side;
        return this;
      }

      public OrderBuilder WithClientOrderId(string clientOrderId)
      {
        this._clientOrderId = clientOrderId;
        return this;
      }

      public OrderBuilder WithType(OrderType type)
      {
        this._type = type;
        return this;
      }

      public OrderBuilder WithBaseQuantity(string baseQuantity)
      {
        this._baseQuantity = baseQuantity;
        return this;
      }

      public OrderBuilder WithQuoteValue(string quoteValue)
      {
        this._quoteValue = quoteValue;
        return this;
      }

      public OrderBuilder WithLimitPrice(string limitPrice)
      {
        this._limitPrice = limitPrice;
        return this;
      }

      public OrderBuilder WithStopPrice(string stopPrice)
      {
        this._stopPrice = stopPrice;
        return this;
      }

      public OrderBuilder WithStartTime(string startTime)
      {
        this._startTime = startTime;
        return this;
      }

      public OrderBuilder WithExpiryTime(string expiryTime)
      {
        this._expiryTime = expiryTime;
        return this;
      }

      public OrderBuilder WithStatus(OrderStatus status)
      {
        this._status = status;
        return this;
      }

      public OrderBuilder WithTimeInForce(TimeInForce timeInForce)
      {
        this._timeInForce = timeInForce;
        return this;
      }

      public OrderBuilder WithCreatedAt(string createdAt)
      {
        this._createdAt = createdAt;
        return this;
      }

      public OrderBuilder WithFilledQuantity(string filledQuantity)
      {
        this._filledQuantity = filledQuantity;
        return this;
      }

      public OrderBuilder WithFilledValue(string filledValue)
      {
        this._filledValue = filledValue;
        return this;
      }

      public OrderBuilder WithAverageFilledPrice(string averageFilledPrice)
      {
        this._averageFilledPrice = averageFilledPrice;
        return this;
      }

      public OrderBuilder WithCommission(string commission)
      {
        this._commission = commission;
        return this;
      }

      public OrderBuilder WithExchangeFee(string exchangeFee)
      {
        this._exchangeFee = exchangeFee;
        return this;
      }

      public OrderBuilder WithHistoricalPov(string historicalPov)
      {
        this._historicalPov = historicalPov;
        return this;
      }

      public Order Build()
      {
        return new Order
        {
          Id = this._id,
          UserId = this._userId,
          PortfolioId = this._portfolioId,
          ProductId = this._productId,
          Side = this._side,
          ClientOrderId = this._clientOrderId,
          Type = this._type,
          BaseQuantity = this._baseQuantity,
          QuoteValue = this._quoteValue,
          LimitPrice = this._limitPrice,
          StopPrice = this._stopPrice,
          StartTime = this._startTime,
          ExpiryTime = this._expiryTime,
          Status = this._status,
          TimeInForce = this._timeInForce,
          CreatedAt = this._createdAt,
          FilledQuantity = this._filledQuantity,
          FilledValue = this._filledValue,
          AverageFilledPrice = this._averageFilledPrice,
          Commission = this._commission,
          ExchangeFee = this._exchangeFee,
          HistoricalPov = this._historicalPov,
        };
      }
    }
  }
}
