/*
 * Copyright 2025-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

namespace CoinbaseSdk.Prime.Model
{
  using CoinbaseSdk.Prime.Model.Enums;
  using CoinbaseSdk.Prime.Model.PaymentMethodType;
  using System.Text.Json.Serialization;

  public class PaymentMethodSummary
  {
    [JsonPropertyName("id")]
    public string? id { get; set; }

    [JsonPropertyName("symbol")]
    public string? symbol { get; set; }

    [JsonPropertyName("payment_method_type")]
    public PaymentMethodType? payment_method_type { get; set; }

    [JsonPropertyName("bank_name")]
    public string? bank_name { get; set; }

    [JsonPropertyName("account_number")]
    public string? account_number { get; set; }

    [JsonPropertyName("bank_name_2")]
    public string? bank_name_2 { get; set; }

    public PaymentMethodSummary() { }

    public PaymentMethodSummary(Builder builder)
    {
      this.id = builder.id;
      this.symbol = builder.symbol;
      this.payment_method_type = builder.payment_method_type;
      this.bank_name = builder.bank_name;
      this.account_number = builder.account_number;
      this.bank_name_2 = builder.bank_name_2;
    }

    public static class Builder
    {
      private string? id;

      private string? symbol;

      private PaymentMethodType? payment_method_type;

      private string? bank_name;

      private string? account_number;

      private string? bank_name_2;

      public Builder id(string? id)
      {
        this.id = id;
        return this;
      }

      public Builder symbol(string? symbol)
      {
        this.symbol = symbol;
        return this;
      }

      public Builder payment_method_type(PaymentMethodType? payment_method_type)
      {
        this.payment_method_type = payment_method_type;
        return this;
      }

      public Builder bank_name(string? bank_name)
      {
        this.bank_name = bank_name;
        return this;
      }

      public Builder account_number(string? account_number)
      {
        this.account_number = account_number;
        return this;
      }

      public Builder bank_name_2(string? bank_name_2)
      {
        this.bank_name_2 = bank_name_2;
        return this;
      }

      public PaymentMethodSummary Build()
      {
        return new PaymentMethodSummary(this);
      }
    }
  }

}
