// <auto-generated/>
#nullable enable

/*
 * Copyright 2025-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */


namespace CoinbaseSdk.Prime.Model
{
  using System.Text.Json.Serialization;
  using CoinbaseSdk.Prime.Model.Enums;

  public class PaymentMethodSummary
  {
    [JsonPropertyName("id")]
    public string? Id { get; set; }
    [JsonPropertyName("symbol")]
    public string? Symbol { get; set; }
    [JsonPropertyName("payment_method_type")]
    public PaymentMethodType? PaymentMethodType { get; set; }
    [JsonPropertyName("bank_name")]
    public string? BankName { get; set; }
    [JsonPropertyName("account_number")]
    public string? AccountNumber { get; set; }
    [JsonPropertyName("bank_name_2")]
    public string? BankName2 { get; set; }
    public PaymentMethodSummary() { }

    public PaymentMethodSummary(Builder builder)
    {
      this.Id = builder.id;
      this.Symbol = builder.symbol;
      this.PaymentMethodType = builder.paymentMethodType;
      this.BankName = builder.bankName;
      this.AccountNumber = builder.accountNumber;
      this.BankName2 = builder.bankName2;
    }

    public class Builder
    {
#pragma warning disable SA1307, SA1401
      internal string? id;
      internal string? symbol;
      internal PaymentMethodType? paymentMethodType;
      internal string? bankName;
      internal string? accountNumber;
      internal string? bankName2;
#pragma warning restore SA1307, SA1401
      public Builder WithId(string? id)
      {
        this.id = id;
        return this;
      }
      public Builder WithSymbol(string? symbol)
      {
        this.symbol = symbol;
        return this;
      }
      public Builder WithPaymentMethodType(PaymentMethodType? paymentMethodType)
      {
        this.paymentMethodType = paymentMethodType;
        return this;
      }
      public Builder WithBankName(string? bankName)
      {
        this.bankName = bankName;
        return this;
      }
      public Builder WithAccountNumber(string? accountNumber)
      {
        this.accountNumber = accountNumber;
        return this;
      }
      public Builder WithBankName2(string? bankName2)
      {
        this.bankName2 = bankName2;
        return this;
      }
      public PaymentMethodSummary Build()
      {
        return new PaymentMethodSummary(this);
      }
    }
  }

}
