// <auto-generated/>
#nullable enable

/*
 * Copyright 2025-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */


namespace CoinbaseSdk.Prime.Model
{
  using System.Text.Json.Serialization;

  public class PerpetualProductDetails
  {
    /// <summary>
    /// Open interest
    /// </summary>
    [JsonPropertyName("open_interest")]
    public string? OpenInterest { get; set; }
    /// <summary>
    /// Current funding rate
    /// </summary>
    [JsonPropertyName("funding_rate")]
    public string? FundingRate { get; set; }
    /// <summary>
    /// Next funding time
    /// </summary>
    [JsonPropertyName("funding_time")]
    public DateTime? FundingTime { get; set; }
    /// <summary>
    /// Maximum leverage allowed
    /// </summary>
    [JsonPropertyName("max_leverage")]
    public string? MaxLeverage { get; set; }
    /// <summary>
    /// The type of underlying for the perpetual product
    /// </summary>
    [JsonPropertyName("underlying_type")]
    public string? UnderlyingType { get; set; }
    public PerpetualProductDetails() { }

    public PerpetualProductDetails(Builder builder)
    {
      this.OpenInterest = builder.openInterest;
      this.FundingRate = builder.fundingRate;
      this.FundingTime = builder.fundingTime;
      this.MaxLeverage = builder.maxLeverage;
      this.UnderlyingType = builder.underlyingType;
    }

    public class Builder
    {
#pragma warning disable SA1307, SA1401
      internal string? openInterest;
      internal string? fundingRate;
      internal DateTime? fundingTime;
      internal string? maxLeverage;
      internal string? underlyingType;
#pragma warning restore SA1307, SA1401
      public Builder WithOpenInterest(string? openInterest)
      {
        this.openInterest = openInterest;
        return this;
      }
      public Builder WithFundingRate(string? fundingRate)
      {
        this.fundingRate = fundingRate;
        return this;
      }
      public Builder WithFundingTime(DateTime? fundingTime)
      {
        this.fundingTime = fundingTime;
        return this;
      }
      public Builder WithMaxLeverage(string? maxLeverage)
      {
        this.maxLeverage = maxLeverage;
        return this;
      }
      public Builder WithUnderlyingType(string? underlyingType)
      {
        this.underlyingType = underlyingType;
        return this;
      }
      public PerpetualProductDetails Build()
      {
        return new PerpetualProductDetails(this);
      }
    }
  }

}
