// <auto-generated/>
#nullable enable

/*
 * Copyright 2025-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */


namespace CoinbaseSdk.Prime.Model
{
  using System.Text.Json.Serialization;

  public class Portfolio
  {
    /// <summary>
    /// The unique ID of the portfolio
    /// </summary>
    [JsonPropertyName("id")]
    public string? Id { get; set; }
    /// <summary>
    /// The name of the portfolio
    /// </summary>
    [JsonPropertyName("name")]
    public string? Name { get; set; }
    /// <summary>
    /// The ID of the entity to which the portfolio is associated
    /// </summary>
    [JsonPropertyName("entity_id")]
    public string? EntityId { get; set; }
    /// <summary>
    /// The ID of the organization to which the portfolio is associated
    /// </summary>
    [JsonPropertyName("organization_id")]
    public string? OrganizationId { get; set; }
    /// <summary>
    /// The name of the entity to which the portfolio is associated
    /// </summary>
    [JsonPropertyName("entity_name")]
    public string? EntityName { get; set; }
    public Portfolio() { }

    public Portfolio(Builder builder)
    {
      this.Id = builder.id;
      this.Name = builder.name;
      this.EntityId = builder.entityId;
      this.OrganizationId = builder.organizationId;
      this.EntityName = builder.entityName;
    }

    public class Builder
    {
#pragma warning disable SA1307, SA1401
      internal string? id;
      internal string? name;
      internal string? entityId;
      internal string? organizationId;
      internal string? entityName;
#pragma warning restore SA1307, SA1401
      public Builder WithId(string? id)
      {
        this.id = id;
        return this;
      }
      public Builder WithName(string? name)
      {
        this.name = name;
        return this;
      }
      public Builder WithEntityId(string? entityId)
      {
        this.entityId = entityId;
        return this;
      }
      public Builder WithOrganizationId(string? organizationId)
      {
        this.organizationId = organizationId;
        return this;
      }
      public Builder WithEntityName(string? entityName)
      {
        this.entityName = entityName;
        return this;
      }
      public Portfolio Build()
      {
        return new Portfolio(this);
      }
    }
  }

}
