// <auto-generated/>
#nullable enable

/*
 * Copyright 2025-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */


namespace CoinbaseSdk.Prime.Model
{
  using System.Text.Json.Serialization;

  public class PostTradeCreditInformation
  {
    /// <summary>
    /// The unique ID of the portfolio
    /// </summary>
    [JsonPropertyName("portfolio_id")]
    public string? PortfolioId { get; set; }
    /// <summary>
    /// The currency symbol credit is denoted in
    /// </summary>
    [JsonPropertyName("currency")]
    public string? Currency { get; set; }
    /// <summary>
    /// The maximum credit limit
    /// </summary>
    [JsonPropertyName("limit")]
    public string? Limit { get; set; }
    /// <summary>
    /// The amount of credit used
    /// </summary>
    [JsonPropertyName("utilized")]
    public string? Utilized { get; set; }
    /// <summary>
    /// The amount of credit available
    /// </summary>
    [JsonPropertyName("available")]
    public string? Available { get; set; }
    /// <summary>
    /// Whether or not a portfolio is frozen due to balance outstanding or other reason
    /// </summary>
    [JsonPropertyName("frozen")]
    public bool? Frozen { get; set; }
    /// <summary>
    /// The reason why the portfolio is frozen
    /// </summary>
    [JsonPropertyName("frozen_reason")]
    public string? FrozenReason { get; set; }
    [JsonPropertyName("amounts_due")]
    public List<AmountDue>? AmountsDue { get; set; }
    /// <summary>
    /// Whether the portfolio has credit enabled
    /// </summary>
    [JsonPropertyName("enabled")]
    public bool? Enabled { get; set; }
    /// <summary>
    /// The amount of adjusted credit used
    /// </summary>
    [JsonPropertyName("adjusted_credit_utilized")]
    public string? AdjustedCreditUtilized { get; set; }
    /// <summary>
    /// The amount of adjusted portfolio equity
    /// </summary>
    [JsonPropertyName("adjusted_portfolio_equity")]
    public string? AdjustedPortfolioEquity { get; set; }
    public PostTradeCreditInformation() { }

    public PostTradeCreditInformation(Builder builder)
    {
      this.PortfolioId = builder.portfolioId;
      this.Currency = builder.currency;
      this.Limit = builder.limit;
      this.Utilized = builder.utilized;
      this.Available = builder.available;
      this.Frozen = builder.frozen;
      this.FrozenReason = builder.frozenReason;
      this.AmountsDue = builder.amountsDue;
      this.Enabled = builder.enabled;
      this.AdjustedCreditUtilized = builder.adjustedCreditUtilized;
      this.AdjustedPortfolioEquity = builder.adjustedPortfolioEquity;
    }

    public class Builder
    {
#pragma warning disable SA1307, SA1401
      internal string? portfolioId;
      internal string? currency;
      internal string? limit;
      internal string? utilized;
      internal string? available;
      internal bool? frozen;
      internal string? frozenReason;
      internal List<AmountDue>? amountsDue;
      internal bool? enabled;
      internal string? adjustedCreditUtilized;
      internal string? adjustedPortfolioEquity;
#pragma warning restore SA1307, SA1401
      public Builder WithPortfolioId(string? portfolioId)
      {
        this.portfolioId = portfolioId;
        return this;
      }
      public Builder WithCurrency(string? currency)
      {
        this.currency = currency;
        return this;
      }
      public Builder WithLimit(string? limit)
      {
        this.limit = limit;
        return this;
      }
      public Builder WithUtilized(string? utilized)
      {
        this.utilized = utilized;
        return this;
      }
      public Builder WithAvailable(string? available)
      {
        this.available = available;
        return this;
      }
      public Builder WithFrozen(bool? frozen)
      {
        this.frozen = frozen;
        return this;
      }
      public Builder WithFrozenReason(string? frozenReason)
      {
        this.frozenReason = frozenReason;
        return this;
      }
      public Builder WithAmountsDue(List<AmountDue>? amountsDue)
      {
        this.amountsDue = amountsDue;
        return this;
      }
      public Builder WithEnabled(bool? enabled)
      {
        this.enabled = enabled;
        return this;
      }
      public Builder WithAdjustedCreditUtilized(string? adjustedCreditUtilized)
      {
        this.adjustedCreditUtilized = adjustedCreditUtilized;
        return this;
      }
      public Builder WithAdjustedPortfolioEquity(string? adjustedPortfolioEquity)
      {
        this.adjustedPortfolioEquity = adjustedPortfolioEquity;
        return this;
      }
      public PostTradeCreditInformation Build()
      {
        return new PostTradeCreditInformation(this);
      }
    }
  }

}
