/*
 * Copyright 2025-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

namespace CoinbaseSdk.Prime.Model
{
  using CoinbaseSdk.Prime.Model.Enums;
  using CoinbaseSdk.Prime.Model.AmountDue;
  using System.Text.Json.Serialization;

  public class PostTradeCreditInformation
  {
    /// <summary>
    /// The unique ID of the portfolio
    /// </summary>
    [JsonPropertyName("portfolio_id")]
    public string? portfolio_id { get; set; }

    /// <summary>
    /// The currency symbol credit is denoted in
    /// </summary>
    [JsonPropertyName("currency")]
    public string? currency { get; set; }

    /// <summary>
    /// The maximum credit limit
    /// </summary>
    [JsonPropertyName("limit")]
    public string? limit { get; set; }

    /// <summary>
    /// The amount of credit used
    /// </summary>
    [JsonPropertyName("utilized")]
    public string? utilized { get; set; }

    /// <summary>
    /// The amount of credit available
    /// </summary>
    [JsonPropertyName("available")]
    public string? available { get; set; }

    /// <summary>
    /// Whether or not a portfolio is frozen due to balance outstanding or other reason
    /// </summary>
    [JsonPropertyName("frozen")]
    public bool? frozen { get; set; }

    /// <summary>
    /// The reason why the portfolio is frozen
    /// </summary>
    [JsonPropertyName("frozen_reason")]
    public string? frozen_reason { get; set; }

    [JsonPropertyName("amounts_due")]
    public List<AmountDue>? amounts_due { get; set; }

    /// <summary>
    /// Whether the portfolio has credit enabled
    /// </summary>
    [JsonPropertyName("enabled")]
    public bool? enabled { get; set; }

    /// <summary>
    /// The amount of adjusted credit used
    /// </summary>
    [JsonPropertyName("adjusted_credit_utilized")]
    public string? adjusted_credit_utilized { get; set; }

    /// <summary>
    /// The amount of adjusted portfolio equity
    /// </summary>
    [JsonPropertyName("adjusted_portfolio_equity")]
    public string? adjusted_portfolio_equity { get; set; }

    public PostTradeCreditInformation() { }

    public PostTradeCreditInformation(Builder builder)
    {
      this.portfolio_id = builder.portfolio_id;
      this.currency = builder.currency;
      this.limit = builder.limit;
      this.utilized = builder.utilized;
      this.available = builder.available;
      this.frozen = builder.frozen;
      this.frozen_reason = builder.frozen_reason;
      this.amounts_due = builder.amounts_due;
      this.enabled = builder.enabled;
      this.adjusted_credit_utilized = builder.adjusted_credit_utilized;
      this.adjusted_portfolio_equity = builder.adjusted_portfolio_equity;
    }

    public static class Builder
    {
      private string? portfolio_id;

      private string? currency;

      private string? limit;

      private string? utilized;

      private string? available;

      private bool? frozen;

      private string? frozen_reason;

      private List<AmountDue>? amounts_due;

      private bool? enabled;

      private string? adjusted_credit_utilized;

      private string? adjusted_portfolio_equity;

      public Builder portfolio_id(string? portfolio_id)
      {
        this.portfolio_id = portfolio_id;
        return this;
      }

      public Builder currency(string? currency)
      {
        this.currency = currency;
        return this;
      }

      public Builder limit(string? limit)
      {
        this.limit = limit;
        return this;
      }

      public Builder utilized(string? utilized)
      {
        this.utilized = utilized;
        return this;
      }

      public Builder available(string? available)
      {
        this.available = available;
        return this;
      }

      public Builder frozen(bool? frozen)
      {
        this.frozen = frozen;
        return this;
      }

      public Builder frozen_reason(string? frozen_reason)
      {
        this.frozen_reason = frozen_reason;
        return this;
      }

      public Builder amounts_due(List<AmountDue>? amounts_due)
      {
        this.amounts_due = amounts_due;
        return this;
      }

      public Builder enabled(bool? enabled)
      {
        this.enabled = enabled;
        return this;
      }

      public Builder adjusted_credit_utilized(string? adjusted_credit_utilized)
      {
        this.adjusted_credit_utilized = adjusted_credit_utilized;
        return this;
      }

      public Builder adjusted_portfolio_equity(string? adjusted_portfolio_equity)
      {
        this.adjusted_portfolio_equity = adjusted_portfolio_equity;
        return this;
      }

      public PostTradeCreditInformation Build()
      {
        return new PostTradeCreditInformation(this);
      }
    }
  }

}
