// <auto-generated/>
#nullable enable

/*
 * Copyright 2026-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 *  Do not edit the class manually.
 */


namespace CoinbaseSdk.Prime.Model
{
  using System.Text.Json.Serialization;

  public class PrimeXMOffsetCreditBreakdown
  {
    /// <summary>
    /// Basis offset credit component.
    /// </summary>
    [JsonPropertyName("basis_credit")]
    public string? BasisCredit { get; set; }
    /// <summary>
    /// Long/short tier-pair offset credit.
    /// </summary>
    [JsonPropertyName("long_short_credit")]
    public string? LongShortCredit { get; set; }
    /// <summary>
    /// Long/long tier-pair offset credit.
    /// </summary>
    [JsonPropertyName("long_long_credit")]
    public string? LongLongCredit { get; set; }
    /// <summary>
    /// Short/short tier-pair offset credit.
    /// </summary>
    [JsonPropertyName("short_short_credit")]
    public string? ShortShortCredit { get; set; }
    /// <summary>
    /// Same-tier offset credit.
    /// </summary>
    [JsonPropertyName("same_tier_credit")]
    public string? SameTierCredit { get; set; }
    /// <summary>
    /// Total offset credit.
    /// </summary>
    [JsonPropertyName("total_credit")]
    public string? TotalCredit { get; set; }
    public PrimeXMOffsetCreditBreakdown() { }

    public PrimeXMOffsetCreditBreakdown(Builder builder)
    {
      this.BasisCredit = builder.basisCredit;
      this.LongShortCredit = builder.longShortCredit;
      this.LongLongCredit = builder.longLongCredit;
      this.ShortShortCredit = builder.shortShortCredit;
      this.SameTierCredit = builder.sameTierCredit;
      this.TotalCredit = builder.totalCredit;
    }

    public class Builder
    {
#pragma warning disable SA1307, SA1401
      internal string? basisCredit;
      internal string? longShortCredit;
      internal string? longLongCredit;
      internal string? shortShortCredit;
      internal string? sameTierCredit;
      internal string? totalCredit;
#pragma warning restore SA1307, SA1401
      public Builder WithBasisCredit(string? basisCredit)
      {
        this.basisCredit = basisCredit;
        return this;
      }
      public Builder WithLongShortCredit(string? longShortCredit)
      {
        this.longShortCredit = longShortCredit;
        return this;
      }
      public Builder WithLongLongCredit(string? longLongCredit)
      {
        this.longLongCredit = longLongCredit;
        return this;
      }
      public Builder WithShortShortCredit(string? shortShortCredit)
      {
        this.shortShortCredit = shortShortCredit;
        return this;
      }
      public Builder WithSameTierCredit(string? sameTierCredit)
      {
        this.sameTierCredit = sameTierCredit;
        return this;
      }
      public Builder WithTotalCredit(string? totalCredit)
      {
        this.totalCredit = totalCredit;
        return this;
      }
      public PrimeXMOffsetCreditBreakdown Build()
      {
        return new PrimeXMOffsetCreditBreakdown(this);
      }
    }
  }

}
