// <auto-generated/>
#nullable enable

/*
 * Copyright 2026-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 *  Do not edit the class manually.
 */


namespace CoinbaseSdk.Prime.Model
{
  using CoinbaseSdk.Prime.Model.Enums;

  public class PrimeXMMarginThreshold
  {
    /// <summary>
    /// - HEALTHY_THRESHOLD: Margin level is healthy.
    /// - DEFICIT_THRESHOLD: Margin level is breaching the deficit threshold (DT) which will result in the issuance of a Margin Call if this is still the case by the scheduled next Margin Call time (as defined in the margin methodology).
    /// - WARNING_THRESHOLD: Margin level is breaching the warning threshold (WT) which will result in the issuance of a Margin Call if this is still the case by the scheduled next Margin Call (as defined in the margin methodology). WT is differentiated from DT in that it means margin health is approaching the UMCT.
    /// - URGENT_MARGIN_CALL_THRESHOLD: Margin level is breaching the UMCT and, as defined in the margin methodology, this will trigger an urgent margin call.
    /// - LIQUIDATION_THRESHOLD: Margin level is breaching the liquidation threshold (LT) and, as defined in the margin methodology, this will trigger the SESSION_LOCKED control status and liquidation may commence.
    /// </summary>
    public XmMarginLevel? MarginLevel { get; set; }
    /// <summary>
    /// - MARGIN_THRESHOLD_EQUITY_RATIO: Threshold based on equity ratio EQ / MR; triggers when EQ / MR &gt;= threshold_value.
    /// - MARGIN_THRESHOLD_DEFICIT_RATIO: Threshold based on deficit ratio (MR - EQ) / XMML; triggers when (MR - EQ) / XMML &gt; threshold_value.
    /// </summary>
    public PrimeXMMarginThresholdType? ThresholdType { get; set; }
    public string? ThresholdValue { get; set; }
    public PrimeXMMarginThreshold() { }

    public PrimeXMMarginThreshold(Builder builder)
    {
      this.MarginLevel = builder.marginLevel;
      this.ThresholdType = builder.thresholdType;
      this.ThresholdValue = builder.thresholdValue;
    }

    public class Builder
    {
#pragma warning disable SA1307, SA1401
      internal XmMarginLevel? marginLevel;
      internal PrimeXMMarginThresholdType? thresholdType;
      internal string? thresholdValue;
#pragma warning restore SA1307, SA1401
      public Builder WithMarginLevel(XmMarginLevel? marginLevel)
      {
        this.marginLevel = marginLevel;
        return this;
      }
      public Builder WithThresholdType(PrimeXMMarginThresholdType? thresholdType)
      {
        this.thresholdType = thresholdType;
        return this;
      }
      public Builder WithThresholdValue(string? thresholdValue)
      {
        this.thresholdValue = thresholdValue;
        return this;
      }
      public PrimeXMMarginThreshold Build()
      {
        return new PrimeXMMarginThreshold(this);
      }
    }
  }

}
