// <auto-generated/>
#nullable enable

/*
 * Copyright 2026-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 *  Do not edit the class manually.
 */


namespace CoinbaseSdk.Prime.Model
{

  public class PrimeXMMarginRequirementBreakdown
  {
    /// <summary>
    /// Base margin requirement component.
    /// </summary>
    public string? BaseMargin { get; set; }
    /// <summary>
    /// Volatility add-on component.
    /// </summary>
    public string? VolatilityAddon { get; set; }
    /// <summary>
    /// Liquidity add-on component.
    /// </summary>
    public string? LiquidityAddon { get; set; }
    /// <summary>
    /// Credits that offset margin charges due to portfolio composition.
    /// </summary>
    public string? OffsetCredit { get; set; }
    /// <summary>
    /// Futures margin charge applied for any futures trades of the opposing direction but of the same underlying.
    /// </summary>
    public string? FuturesMargin { get; set; }
    public PrimeXMMarginRequirementBreakdown() { }

    public PrimeXMMarginRequirementBreakdown(Builder builder)
    {
      this.BaseMargin = builder.baseMargin;
      this.VolatilityAddon = builder.volatilityAddon;
      this.LiquidityAddon = builder.liquidityAddon;
      this.OffsetCredit = builder.offsetCredit;
      this.FuturesMargin = builder.futuresMargin;
    }

    public class Builder
    {
#pragma warning disable SA1307, SA1401
      internal string? baseMargin;
      internal string? volatilityAddon;
      internal string? liquidityAddon;
      internal string? offsetCredit;
      internal string? futuresMargin;
#pragma warning restore SA1307, SA1401
      public Builder WithBaseMargin(string? baseMargin)
      {
        this.baseMargin = baseMargin;
        return this;
      }
      public Builder WithVolatilityAddon(string? volatilityAddon)
      {
        this.volatilityAddon = volatilityAddon;
        return this;
      }
      public Builder WithLiquidityAddon(string? liquidityAddon)
      {
        this.liquidityAddon = liquidityAddon;
        return this;
      }
      public Builder WithOffsetCredit(string? offsetCredit)
      {
        this.offsetCredit = offsetCredit;
        return this;
      }
      public Builder WithFuturesMargin(string? futuresMargin)
      {
        this.futuresMargin = futuresMargin;
        return this;
      }
      public PrimeXMMarginRequirementBreakdown Build()
      {
        return new PrimeXMMarginRequirementBreakdown(this);
      }
    }
  }

}
