// <auto-generated/>
#nullable enable

/*
 * Copyright 2026-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 *  Do not edit the class manually.
 */


namespace CoinbaseSdk.Prime.Model
{
  using CoinbaseSdk.Prime.Model.Enums;
  /// <summary>
  /// Represents the status of various process requirements for a transaction.
  /// </summary>

  public class ProcessRequirements
  {
    /// <summary>
    /// Travel rule compliance status for a transaction.
    /// </summary>
    public TravelRuleStatus? TravelRuleStatus { get; set; }
    public ProcessRequirements() { }

    public ProcessRequirements(Builder builder)
    {
      this.TravelRuleStatus = builder.travelRuleStatus;
    }

    public class Builder
    {
#pragma warning disable SA1307, SA1401
      internal TravelRuleStatus? travelRuleStatus;
#pragma warning restore SA1307, SA1401
      public Builder WithTravelRuleStatus(TravelRuleStatus? travelRuleStatus)
      {
        this.travelRuleStatus = travelRuleStatus;
        return this;
      }
      public ProcessRequirements Build()
      {
        return new ProcessRequirements(this);
      }
    }
  }

}
