/*
 * Copyright 2025-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

namespace CoinbaseSdk.Prime.Model
{
  using CoinbaseSdk.Prime.Model.Enums;
  using CoinbaseSdk.Prime.Model.ProductPermissions;
  using CoinbaseSdk.Prime.Model.RFQProductDetails;
  using System.Text.Json.Serialization;

  public class Product
  {
    /// <summary>
    /// The product ID, written as &#x60;BASE-QUOTE&#x60;
    /// </summary>
    [JsonPropertyName("id")]
    public string? id { get; set; }

    /// <summary>
    /// The smallest permitted unit of denomination for the base asset (varies by product)
    /// </summary>
    [JsonPropertyName("base_increment")]
    public string? base_increment { get; set; }

    /// <summary>
    /// The smallest permitted unit of denomination for the quote asset (varies by product)
    /// </summary>
    [JsonPropertyName("quote_increment")]
    public string? quote_increment { get; set; }

    /// <summary>
    /// The minimum size (in base asset units) for which an order can be placed
    /// </summary>
    [JsonPropertyName("base_min_size")]
    public string? base_min_size { get; set; }

    /// <summary>
    /// The minimum size (in quote asset units) for which an order can be placed
    /// </summary>
    [JsonPropertyName("quote_min_size")]
    public string? quote_min_size { get; set; }

    /// <summary>
    /// The maximum size (in base asset units) for which an order can be placed
    /// </summary>
    [JsonPropertyName("base_max_size")]
    public string? base_max_size { get; set; }

    /// <summary>
    /// The maximum size (in quote asset units) for which an order can be placed
    /// </summary>
    [JsonPropertyName("quote_max_size")]
    public string? quote_max_size { get; set; }

    /// <summary>
    /// Permissions given to the user for a product
    /// </summary>
    [JsonPropertyName("permissions")]
    public List<ProductPermissions>? permissions { get; set; }

    /// <summary>
    /// The smallest permitted price increment for the product
    /// </summary>
    [JsonPropertyName("price_increment")]
    public string? price_increment { get; set; }

    [JsonPropertyName("rfq_product_details")]
    public RFQProductDetails? rfq_product_details { get; set; }

    public Product() { }

    public Product(Builder builder)
    {
      this.id = builder.id;
      this.base_increment = builder.base_increment;
      this.quote_increment = builder.quote_increment;
      this.base_min_size = builder.base_min_size;
      this.quote_min_size = builder.quote_min_size;
      this.base_max_size = builder.base_max_size;
      this.quote_max_size = builder.quote_max_size;
      this.permissions = builder.permissions;
      this.price_increment = builder.price_increment;
      this.rfq_product_details = builder.rfq_product_details;
    }

    public class Builder
    {
      private string? id;

      private string? base_increment;

      private string? quote_increment;

      private string? base_min_size;

      private string? quote_min_size;

      private string? base_max_size;

      private string? quote_max_size;

      private List<ProductPermissions>? permissions;

      private string? price_increment;

      private RFQProductDetails? rfq_product_details;

      public Builder Withid(string? id)
      {
        this.id = id;
        return this;
      }

      public Builder Withbase_increment(string? base_increment)
      {
        this.base_increment = base_increment;
        return this;
      }

      public Builder Withquote_increment(string? quote_increment)
      {
        this.quote_increment = quote_increment;
        return this;
      }

      public Builder Withbase_min_size(string? base_min_size)
      {
        this.base_min_size = base_min_size;
        return this;
      }

      public Builder Withquote_min_size(string? quote_min_size)
      {
        this.quote_min_size = quote_min_size;
        return this;
      }

      public Builder Withbase_max_size(string? base_max_size)
      {
        this.base_max_size = base_max_size;
        return this;
      }

      public Builder Withquote_max_size(string? quote_max_size)
      {
        this.quote_max_size = quote_max_size;
        return this;
      }

      public Builder Withpermissions(List<ProductPermissions>? permissions)
      {
        this.permissions = permissions;
        return this;
      }

      public Builder Withprice_increment(string? price_increment)
      {
        this.price_increment = price_increment;
        return this;
      }

      public Builder Withrfq_product_details(RFQProductDetails? rfq_product_details)
      {
        this.rfq_product_details = rfq_product_details;
        return this;
      }

      public Product Build()
      {
        return new Product(this);
      }
    }
  }

}
