// <auto-generated/>
#nullable enable

/*
 * Copyright 2026-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 *  Do not edit the class manually.
 */


namespace CoinbaseSdk.Prime.Model
{

  public class RequestToSubmitTravelRuleDataForAnExistingDepositTransaction
  {
    public TravelRuleParty? Originator { get; set; }
    public TravelRuleParty? Beneficiary { get; set; }
    public bool? IsSelf { get; set; }
    public bool? OptOutOfOwnershipVerification { get; set; }
    public RequestToSubmitTravelRuleDataForAnExistingDepositTransaction() { }

    public RequestToSubmitTravelRuleDataForAnExistingDepositTransaction(Builder builder)
    {
      this.Originator = builder.originator;
      this.Beneficiary = builder.beneficiary;
      this.IsSelf = builder.isSelf;
      this.OptOutOfOwnershipVerification = builder.optOutOfOwnershipVerification;
    }

    public class Builder
    {
#pragma warning disable SA1307, SA1401
      internal TravelRuleParty? originator;
      internal TravelRuleParty? beneficiary;
      internal bool? isSelf;
      internal bool? optOutOfOwnershipVerification;
#pragma warning restore SA1307, SA1401
      public Builder WithOriginator(TravelRuleParty? originator)
      {
        this.originator = originator;
        return this;
      }
      public Builder WithBeneficiary(TravelRuleParty? beneficiary)
      {
        this.beneficiary = beneficiary;
        return this;
      }
      public Builder WithIsSelf(bool? isSelf)
      {
        this.isSelf = isSelf;
        return this;
      }
      public Builder WithOptOutOfOwnershipVerification(bool? optOutOfOwnershipVerification)
      {
        this.optOutOfOwnershipVerification = optOutOfOwnershipVerification;
        return this;
      }
      public RequestToSubmitTravelRuleDataForAnExistingDepositTransaction Build()
      {
        return new RequestToSubmitTravelRuleDataForAnExistingDepositTransaction(this);
      }
    }
  }

}
