/*
 * Copyright 2025-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

namespace CoinbaseSdk.Prime.Model
{
  using CoinbaseSdk.Prime.Model.Enums;
  using System.Text.Json.Serialization;

  public class RFQ
  {
    [JsonPropertyName("product_id")]
    public string product_id { get; set; }

    [JsonPropertyName("side")]
    public OrderSide side { get; set; }

    /// <summary>
    /// A client-generated order ID used for reference purposes (note: order will be rejected if this ID is not unique among all currently active orders)
    /// </summary>
    [JsonPropertyName("client_quote_id")]
    public string client_quote_id { get; set; }

    [JsonPropertyName("base_quantity")]
    public string? base_quantity { get; set; }

    [JsonPropertyName("quote_value")]
    public string? quote_value { get; set; }

    [JsonPropertyName("limit_price")]
    public string limit_price { get; set; }

    [JsonPropertyName("settl_currency")]
    public string? settl_currency { get; set; }

    public RFQ() { }

    public RFQ(Builder builder)
    {
      this.product_id = builder.product_id;
      this.side = builder.side;
      this.client_quote_id = builder.client_quote_id;
      this.base_quantity = builder.base_quantity;
      this.quote_value = builder.quote_value;
      this.limit_price = builder.limit_price;
      this.settl_currency = builder.settl_currency;
    }

    public class Builder
    {
      private string product_id;

      private OrderSide side;

      private string client_quote_id;

      private string? base_quantity;

      private string? quote_value;

      private string limit_price;

      private string? settl_currency;

      public Builder Withproduct_id(string product_id)
      {
        this.product_id = product_id;
        return this;
      }

      public Builder Withside(OrderSide side)
      {
        this.side = side;
        return this;
      }

      public Builder Withclient_quote_id(string client_quote_id)
      {
        this.client_quote_id = client_quote_id;
        return this;
      }

      public Builder Withbase_quantity(string? base_quantity)
      {
        this.base_quantity = base_quantity;
        return this;
      }

      public Builder Withquote_value(string? quote_value)
      {
        this.quote_value = quote_value;
        return this;
      }

      public Builder Withlimit_price(string limit_price)
      {
        this.limit_price = limit_price;
        return this;
      }

      public Builder Withsettl_currency(string? settl_currency)
      {
        this.settl_currency = settl_currency;
        return this;
      }

      public RFQ Build()
      {
        return new RFQ(this);
      }
    }
  }

}
