// <auto-generated/>
#nullable enable

/*
 * Copyright 2025-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */


namespace CoinbaseSdk.Prime.Model
{
  using System.Text.Json.Serialization;

  public class RfqProductDetails
  {
    /// <summary>
    /// Whether the product is tradable via RFQ
    /// </summary>
    [JsonPropertyName("tradable")]
    public bool? Tradable { get; set; }
    /// <summary>
    /// Deprecated: Value will be an empty string
    /// </summary>
    [JsonPropertyName("min_notional_size")]
    public string? MinNotionalSize { get; set; }
    /// <summary>
    /// Deprecated: Value will be an empty string
    /// </summary>
    [JsonPropertyName("max_notional_size")]
    public string? MaxNotionalSize { get; set; }
    /// <summary>
    /// Minimum base size for RFQ
    /// </summary>
    [JsonPropertyName("min_base_size")]
    public string? MinBaseSize { get; set; }
    /// <summary>
    /// Maximum base size for RFQ
    /// </summary>
    [JsonPropertyName("max_base_size")]
    public string? MaxBaseSize { get; set; }
    /// <summary>
    /// Minimum quote size for RFQ
    /// </summary>
    [JsonPropertyName("min_quote_size")]
    public string? MinQuoteSize { get; set; }
    /// <summary>
    /// Maximum quote size for RFQ
    /// </summary>
    [JsonPropertyName("max_quote_size")]
    public string? MaxQuoteSize { get; set; }
    public RfqProductDetails() { }

    public RfqProductDetails(Builder builder)
    {
      this.Tradable = builder.tradable;
      this.MinNotionalSize = builder.minNotionalSize;
      this.MaxNotionalSize = builder.maxNotionalSize;
      this.MinBaseSize = builder.minBaseSize;
      this.MaxBaseSize = builder.maxBaseSize;
      this.MinQuoteSize = builder.minQuoteSize;
      this.MaxQuoteSize = builder.maxQuoteSize;
    }

    public class Builder
    {
#pragma warning disable SA1307, SA1401
      internal bool? tradable;
      internal string? minNotionalSize;
      internal string? maxNotionalSize;
      internal string? minBaseSize;
      internal string? maxBaseSize;
      internal string? minQuoteSize;
      internal string? maxQuoteSize;
#pragma warning restore SA1307, SA1401
      public Builder WithTradable(bool? tradable)
      {
        this.tradable = tradable;
        return this;
      }
      public Builder WithMinNotionalSize(string? minNotionalSize)
      {
        this.minNotionalSize = minNotionalSize;
        return this;
      }
      public Builder WithMaxNotionalSize(string? maxNotionalSize)
      {
        this.maxNotionalSize = maxNotionalSize;
        return this;
      }
      public Builder WithMinBaseSize(string? minBaseSize)
      {
        this.minBaseSize = minBaseSize;
        return this;
      }
      public Builder WithMaxBaseSize(string? maxBaseSize)
      {
        this.maxBaseSize = maxBaseSize;
        return this;
      }
      public Builder WithMinQuoteSize(string? minQuoteSize)
      {
        this.minQuoteSize = minQuoteSize;
        return this;
      }
      public Builder WithMaxQuoteSize(string? maxQuoteSize)
      {
        this.maxQuoteSize = maxQuoteSize;
        return this;
      }
      public RfqProductDetails Build()
      {
        return new RfqProductDetails(this);
      }
    }
  }

}
