// <auto-generated/>
#nullable enable

/*
 * Copyright 2025-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */


namespace CoinbaseSdk.Prime.Model
{
  using System.Text.Json.Serialization;

  public class RpcConfig
  {
    /// <summary>
    /// If true, transaction will not be broadcast to the network
    /// </summary>
    [JsonPropertyName("skip_broadcast")]
    public bool? SkipBroadcast { get; set; }
    /// <summary>
    /// Custom blockchain node RpcConfig URL. (EVM-only)
    /// </summary>
    [JsonPropertyName("url")]
    public string? Url { get; set; }
    public RpcConfig() { }

    public RpcConfig(Builder builder)
    {
      this.SkipBroadcast = builder.skipBroadcast;
      this.Url = builder.url;
    }

    public class Builder
    {
#pragma warning disable SA1307, SA1401
      internal bool? skipBroadcast;
      internal string? url;
#pragma warning restore SA1307, SA1401
      public Builder WithSkipBroadcast(bool? skipBroadcast)
      {
        this.skipBroadcast = skipBroadcast;
        return this;
      }
      public Builder WithUrl(string? url)
      {
        this.url = url;
        return this;
      }
      public RpcConfig Build()
      {
        return new RpcConfig(this);
      }
    }
  }

}
