/*
 * Copyright 2025-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

namespace CoinbaseSdk.Prime.Model
{
  using CoinbaseSdk.Prime.Model.Enums;
  using System.Text.Json.Serialization;

  public class ShortCollateral
  {
    /// <summary>
    /// Existing short collateral balance
    /// </summary>
    [JsonPropertyName("old_balance")]
    public string? old_balance { get; set; }

    /// <summary>
    /// New short collateral balance required
    /// </summary>
    [JsonPropertyName("new_balance")]
    public string? new_balance { get; set; }

    /// <summary>
    /// Loan interest rate
    /// </summary>
    [JsonPropertyName("loan_interest_rate")]
    public string? loan_interest_rate { get; set; }

    /// <summary>
    /// Collateral interest rate
    /// </summary>
    [JsonPropertyName("collateral_interest_rate")]
    public string? collateral_interest_rate { get; set; }

    public ShortCollateral() { }

    public ShortCollateral(Builder builder)
    {
      this.old_balance = builder.old_balance;
      this.new_balance = builder.new_balance;
      this.loan_interest_rate = builder.loan_interest_rate;
      this.collateral_interest_rate = builder.collateral_interest_rate;
    }

    public static class Builder
    {
      private string? old_balance;

      private string? new_balance;

      private string? loan_interest_rate;

      private string? collateral_interest_rate;

      public Builder old_balance(string? old_balance)
      {
        this.old_balance = old_balance;
        return this;
      }

      public Builder new_balance(string? new_balance)
      {
        this.new_balance = new_balance;
        return this;
      }

      public Builder loan_interest_rate(string? loan_interest_rate)
      {
        this.loan_interest_rate = loan_interest_rate;
        return this;
      }

      public Builder collateral_interest_rate(string? collateral_interest_rate)
      {
        this.collateral_interest_rate = collateral_interest_rate;
        return this;
      }

      public ShortCollateral Build()
      {
        return new ShortCollateral(this);
      }
    }
  }

}
