// <auto-generated/>
#nullable enable

/*
 * Copyright 2025-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */


namespace CoinbaseSdk.Prime.Model
{
  using System.Text.Json.Serialization;

  public class ShortCollateral
  {
    /// <summary>
    /// Existing short collateral balance
    /// </summary>
    [JsonPropertyName("old_balance")]
    public string? OldBalance { get; set; }
    /// <summary>
    /// New short collateral balance required
    /// </summary>
    [JsonPropertyName("new_balance")]
    public string? NewBalance { get; set; }
    /// <summary>
    /// Loan interest rate
    /// </summary>
    [JsonPropertyName("loan_interest_rate")]
    public string? LoanInterestRate { get; set; }
    /// <summary>
    /// Collateral interest rate
    /// </summary>
    [JsonPropertyName("collateral_interest_rate")]
    public string? CollateralInterestRate { get; set; }
    public ShortCollateral() { }

    public ShortCollateral(Builder builder)
    {
      this.OldBalance = builder.oldBalance;
      this.NewBalance = builder.newBalance;
      this.LoanInterestRate = builder.loanInterestRate;
      this.CollateralInterestRate = builder.collateralInterestRate;
    }

    public class Builder
    {
#pragma warning disable SA1307, SA1401
      internal string? oldBalance;
      internal string? newBalance;
      internal string? loanInterestRate;
      internal string? collateralInterestRate;
#pragma warning restore SA1307, SA1401
      public Builder WithOldBalance(string? oldBalance)
      {
        this.oldBalance = oldBalance;
        return this;
      }
      public Builder WithNewBalance(string? newBalance)
      {
        this.newBalance = newBalance;
        return this;
      }
      public Builder WithLoanInterestRate(string? loanInterestRate)
      {
        this.loanInterestRate = loanInterestRate;
        return this;
      }
      public Builder WithCollateralInterestRate(string? collateralInterestRate)
      {
        this.collateralInterestRate = collateralInterestRate;
        return this;
      }
      public ShortCollateral Build()
      {
        return new ShortCollateral(this);
      }
    }
  }

}
