// <auto-generated/>
#nullable enable

/*
 * Copyright 2026-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 *  Do not edit the class manually.
 */


namespace CoinbaseSdk.Prime.Model
{
  using CoinbaseSdk.Prime.Model.Enums;

  public class StakingStatus
  {
    /// <summary>
    /// Amount being staked (whole amount, e.g., 16 ETH)
    /// </summary>
    public string Amount { get; set; } = default!;
    public StakeType StakeType { get; set; } = default!;
    /// <summary>
    /// Estimated date when staking will complete (ISO 8601 format)
    /// </summary>
    public DateTime EstimatedStakeDate { get; set; } = default!;
    /// <summary>
    /// Estimated hours until this staking request completes
    /// </summary>
    public long EstimatedHoursToStake { get; set; } = default!;
    /// <summary>
    /// Timestamp when the stake request was originally created
    /// </summary>
    public DateTime? RequestedAt { get; set; }
    public StakingStatus() { }

    public StakingStatus(Builder builder)
    {
      this.Amount = builder.amount;
      this.StakeType = builder.stakeType;
      this.EstimatedStakeDate = builder.estimatedStakeDate;
      this.EstimatedHoursToStake = builder.estimatedHoursToStake;
      this.RequestedAt = builder.requestedAt;
    }

    public class Builder
    {
#pragma warning disable SA1307, SA1401
      internal string amount = default!;
      internal StakeType stakeType = default!;
      internal DateTime estimatedStakeDate = default!;
      internal long estimatedHoursToStake = default!;
      internal DateTime? requestedAt;
#pragma warning restore SA1307, SA1401
      public Builder WithAmount(string amount)
      {
        this.amount = amount;
        return this;
      }
      public Builder WithStakeType(StakeType stakeType)
      {
        this.stakeType = stakeType;
        return this;
      }
      public Builder WithEstimatedStakeDate(DateTime estimatedStakeDate)
      {
        this.estimatedStakeDate = estimatedStakeDate;
        return this;
      }
      public Builder WithEstimatedHoursToStake(long estimatedHoursToStake)
      {
        this.estimatedHoursToStake = estimatedHoursToStake;
        return this;
      }
      public Builder WithRequestedAt(DateTime? requestedAt)
      {
        this.requestedAt = requestedAt;
        return this;
      }
      public StakingStatus Build()
      {
        return new StakingStatus(this);
      }
    }
  }

}
