// <auto-generated/>
#nullable enable

/*
 * Copyright 2025-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */


namespace CoinbaseSdk.Prime.Model
{
  using System.Text.Json.Serialization;

  public class TieredPricingFee
  {
    /// <summary>
    /// Asset symbol
    /// </summary>
    [JsonPropertyName("symbol")]
    public string? Symbol { get; set; }
    /// <summary>
    /// The fee in bps
    /// </summary>
    [JsonPropertyName("fee")]
    public string? Fee { get; set; }
    public TieredPricingFee() { }

    public TieredPricingFee(Builder builder)
    {
      this.Symbol = builder.symbol;
      this.Fee = builder.fee;
    }

    public class Builder
    {
#pragma warning disable SA1307, SA1401
      internal string? symbol;
      internal string? fee;
#pragma warning restore SA1307, SA1401
      public Builder WithSymbol(string? symbol)
      {
        this.symbol = symbol;
        return this;
      }
      public Builder WithFee(string? fee)
      {
        this.fee = fee;
        return this;
      }
      public TieredPricingFee Build()
      {
        return new TieredPricingFee(this);
      }
    }
  }

}
