/*
 * Copyright 2025-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

namespace CoinbaseSdk.Prime.Model
{
  using CoinbaseSdk.Prime.Model.Enums;
  using CoinbaseSdk.Prime.Model.TransferLocationType;
  using System.Text.Json.Serialization;

  public class TransferLocation
  {
    [JsonPropertyName("type")]
    public TransferLocationType? type { get; set; }

    /// <summary>
    /// The value of the transfer location: payment method ID, wallet ID or crypto address
    /// </summary>
    [JsonPropertyName("value")]
    public string? value { get; set; }

    /// <summary>
    /// The crypto address of the transfer location
    /// </summary>
    [JsonPropertyName("address")]
    public string? address { get; set; }

    /// <summary>
    /// The tag/memo of the address, if applicable - - required for certain assets (e.g. XRP, XLM, etc.)
    /// </summary>
    [JsonPropertyName("account_identifier")]
    public string? account_identifier { get; set; }

    public TransferLocation() { }

    public TransferLocation(Builder builder)
    {
      this.type = builder.type;
      this.value = builder.value;
      this.address = builder.address;
      this.account_identifier = builder.account_identifier;
    }

    public static class Builder
    {
      private TransferLocationType? type;

      private string? value;

      private string? address;

      private string? account_identifier;

      public Builder type(TransferLocationType? type)
      {
        this.type = type;
        return this;
      }

      public Builder value(string? value)
      {
        this.value = value;
        return this;
      }

      public Builder address(string? address)
      {
        this.address = address;
        return this;
      }

      public Builder account_identifier(string? account_identifier)
      {
        this.account_identifier = account_identifier;
        return this;
      }

      public TransferLocation Build()
      {
        return new TransferLocation(this);
      }
    }
  }

}
