// <auto-generated/>
#nullable enable

/*
 * Copyright 2025-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */


namespace CoinbaseSdk.Prime.Model
{
  using System.Text.Json.Serialization;
  using CoinbaseSdk.Prime.Model.Enums;

  public class TransferLocation
  {
    [JsonPropertyName("type")]
    public TransferLocationType? Type { get; set; }
    /// <summary>
    /// The value of the transfer location: payment method ID, wallet ID or crypto address
    /// </summary>
    [JsonPropertyName("value")]
    public string? Value { get; set; }
    /// <summary>
    /// The crypto address of the transfer location
    /// </summary>
    [JsonPropertyName("address")]
    public string? Address { get; set; }
    /// <summary>
    /// The tag/memo of the address, if applicable - - required for certain assets (e.g. XRP, XLM, etc.)
    /// </summary>
    [JsonPropertyName("account_identifier")]
    public string? AccountIdentifier { get; set; }
    public TransferLocation() { }

    public TransferLocation(Builder builder)
    {
      this.Type = builder.type;
      this.Value = builder.value;
      this.Address = builder.address;
      this.AccountIdentifier = builder.accountIdentifier;
    }

    public class Builder
    {
#pragma warning disable SA1307, SA1401
      internal TransferLocationType? type;
      internal string? value;
      internal string? address;
      internal string? accountIdentifier;
#pragma warning restore SA1307, SA1401
      public Builder WithType(TransferLocationType? type)
      {
        this.type = type;
        return this;
      }
      public Builder WithValue(string? value)
      {
        this.value = value;
        return this;
      }
      public Builder WithAddress(string? address)
      {
        this.address = address;
        return this;
      }
      public Builder WithAccountIdentifier(string? accountIdentifier)
      {
        this.accountIdentifier = accountIdentifier;
        return this;
      }
      public TransferLocation Build()
      {
        return new TransferLocation(this);
      }
    }
  }

}
