// <auto-generated/>
#nullable enable

/*
 * Copyright 2025-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */


namespace CoinbaseSdk.Prime.Model
{
  using System.Text.Json.Serialization;
  using CoinbaseSdk.Prime.Model.Enums;

  public class Transaction
  {
    /// <summary>
    /// The ID of the transaction
    /// </summary>
    [JsonPropertyName("id")]
    public string? Id { get; set; }
    /// <summary>
    /// The wallet ID of the transaction
    /// </summary>
    [JsonPropertyName("wallet_id")]
    public string? WalletId { get; set; }
    /// <summary>
    /// The portfolio ID of the transaction
    /// </summary>
    [JsonPropertyName("portfolio_id")]
    public string? PortfolioId { get; set; }
    [JsonPropertyName("type")]
    public TransactionType? Type { get; set; }
    [JsonPropertyName("status")]
    public TransactionStatus? Status { get; set; }
    /// <summary>
    /// The asset symbol
    /// </summary>
    [JsonPropertyName("symbol")]
    public string? Symbol { get; set; }
    /// <summary>
    /// The transaction creation time (as a UTC timestamp)
    /// </summary>
    [JsonPropertyName("created_at")]
    public DateTime? CreatedAt { get; set; }
    /// <summary>
    /// The transaction completion time (as a UTC timestamp)
    /// </summary>
    [JsonPropertyName("completed_at")]
    public DateTime? CompletedAt { get; set; }
    /// <summary>
    /// The transaction amount in whole units
    /// </summary>
    [JsonPropertyName("amount")]
    public string? Amount { get; set; }
    [JsonPropertyName("transfer_from")]
    public TransferLocation? TransferFrom { get; set; }
    [JsonPropertyName("transfer_to")]
    public TransferLocation? TransferTo { get; set; }
    /// <summary>
    /// The blockchain network fees (in whole units) required in order to broadcast the transaction
    /// </summary>
    [JsonPropertyName("network_fees")]
    public string? NetworkFees { get; set; }
    /// <summary>
    /// The fees that the customer paid for the transaction (in whole units)
    /// </summary>
    [JsonPropertyName("fees")]
    public string? Fees { get; set; }
    /// <summary>
    /// The asset in which fees will be paid
    /// </summary>
    [JsonPropertyName("fee_symbol")]
    public string? FeeSymbol { get; set; }
    /// <summary>
    /// The cryptocurrency network transaction hashes/IDs generated upon broadcast
    /// </summary>
    [JsonPropertyName("blockchain_ids")]
    public List<string>? BlockchainIds { get; set; }
    /// <summary>
    /// The 8 character alphanumeric short form id for the transaction
    /// </summary>
    [JsonPropertyName("transaction_id")]
    public string? TransactionId { get; set; }
    /// <summary>
    /// The destination asset symbol
    /// </summary>
    [JsonPropertyName("destination_symbol")]
    public string? DestinationSymbol { get; set; }
    [JsonPropertyName("estimated_network_fees")]
    public EstimatedNetworkFees? EstimatedNetworkFees { get; set; }
    /// <summary>
    /// The network name specific to onchain/onchain wallet transactions
    /// </summary>
    [JsonPropertyName("network")]
    public string? Network { get; set; }
    /// <summary>
    /// The estimated asset changes (onchain)
    /// </summary>
    [JsonPropertyName("estimated_asset_changes")]
    public List<AssetChange>? EstimatedAssetChanges { get; set; }
    [JsonPropertyName("metadata")]
    public TransactionMetadata? Metadata { get; set; }
    /// <summary>
    /// The idempotency key associated with the transaction creation request
    /// </summary>
    [JsonPropertyName("idempotency_key")]
    public string? IdempotencyKey { get; set; }
    [JsonPropertyName("onchain_details")]
    public OnchainTransactionDetails? OnchainDetails { get; set; }
    [JsonPropertyName("network_info")]
    public Network? NetworkInfo { get; set; }
    public Transaction() { }

    public Transaction(Builder builder)
    {
      this.Id = builder.id;
      this.WalletId = builder.walletId;
      this.PortfolioId = builder.portfolioId;
      this.Type = builder.type;
      this.Status = builder.status;
      this.Symbol = builder.symbol;
      this.CreatedAt = builder.createdAt;
      this.CompletedAt = builder.completedAt;
      this.Amount = builder.amount;
      this.TransferFrom = builder.transferFrom;
      this.TransferTo = builder.transferTo;
      this.NetworkFees = builder.networkFees;
      this.Fees = builder.fees;
      this.FeeSymbol = builder.feeSymbol;
      this.BlockchainIds = builder.blockchainIds;
      this.TransactionId = builder.transactionId;
      this.DestinationSymbol = builder.destinationSymbol;
      this.EstimatedNetworkFees = builder.estimatedNetworkFees;
      this.Network = builder.network;
      this.EstimatedAssetChanges = builder.estimatedAssetChanges;
      this.Metadata = builder.metadata;
      this.IdempotencyKey = builder.idempotencyKey;
      this.OnchainDetails = builder.onchainDetails;
      this.NetworkInfo = builder.networkInfo;
    }

    public class Builder
    {
#pragma warning disable SA1307, SA1401
      internal string? id;
      internal string? walletId;
      internal string? portfolioId;
      internal TransactionType? type;
      internal TransactionStatus? status;
      internal string? symbol;
      internal DateTime? createdAt;
      internal DateTime? completedAt;
      internal string? amount;
      internal TransferLocation? transferFrom;
      internal TransferLocation? transferTo;
      internal string? networkFees;
      internal string? fees;
      internal string? feeSymbol;
      internal List<string>? blockchainIds;
      internal string? transactionId;
      internal string? destinationSymbol;
      internal EstimatedNetworkFees? estimatedNetworkFees;
      internal string? network;
      internal List<AssetChange>? estimatedAssetChanges;
      internal TransactionMetadata? metadata;
      internal string? idempotencyKey;
      internal OnchainTransactionDetails? onchainDetails;
      internal Network? networkInfo;
#pragma warning restore SA1307, SA1401
      public Builder WithId(string? id)
      {
        this.id = id;
        return this;
      }
      public Builder WithWalletId(string? walletId)
      {
        this.walletId = walletId;
        return this;
      }
      public Builder WithPortfolioId(string? portfolioId)
      {
        this.portfolioId = portfolioId;
        return this;
      }
      public Builder WithType(TransactionType? type)
      {
        this.type = type;
        return this;
      }
      public Builder WithStatus(TransactionStatus? status)
      {
        this.status = status;
        return this;
      }
      public Builder WithSymbol(string? symbol)
      {
        this.symbol = symbol;
        return this;
      }
      public Builder WithCreatedAt(DateTime? createdAt)
      {
        this.createdAt = createdAt;
        return this;
      }
      public Builder WithCompletedAt(DateTime? completedAt)
      {
        this.completedAt = completedAt;
        return this;
      }
      public Builder WithAmount(string? amount)
      {
        this.amount = amount;
        return this;
      }
      public Builder WithTransferFrom(TransferLocation? transferFrom)
      {
        this.transferFrom = transferFrom;
        return this;
      }
      public Builder WithTransferTo(TransferLocation? transferTo)
      {
        this.transferTo = transferTo;
        return this;
      }
      public Builder WithNetworkFees(string? networkFees)
      {
        this.networkFees = networkFees;
        return this;
      }
      public Builder WithFees(string? fees)
      {
        this.fees = fees;
        return this;
      }
      public Builder WithFeeSymbol(string? feeSymbol)
      {
        this.feeSymbol = feeSymbol;
        return this;
      }
      public Builder WithBlockchainIds(List<string>? blockchainIds)
      {
        this.blockchainIds = blockchainIds;
        return this;
      }
      public Builder WithTransactionId(string? transactionId)
      {
        this.transactionId = transactionId;
        return this;
      }
      public Builder WithDestinationSymbol(string? destinationSymbol)
      {
        this.destinationSymbol = destinationSymbol;
        return this;
      }
      public Builder WithEstimatedNetworkFees(EstimatedNetworkFees? estimatedNetworkFees)
      {
        this.estimatedNetworkFees = estimatedNetworkFees;
        return this;
      }
      public Builder WithNetwork(string? network)
      {
        this.network = network;
        return this;
      }
      public Builder WithEstimatedAssetChanges(List<AssetChange>? estimatedAssetChanges)
      {
        this.estimatedAssetChanges = estimatedAssetChanges;
        return this;
      }
      public Builder WithMetadata(TransactionMetadata? metadata)
      {
        this.metadata = metadata;
        return this;
      }
      public Builder WithIdempotencyKey(string? idempotencyKey)
      {
        this.idempotencyKey = idempotencyKey;
        return this;
      }
      public Builder WithOnchainDetails(OnchainTransactionDetails? onchainDetails)
      {
        this.onchainDetails = onchainDetails;
        return this;
      }
      public Builder WithNetworkInfo(Network? networkInfo)
      {
        this.networkInfo = networkInfo;
        return this;
      }
      public Transaction Build()
      {
        return new Transaction(this);
      }
    }
  }

}
