// <auto-generated/>
#nullable enable

/*
 * Copyright 2025-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */


namespace CoinbaseSdk.Prime.Model
{
  using System.Text.Json.Serialization;

  public class TravelRuleEntry
  {
    [JsonPropertyName("id")]
    public string? Id { get; set; }
    [JsonPropertyName("blockchain_address")]
    public BlockchainAddress? BlockchainAddress { get; set; }
    [JsonPropertyName("originator")]
    public TravelRuleParty? Originator { get; set; }
    [JsonPropertyName("beneficiary")]
    public TravelRuleParty? Beneficiary { get; set; }
    [JsonPropertyName("vasp")]
    public VASP? Vasp { get; set; }
    [JsonPropertyName("wallet_details")]
    public TravelRuleWalletDetails? WalletDetails { get; set; }
    [JsonPropertyName("transfer_purpose")]
    public string? TransferPurpose { get; set; }
    [JsonPropertyName("is_self_certified")]
    public bool? IsSelfCertified { get; set; }
    [JsonPropertyName("is_intermediary")]
    public bool? IsIntermediary { get; set; }
    [JsonPropertyName("is_self")]
    public bool? IsSelf { get; set; }
    public TravelRuleEntry() { }

    public TravelRuleEntry(Builder builder)
    {
      this.Id = builder.id;
      this.BlockchainAddress = builder.blockchainAddress;
      this.Originator = builder.originator;
      this.Beneficiary = builder.beneficiary;
      this.Vasp = builder.vasp;
      this.WalletDetails = builder.walletDetails;
      this.TransferPurpose = builder.transferPurpose;
      this.IsSelfCertified = builder.isSelfCertified;
      this.IsIntermediary = builder.isIntermediary;
      this.IsSelf = builder.isSelf;
    }

    public class Builder
    {
#pragma warning disable SA1307, SA1401
      internal string? id;
      internal BlockchainAddress? blockchainAddress;
      internal TravelRuleParty? originator;
      internal TravelRuleParty? beneficiary;
      internal VASP? vasp;
      internal TravelRuleWalletDetails? walletDetails;
      internal string? transferPurpose;
      internal bool? isSelfCertified;
      internal bool? isIntermediary;
      internal bool? isSelf;
#pragma warning restore SA1307, SA1401
      public Builder WithId(string? id)
      {
        this.id = id;
        return this;
      }
      public Builder WithBlockchainAddress(BlockchainAddress? blockchainAddress)
      {
        this.blockchainAddress = blockchainAddress;
        return this;
      }
      public Builder WithOriginator(TravelRuleParty? originator)
      {
        this.originator = originator;
        return this;
      }
      public Builder WithBeneficiary(TravelRuleParty? beneficiary)
      {
        this.beneficiary = beneficiary;
        return this;
      }
      public Builder WithVasp(VASP? vasp)
      {
        this.vasp = vasp;
        return this;
      }
      public Builder WithWalletDetails(TravelRuleWalletDetails? walletDetails)
      {
        this.walletDetails = walletDetails;
        return this;
      }
      public Builder WithTransferPurpose(string? transferPurpose)
      {
        this.transferPurpose = transferPurpose;
        return this;
      }
      public Builder WithIsSelfCertified(bool? isSelfCertified)
      {
        this.isSelfCertified = isSelfCertified;
        return this;
      }
      public Builder WithIsIntermediary(bool? isIntermediary)
      {
        this.isIntermediary = isIntermediary;
        return this;
      }
      public Builder WithIsSelf(bool? isSelf)
      {
        this.isSelf = isSelf;
        return this;
      }
      public TravelRuleEntry Build()
      {
        return new TravelRuleEntry(this);
      }
    }
  }

}
