// <auto-generated/>
#nullable enable

/*
 * Copyright 2026-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 *  Do not edit the class manually.
 */


namespace CoinbaseSdk.Prime.Model
{

  public class TravelRuleData
  {
    public TravelRuleParty? Beneficiary { get; set; }
    public TravelRuleParty? Originator { get; set; }
    public bool? IsSelf { get; set; }
    /// <summary>
    /// True if Coinbase is being used as an intermediary for a customer transfer.
    /// </summary>
    public bool? IsIntermediary { get; set; }
    public bool? OptOutOfOwnershipVerification { get; set; }
    /// <summary>
    /// Whether the originating Vasp attests to verified wallet ownership. When true with is_intermediary, enables automatic Vasp data enrichment from the legal entity.
    /// </summary>
    public bool? AttestVerifiedWalletOwnership { get; set; }
    public TravelRuleData() { }

    public TravelRuleData(Builder builder)
    {
      this.Beneficiary = builder.beneficiary;
      this.Originator = builder.originator;
      this.IsSelf = builder.isSelf;
      this.IsIntermediary = builder.isIntermediary;
      this.OptOutOfOwnershipVerification = builder.optOutOfOwnershipVerification;
      this.AttestVerifiedWalletOwnership = builder.attestVerifiedWalletOwnership;
    }

    public class Builder
    {
#pragma warning disable SA1307, SA1401
      internal TravelRuleParty? beneficiary;
      internal TravelRuleParty? originator;
      internal bool? isSelf;
      internal bool? isIntermediary;
      internal bool? optOutOfOwnershipVerification;
      internal bool? attestVerifiedWalletOwnership;
#pragma warning restore SA1307, SA1401
      public Builder WithBeneficiary(TravelRuleParty? beneficiary)
      {
        this.beneficiary = beneficiary;
        return this;
      }
      public Builder WithOriginator(TravelRuleParty? originator)
      {
        this.originator = originator;
        return this;
      }
      public Builder WithIsSelf(bool? isSelf)
      {
        this.isSelf = isSelf;
        return this;
      }
      public Builder WithIsIntermediary(bool? isIntermediary)
      {
        this.isIntermediary = isIntermediary;
        return this;
      }
      public Builder WithOptOutOfOwnershipVerification(bool? optOutOfOwnershipVerification)
      {
        this.optOutOfOwnershipVerification = optOutOfOwnershipVerification;
        return this;
      }
      public Builder WithAttestVerifiedWalletOwnership(bool? attestVerifiedWalletOwnership)
      {
        this.attestVerifiedWalletOwnership = attestVerifiedWalletOwnership;
        return this;
      }
      public TravelRuleData Build()
      {
        return new TravelRuleData(this);
      }
    }
  }

}
