/*
 * Copyright 2025-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

namespace CoinbaseSdk.Prime.Model
{
  using CoinbaseSdk.Prime.Model.Enums;
  using System.Text.Json.Serialization;

  public class TravelRuleWalletDetails
  {
    [JsonPropertyName("wallet_type")]
    public TravelRuleWalletType? wallet_type { get; set; }

    [JsonPropertyName("wallet_address")]
    public BlockchainAddress? wallet_address { get; set; }

    public TravelRuleWalletDetails() { }

    public TravelRuleWalletDetails(Builder builder)
    {
      this.wallet_type = builder.wallet_type;
      this.wallet_address = builder.wallet_address;
    }

    public class Builder
    {
      private TravelRuleWalletType? wallet_type;

      private BlockchainAddress? wallet_address;

      public Builder Withwallet_type(TravelRuleWalletType? wallet_type)
      {
        this.wallet_type = wallet_type;
        return this;
      }

      public Builder Withwallet_address(BlockchainAddress? wallet_address)
      {
        this.wallet_address = wallet_address;
        return this;
      }

      public TravelRuleWalletDetails Build()
      {
        return new TravelRuleWalletDetails(this);
      }
    }
  }

}
