/*
 * Copyright 2025-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

namespace CoinbaseSdk.Prime.Model
{
  using CoinbaseSdk.Prime.Model.Enums;
  using CoinbaseSdk.Prime.Model.DateOfBirth;
  using CoinbaseSdk.Prime.Model.DetailedAddress;
  using CoinbaseSdk.Prime.Model.NaturalPersonName;
  using System.Text.Json.Serialization;

  public class TravelRuleParty
  {
    [JsonPropertyName("name")]
    public string? name { get; set; }

    [JsonPropertyName("detailed_address")]
    public DetailedAddress? detailed_address { get; set; }

    [JsonPropertyName("natural_person_name")]
    public NaturalPersonName? natural_person_name { get; set; }

    [JsonPropertyName("date_of_birth")]
    public DateOfBirth? date_of_birth { get; set; }

    [JsonPropertyName("telephone_number")]
    public string? telephone_number { get; set; }

    public TravelRuleParty() { }

    public TravelRuleParty(Builder builder)
    {
      this.name = builder.name;
      this.detailed_address = builder.detailed_address;
      this.natural_person_name = builder.natural_person_name;
      this.date_of_birth = builder.date_of_birth;
      this.telephone_number = builder.telephone_number;
    }

    public static class Builder
    {
      private string? name;

      private DetailedAddress? detailed_address;

      private NaturalPersonName? natural_person_name;

      private DateOfBirth? date_of_birth;

      private string? telephone_number;

      public Builder name(string? name)
      {
        this.name = name;
        return this;
      }

      public Builder detailed_address(DetailedAddress? detailed_address)
      {
        this.detailed_address = detailed_address;
        return this;
      }

      public Builder natural_person_name(NaturalPersonName? natural_person_name)
      {
        this.natural_person_name = natural_person_name;
        return this;
      }

      public Builder date_of_birth(DateOfBirth? date_of_birth)
      {
        this.date_of_birth = date_of_birth;
        return this;
      }

      public Builder telephone_number(string? telephone_number)
      {
        this.telephone_number = telephone_number;
        return this;
      }

      public TravelRuleParty Build()
      {
        return new TravelRuleParty(this);
      }
    }
  }

}
