// <auto-generated/>
#nullable enable

/*
 * Copyright 2025-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */


namespace CoinbaseSdk.Prime.Model
{
  using System.Text.Json.Serialization;
  using CoinbaseSdk.Prime.Model.Enums;

  public class UserAction
  {
    [JsonPropertyName("action")]
    public Action? Action { get; set; }
    /// <summary>
    /// Id of the user who executed the action
    /// </summary>
    [JsonPropertyName("user_id")]
    public string? UserId { get; set; }
    /// <summary>
    /// Time the action was taken
    /// </summary>
    [JsonPropertyName("timestamp")]
    public string? Timestamp { get; set; }
    public UserAction() { }

    public UserAction(Builder builder)
    {
      this.Action = builder.action;
      this.UserId = builder.userId;
      this.Timestamp = builder.timestamp;
    }

    public class Builder
    {
#pragma warning disable SA1307, SA1401
      internal Action? action;
      internal string? userId;
      internal string? timestamp;
#pragma warning restore SA1307, SA1401
      public Builder WithAction(Action? action)
      {
        this.action = action;
        return this;
      }
      public Builder WithUserId(string? userId)
      {
        this.userId = userId;
        return this;
      }
      public Builder WithTimestamp(string? timestamp)
      {
        this.timestamp = timestamp;
        return this;
      }
      public UserAction Build()
      {
        return new UserAction(this);
      }
    }
  }

}
