/*
 * Copyright 2025-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

namespace CoinbaseSdk.Prime.Model
{
  using CoinbaseSdk.Prime.Model.Enums;
  using System.Text.Json.Serialization;

  public class UserAction
  {
    [JsonPropertyName("action")]
    public Action? action { get; set; }

    /// <summary>
    /// Id of the user who executed the action
    /// </summary>
    [JsonPropertyName("user_id")]
    public string? user_id { get; set; }

    /// <summary>
    /// Time the action was taken
    /// </summary>
    [JsonPropertyName("timestamp")]
    public string? timestamp { get; set; }

    public UserAction() { }

    public UserAction(Builder builder)
    {
      this.action = builder.action;
      this.user_id = builder.user_id;
      this.timestamp = builder.timestamp;
    }

    public class Builder
    {
      private Action? action;

      private string? user_id;

      private string? timestamp;

      public Builder Withaction(Action? action)
      {
        this.action = action;
        return this;
      }

      public Builder Withuser_id(string? user_id)
      {
        this.user_id = user_id;
        return this;
      }

      public Builder Withtimestamp(string? timestamp)
      {
        this.timestamp = timestamp;
        return this;
      }

      public UserAction Build()
      {
        return new UserAction(this);
      }
    }
  }

}
