// <auto-generated/>
#nullable enable

/*
 * Copyright 2025-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */


namespace CoinbaseSdk.Prime.Model
{
  using System.Text.Json.Serialization;

  public class VASP
  {
    [JsonPropertyName("id")]
    public string? Id { get; set; }
    [JsonPropertyName("country_code")]
    public string? CountryCode { get; set; }
    [JsonPropertyName("lei_number")]
    public string? LeiNumber { get; set; }
    public VASP() { }

    public VASP(Builder builder)
    {
      this.Id = builder.id;
      this.CountryCode = builder.countryCode;
      this.LeiNumber = builder.leiNumber;
    }

    public class Builder
    {
#pragma warning disable SA1307, SA1401
      internal string? id;
      internal string? countryCode;
      internal string? leiNumber;
#pragma warning restore SA1307, SA1401
      public Builder WithId(string? id)
      {
        this.id = id;
        return this;
      }
      public Builder WithCountryCode(string? countryCode)
      {
        this.countryCode = countryCode;
        return this;
      }
      public Builder WithLeiNumber(string? leiNumber)
      {
        this.leiNumber = leiNumber;
        return this;
      }
      public VASP Build()
      {
        return new VASP(this);
      }
    }
  }

}
