/*
 * Copyright 2025-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

namespace CoinbaseSdk.Prime.Model
{
  using CoinbaseSdk.Prime.Model.Enums;
  using System.Text.Json.Serialization;

  public class VASP
  {
    [JsonPropertyName("id")]
    public string? id { get; set; }

    [JsonPropertyName("country_code")]
    public string? country_code { get; set; }

    [JsonPropertyName("lei_number")]
    public string? lei_number { get; set; }

    public VASP() { }

    public VASP(Builder builder)
    {
      this.id = builder.id;
      this.country_code = builder.country_code;
      this.lei_number = builder.lei_number;
    }

    public static class Builder
    {
      private string? id;

      private string? country_code;

      private string? lei_number;

      public Builder id(string? id)
      {
        this.id = id;
        return this;
      }

      public Builder country_code(string? country_code)
      {
        this.country_code = country_code;
        return this;
      }

      public Builder lei_number(string? lei_number)
      {
        this.lei_number = lei_number;
        return this;
      }

      public VASP Build()
      {
        return new VASP(this);
      }
    }
  }

}
