// <auto-generated/>
#nullable enable

/*
 * Copyright 2025-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */


namespace CoinbaseSdk.Prime.Model
{
  using System.Text.Json.Serialization;
  using CoinbaseSdk.Prime.Model.Enums;

  public class WalletCryptoDepositInstructions
  {
    /// <summary>
    /// The ID of the wallet
    /// </summary>
    [JsonPropertyName("id")]
    public string? Id { get; set; }
    /// <summary>
    /// The name of the wallet
    /// </summary>
    [JsonPropertyName("name")]
    public string? Name { get; set; }
    [JsonPropertyName("type")]
    public WalletDepositInstructionType? Type { get; set; }
    /// <summary>
    /// The address of the wallet
    /// </summary>
    [JsonPropertyName("address")]
    public string? Address { get; set; }
    /// <summary>
    /// The tag/memo of the address, if applicable - - required for certain assets (e.g. XRP, XLM, etc.)
    /// </summary>
    [JsonPropertyName("account_identifier")]
    public string? AccountIdentifier { get; set; }
    /// <summary>
    /// The blockchain network&#39;s terminology for the unique identifier used to identify the receiver of the transaction (different blockchain networks use different names, such as &#x60;destination_tag&#x60; or &#x60;memo&#x60;)
    /// </summary>
    [JsonPropertyName("account_identifier_name")]
    public string? AccountIdentifierName { get; set; }
    [JsonPropertyName("network")]
    public Network? Network { get; set; }
    public WalletCryptoDepositInstructions() { }

    public WalletCryptoDepositInstructions(Builder builder)
    {
      this.Id = builder.id;
      this.Name = builder.name;
      this.Type = builder.type;
      this.Address = builder.address;
      this.AccountIdentifier = builder.accountIdentifier;
      this.AccountIdentifierName = builder.accountIdentifierName;
      this.Network = builder.network;
    }

    public class Builder
    {
#pragma warning disable SA1307, SA1401
      internal string? id;
      internal string? name;
      internal WalletDepositInstructionType? type;
      internal string? address;
      internal string? accountIdentifier;
      internal string? accountIdentifierName;
      internal Network? network;
#pragma warning restore SA1307, SA1401
      public Builder WithId(string? id)
      {
        this.id = id;
        return this;
      }
      public Builder WithName(string? name)
      {
        this.name = name;
        return this;
      }
      public Builder WithType(WalletDepositInstructionType? type)
      {
        this.type = type;
        return this;
      }
      public Builder WithAddress(string? address)
      {
        this.address = address;
        return this;
      }
      public Builder WithAccountIdentifier(string? accountIdentifier)
      {
        this.accountIdentifier = accountIdentifier;
        return this;
      }
      public Builder WithAccountIdentifierName(string? accountIdentifierName)
      {
        this.accountIdentifierName = accountIdentifierName;
        return this;
      }
      public Builder WithNetwork(Network? network)
      {
        this.network = network;
        return this;
      }
      public WalletCryptoDepositInstructions Build()
      {
        return new WalletCryptoDepositInstructions(this);
      }
    }
  }

}
