/*
 * Copyright 2025-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

namespace CoinbaseSdk.Prime.Model
{
  using CoinbaseSdk.Prime.Model.Enums;
  using CoinbaseSdk.Prime.Model.WalletDepositInstructionType;
  using System.Text.Json.Serialization;

  public class WalletFiatDepositInstructions
  {
    [JsonPropertyName("id")]
    public string? id { get; set; }

    [JsonPropertyName("name")]
    public string? name { get; set; }

    [JsonPropertyName("type")]
    public WalletDepositInstructionType? type { get; set; }

    [JsonPropertyName("account_number")]
    public string? account_number { get; set; }

    [JsonPropertyName("routing_number")]
    public string? routing_number { get; set; }

    [JsonPropertyName("reference_code")]
    public string? reference_code { get; set; }

    public WalletFiatDepositInstructions() { }

    public WalletFiatDepositInstructions(Builder builder)
    {
      this.id = builder.id;
      this.name = builder.name;
      this.type = builder.type;
      this.account_number = builder.account_number;
      this.routing_number = builder.routing_number;
      this.reference_code = builder.reference_code;
    }

    public static class Builder
    {
      private string? id;

      private string? name;

      private WalletDepositInstructionType? type;

      private string? account_number;

      private string? routing_number;

      private string? reference_code;

      public Builder id(string? id)
      {
        this.id = id;
        return this;
      }

      public Builder name(string? name)
      {
        this.name = name;
        return this;
      }

      public Builder type(WalletDepositInstructionType? type)
      {
        this.type = type;
        return this;
      }

      public Builder account_number(string? account_number)
      {
        this.account_number = account_number;
        return this;
      }

      public Builder routing_number(string? routing_number)
      {
        this.routing_number = routing_number;
        return this;
      }

      public Builder reference_code(string? reference_code)
      {
        this.reference_code = reference_code;
        return this;
      }

      public WalletFiatDepositInstructions Build()
      {
        return new WalletFiatDepositInstructions(this);
      }
    }
  }

}
