// <auto-generated/>
#nullable enable

/*
 * Copyright 2026-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 *  Do not edit the class manually.
 */


namespace CoinbaseSdk.Prime.Model
{
  using CoinbaseSdk.Prime.Model.Enums;

  public class XmLoan
  {
    /// <summary>
    /// Financing loan UUID
    /// </summary>
    public string? LoanId { get; set; }
    public XmParty? LoanParty { get; set; }
    /// <summary>
    /// Loan principal currency
    /// </summary>
    public string? PrincipalCurrency { get; set; }
    /// <summary>
    /// Loan principal currency market price
    /// </summary>
    public string? PrincipalCurrencyMarketPrice { get; set; }
    /// <summary>
    /// Principal amount (nominal) as of loan initiation
    /// </summary>
    public string? InitialPrincipalAmount { get; set; }
    /// <summary>
    /// Current outstanding amount (nominal)
    /// </summary>
    public string? OutstandingPrincipalAmount { get; set; }
    /// <summary>
    /// Timestamp when the loan was created / initiated
    /// </summary>
    public DateTime? CreatedAt { get; set; }
    /// <summary>
    /// Timestamp when the loan was last updated
    /// </summary>
    public DateTime? UpdatedAt { get; set; }
    public XmLoan() { }

    public XmLoan(Builder builder)
    {
      this.LoanId = builder.loanId;
      this.LoanParty = builder.loanParty;
      this.PrincipalCurrency = builder.principalCurrency;
      this.PrincipalCurrencyMarketPrice = builder.principalCurrencyMarketPrice;
      this.InitialPrincipalAmount = builder.initialPrincipalAmount;
      this.OutstandingPrincipalAmount = builder.outstandingPrincipalAmount;
      this.CreatedAt = builder.createdAt;
      this.UpdatedAt = builder.updatedAt;
    }

    public class Builder
    {
#pragma warning disable SA1307, SA1401
      internal string? loanId;
      internal XmParty? loanParty;
      internal string? principalCurrency;
      internal string? principalCurrencyMarketPrice;
      internal string? initialPrincipalAmount;
      internal string? outstandingPrincipalAmount;
      internal DateTime? createdAt;
      internal DateTime? updatedAt;
#pragma warning restore SA1307, SA1401
      public Builder WithLoanId(string? loanId)
      {
        this.loanId = loanId;
        return this;
      }
      public Builder WithLoanParty(XmParty? loanParty)
      {
        this.loanParty = loanParty;
        return this;
      }
      public Builder WithPrincipalCurrency(string? principalCurrency)
      {
        this.principalCurrency = principalCurrency;
        return this;
      }
      public Builder WithPrincipalCurrencyMarketPrice(string? principalCurrencyMarketPrice)
      {
        this.principalCurrencyMarketPrice = principalCurrencyMarketPrice;
        return this;
      }
      public Builder WithInitialPrincipalAmount(string? initialPrincipalAmount)
      {
        this.initialPrincipalAmount = initialPrincipalAmount;
        return this;
      }
      public Builder WithOutstandingPrincipalAmount(string? outstandingPrincipalAmount)
      {
        this.outstandingPrincipalAmount = outstandingPrincipalAmount;
        return this;
      }
      public Builder WithCreatedAt(DateTime? createdAt)
      {
        this.createdAt = createdAt;
        return this;
      }
      public Builder WithUpdatedAt(DateTime? updatedAt)
      {
        this.updatedAt = updatedAt;
        return this;
      }
      public XmLoan Build()
      {
        return new XmLoan(this);
      }
    }
  }

}
