/*
 * Copyright 2025-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

namespace CoinbaseSdk.Prime.Model
{
  using CoinbaseSdk.Prime.Model.Enums;
  using System.Text.Json.Serialization;

  public class XMMarginCall
  {
    /// <summary>
    /// Financing margin call UUID
    /// </summary>
    [JsonPropertyName("margin_call_id")]
    public string? margin_call_id { get; set; }

    /// <summary>
    /// Margin call currency
    /// </summary>
    [JsonPropertyName("currency")]
    public string? currency { get; set; }

    /// <summary>
    /// Call amount (notional) as of the margin call creation
    /// </summary>
    [JsonPropertyName("initial_notional_amount")]
    public string? initial_notional_amount { get; set; }

    /// <summary>
    /// Current outstanding call amount (notional)
    /// </summary>
    [JsonPropertyName("outstanding_notional_amount")]
    public string? outstanding_notional_amount { get; set; }

    [JsonPropertyName("margin_call_type")]
    public XMCallType? margin_call_type { get; set; }

    [JsonPropertyName("margin_call_status")]
    public XMCallStatus? margin_call_status { get; set; }

    [JsonPropertyName("called_with_margin_level")]
    public XMMarginLevel? called_with_margin_level { get; set; }

    [JsonPropertyName("called_with_margin_summary")]
    public XMSummary? called_with_margin_summary { get; set; }

    /// <summary>
    /// Timestamp when the margin call settlement is due
    /// </summary>
    [JsonPropertyName("due_at")]
    public DateTime? due_at { get; set; }

    /// <summary>
    /// Timestamp when the margin call was created
    /// </summary>
    [JsonPropertyName("created_at")]
    public DateTime? created_at { get; set; }

    /// <summary>
    /// Timestamp when the margin call was last updated
    /// </summary>
    [JsonPropertyName("updated_at")]
    public DateTime? updated_at { get; set; }

    public XMMarginCall() { }

    public XMMarginCall(Builder builder)
    {
      this.margin_call_id = builder.margin_call_id;
      this.currency = builder.currency;
      this.initial_notional_amount = builder.initial_notional_amount;
      this.outstanding_notional_amount = builder.outstanding_notional_amount;
      this.margin_call_type = builder.margin_call_type;
      this.margin_call_status = builder.margin_call_status;
      this.called_with_margin_level = builder.called_with_margin_level;
      this.called_with_margin_summary = builder.called_with_margin_summary;
      this.due_at = builder.due_at;
      this.created_at = builder.created_at;
      this.updated_at = builder.updated_at;
    }

    public class Builder
    {
      private string? margin_call_id;

      private string? currency;

      private string? initial_notional_amount;

      private string? outstanding_notional_amount;

      private XMCallType? margin_call_type;

      private XMCallStatus? margin_call_status;

      private XMMarginLevel? called_with_margin_level;

      private XMSummary? called_with_margin_summary;

      private DateTime? due_at;

      private DateTime? created_at;

      private DateTime? updated_at;

      public Builder Withmargin_call_id(string? margin_call_id)
      {
        this.margin_call_id = margin_call_id;
        return this;
      }

      public Builder Withcurrency(string? currency)
      {
        this.currency = currency;
        return this;
      }

      public Builder Withinitial_notional_amount(string? initial_notional_amount)
      {
        this.initial_notional_amount = initial_notional_amount;
        return this;
      }

      public Builder Withoutstanding_notional_amount(string? outstanding_notional_amount)
      {
        this.outstanding_notional_amount = outstanding_notional_amount;
        return this;
      }

      public Builder Withmargin_call_type(XMCallType? margin_call_type)
      {
        this.margin_call_type = margin_call_type;
        return this;
      }

      public Builder Withmargin_call_status(XMCallStatus? margin_call_status)
      {
        this.margin_call_status = margin_call_status;
        return this;
      }

      public Builder Withcalled_with_margin_level(XMMarginLevel? called_with_margin_level)
      {
        this.called_with_margin_level = called_with_margin_level;
        return this;
      }

      public Builder Withcalled_with_margin_summary(XMSummary? called_with_margin_summary)
      {
        this.called_with_margin_summary = called_with_margin_summary;
        return this;
      }

      public Builder Withdue_at(DateTime? due_at)
      {
        this.due_at = due_at;
        return this;
      }

      public Builder Withcreated_at(DateTime? created_at)
      {
        this.created_at = created_at;
        return this;
      }

      public Builder Withupdated_at(DateTime? updated_at)
      {
        this.updated_at = updated_at;
        return this;
      }

      public XMMarginCall Build()
      {
        return new XMMarginCall(this);
      }
    }
  }

}
