/*
 * Copyright 2025-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

namespace CoinbaseSdk.Prime.Model
{
  using CoinbaseSdk.Prime.Model.Enums;
  using System.Text.Json.Serialization;

  public class XMPosition
  {
    /// <summary>
    /// Position currency
    /// </summary>
    [JsonPropertyName("currency")]
    public string? currency { get; set; }

    /// <summary>
    /// Current market price
    /// </summary>
    [JsonPropertyName("market_price")]
    public string? market_price { get; set; }

    /// <summary>
    /// True if margin eligible, false otherwise
    /// </summary>
    [JsonPropertyName("margin_eligible")]
    public bool? margin_eligible { get; set; }

    /// <summary>
    /// Total market capitalization
    /// </summary>
    [JsonPropertyName("market_cap")]
    public string? market_cap { get; set; }

    /// <summary>
    /// Average daily volume calculated over a 30-day period
    /// </summary>
    [JsonPropertyName("adv30_days")]
    public string? adv30_days { get; set; }

    /// <summary>
    /// Historic volatility calculated over a 5-day period
    /// </summary>
    [JsonPropertyName("hist5d_vol")]
    public string? hist5d_vol { get; set; }

    /// <summary>
    /// Historic volatility calculated over a 30-day period
    /// </summary>
    [JsonPropertyName("hist30d_vol")]
    public string? hist30d_vol { get; set; }

    /// <summary>
    /// Historic volatility calculated over a 90-day period
    /// </summary>
    [JsonPropertyName("hist90d_vol")]
    public string? hist90d_vol { get; set; }

    /// <summary>
    /// Base margin requirement for the specific asset
    /// </summary>
    [JsonPropertyName("margin_requirement")]
    public string? margin_requirement { get; set; }

    /// <summary>
    /// XM spot balance nominal
    /// </summary>
    [JsonPropertyName("spot_balance")]
    public string? spot_balance { get; set; }

    /// <summary>
    /// XM spot balance notional
    /// </summary>
    [JsonPropertyName("spot_balance_notional")]
    public string? spot_balance_notional { get; set; }

    /// <summary>
    /// Pre-netted spot total position margin
    /// </summary>
    [JsonPropertyName("spot_total_position_margin")]
    public string? spot_total_position_margin { get; set; }

    /// <summary>
    /// XM futures balance nominal
    /// </summary>
    [JsonPropertyName("futures_balance")]
    public string? futures_balance { get; set; }

    /// <summary>
    /// XM futures balance notional
    /// </summary>
    [JsonPropertyName("futures_balance_notional")]
    public string? futures_balance_notional { get; set; }

    /// <summary>
    /// Pre-netted futures total position margin
    /// </summary>
    [JsonPropertyName("futures_total_position_margin")]
    public string? futures_total_position_margin { get; set; }

    /// <summary>
    /// Basis GMV &#x3D; |futures| + |spot| - |unnetted position|
    /// </summary>
    [JsonPropertyName("gmv_basis")]
    public string? gmv_basis { get; set; }

    /// <summary>
    /// Base margin requirement notional
    /// </summary>
    [JsonPropertyName("base_requirement")]
    public string? base_requirement { get; set; }

    /// <summary>
    /// Effective liquidity add-on for the short positions
    /// </summary>
    [JsonPropertyName("liq_shorts_add_on")]
    public string? liq_shorts_add_on { get; set; }

    /// <summary>
    /// Effective liquidity add-on for the long positions
    /// </summary>
    [JsonPropertyName("liq_longs_add_on")]
    public string? liq_longs_add_on { get; set; }

    /// <summary>
    /// Effective volatility add-on for the short positions
    /// </summary>
    [JsonPropertyName("vol_shorts_add_on")]
    public string? vol_shorts_add_on { get; set; }

    /// <summary>
    /// Effective volatility add-on for the long positions
    /// </summary>
    [JsonPropertyName("vol_longs_add_on")]
    public string? vol_longs_add_on { get; set; }

    /// <summary>
    /// 5-day volatility add-on
    /// </summary>
    [JsonPropertyName("vol5days_add_on")]
    public string? vol5days_add_on { get; set; }

    /// <summary>
    /// 30-day volatility add-on
    /// </summary>
    [JsonPropertyName("vol30days_add_on")]
    public string? vol30days_add_on { get; set; }

    /// <summary>
    /// 90-day volatility add-on
    /// </summary>
    [JsonPropertyName("vol90days_add_on")]
    public string? vol90days_add_on { get; set; }

    /// <summary>
    /// Total margin required
    /// </summary>
    [JsonPropertyName("total_position_margin")]
    public string? total_position_margin { get; set; }

    public XMPosition() { }

    public XMPosition(Builder builder)
    {
      this.currency = builder.currency;
      this.market_price = builder.market_price;
      this.margin_eligible = builder.margin_eligible;
      this.market_cap = builder.market_cap;
      this.adv30_days = builder.adv30_days;
      this.hist5d_vol = builder.hist5d_vol;
      this.hist30d_vol = builder.hist30d_vol;
      this.hist90d_vol = builder.hist90d_vol;
      this.margin_requirement = builder.margin_requirement;
      this.spot_balance = builder.spot_balance;
      this.spot_balance_notional = builder.spot_balance_notional;
      this.spot_total_position_margin = builder.spot_total_position_margin;
      this.futures_balance = builder.futures_balance;
      this.futures_balance_notional = builder.futures_balance_notional;
      this.futures_total_position_margin = builder.futures_total_position_margin;
      this.gmv_basis = builder.gmv_basis;
      this.base_requirement = builder.base_requirement;
      this.liq_shorts_add_on = builder.liq_shorts_add_on;
      this.liq_longs_add_on = builder.liq_longs_add_on;
      this.vol_shorts_add_on = builder.vol_shorts_add_on;
      this.vol_longs_add_on = builder.vol_longs_add_on;
      this.vol5days_add_on = builder.vol5days_add_on;
      this.vol30days_add_on = builder.vol30days_add_on;
      this.vol90days_add_on = builder.vol90days_add_on;
      this.total_position_margin = builder.total_position_margin;
    }

    public static class Builder
    {
      private string? currency;

      private string? market_price;

      private bool? margin_eligible;

      private string? market_cap;

      private string? adv30_days;

      private string? hist5d_vol;

      private string? hist30d_vol;

      private string? hist90d_vol;

      private string? margin_requirement;

      private string? spot_balance;

      private string? spot_balance_notional;

      private string? spot_total_position_margin;

      private string? futures_balance;

      private string? futures_balance_notional;

      private string? futures_total_position_margin;

      private string? gmv_basis;

      private string? base_requirement;

      private string? liq_shorts_add_on;

      private string? liq_longs_add_on;

      private string? vol_shorts_add_on;

      private string? vol_longs_add_on;

      private string? vol5days_add_on;

      private string? vol30days_add_on;

      private string? vol90days_add_on;

      private string? total_position_margin;

      public Builder currency(string? currency)
      {
        this.currency = currency;
        return this;
      }

      public Builder market_price(string? market_price)
      {
        this.market_price = market_price;
        return this;
      }

      public Builder margin_eligible(bool? margin_eligible)
      {
        this.margin_eligible = margin_eligible;
        return this;
      }

      public Builder market_cap(string? market_cap)
      {
        this.market_cap = market_cap;
        return this;
      }

      public Builder adv30_days(string? adv30_days)
      {
        this.adv30_days = adv30_days;
        return this;
      }

      public Builder hist5d_vol(string? hist5d_vol)
      {
        this.hist5d_vol = hist5d_vol;
        return this;
      }

      public Builder hist30d_vol(string? hist30d_vol)
      {
        this.hist30d_vol = hist30d_vol;
        return this;
      }

      public Builder hist90d_vol(string? hist90d_vol)
      {
        this.hist90d_vol = hist90d_vol;
        return this;
      }

      public Builder margin_requirement(string? margin_requirement)
      {
        this.margin_requirement = margin_requirement;
        return this;
      }

      public Builder spot_balance(string? spot_balance)
      {
        this.spot_balance = spot_balance;
        return this;
      }

      public Builder spot_balance_notional(string? spot_balance_notional)
      {
        this.spot_balance_notional = spot_balance_notional;
        return this;
      }

      public Builder spot_total_position_margin(string? spot_total_position_margin)
      {
        this.spot_total_position_margin = spot_total_position_margin;
        return this;
      }

      public Builder futures_balance(string? futures_balance)
      {
        this.futures_balance = futures_balance;
        return this;
      }

      public Builder futures_balance_notional(string? futures_balance_notional)
      {
        this.futures_balance_notional = futures_balance_notional;
        return this;
      }

      public Builder futures_total_position_margin(string? futures_total_position_margin)
      {
        this.futures_total_position_margin = futures_total_position_margin;
        return this;
      }

      public Builder gmv_basis(string? gmv_basis)
      {
        this.gmv_basis = gmv_basis;
        return this;
      }

      public Builder base_requirement(string? base_requirement)
      {
        this.base_requirement = base_requirement;
        return this;
      }

      public Builder liq_shorts_add_on(string? liq_shorts_add_on)
      {
        this.liq_shorts_add_on = liq_shorts_add_on;
        return this;
      }

      public Builder liq_longs_add_on(string? liq_longs_add_on)
      {
        this.liq_longs_add_on = liq_longs_add_on;
        return this;
      }

      public Builder vol_shorts_add_on(string? vol_shorts_add_on)
      {
        this.vol_shorts_add_on = vol_shorts_add_on;
        return this;
      }

      public Builder vol_longs_add_on(string? vol_longs_add_on)
      {
        this.vol_longs_add_on = vol_longs_add_on;
        return this;
      }

      public Builder vol5days_add_on(string? vol5days_add_on)
      {
        this.vol5days_add_on = vol5days_add_on;
        return this;
      }

      public Builder vol30days_add_on(string? vol30days_add_on)
      {
        this.vol30days_add_on = vol30days_add_on;
        return this;
      }

      public Builder vol90days_add_on(string? vol90days_add_on)
      {
        this.vol90days_add_on = vol90days_add_on;
        return this;
      }

      public Builder total_position_margin(string? total_position_margin)
      {
        this.total_position_margin = total_position_margin;
        return this;
      }

      public XMPosition Build()
      {
        return new XMPosition(this);
      }
    }
  }

}
