// <auto-generated/>
#nullable enable

/*
 * Copyright 2025-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */


namespace CoinbaseSdk.Prime.Model
{
  using System.Text.Json.Serialization;

  public class XmRiskNettingInfo
  {
    /// <summary>
    /// Nodal Margin Requirement (NMR) is the margin requirement for all futures positions, derived from the Nodal model
    /// </summary>
    [JsonPropertyName("nodal_margin_requirement")]
    public string? NodalMarginRequirement { get; set; }
    /// <summary>
    /// Portfolio Margin Requirement (PmR) is the margin requirement for all spot positions, derived from the Xm model
    /// </summary>
    [JsonPropertyName("portfolio_margin_requirement")]
    public string? PortfolioMarginRequirement { get; set; }
    /// <summary>
    /// Integrated Portfolio Margin Requirement (IPMR) is the margin requirement for all spot positions + futures positions with underlying assets eligible in Portfolio Margin, via the Xm model with one-leg netting
    /// </summary>
    [JsonPropertyName("integrated_portfolio_margin_requirement")]
    public string? IntegratedPortfolioMarginRequirement { get; set; }
    /// <summary>
    /// Ineligible Futures Margin Requirement (IFMR) is the margin requirement for IPMR-ineligible futures contracts
    /// </summary>
    [JsonPropertyName("ineligible_futures_margin_requirement")]
    public string? IneligibleFuturesMarginRequirement { get; set; }
    /// <summary>
    /// Position margin requirement for all spot positions
    /// </summary>
    [JsonPropertyName("position_margin_requirement")]
    public string? PositionMarginRequirement { get; set; }
    /// <summary>
    /// Portfolio margin addon for all spot positions
    /// </summary>
    [JsonPropertyName("portfolio_margin_addon")]
    public string? PortfolioMarginAddon { get; set; }
    /// <summary>
    /// Position margin requirement for spot + futures positions
    /// </summary>
    [JsonPropertyName("integrated_position_margin_requirement")]
    public string? IntegratedPositionMarginRequirement { get; set; }
    /// <summary>
    /// Portfolio margin addon for spot + futures positions
    /// </summary>
    [JsonPropertyName("integrated_portfolio_margin_addon")]
    public string? IntegratedPortfolioMarginAddon { get; set; }
    /// <summary>
    /// Post-netting USD notional for all futures positions
    /// </summary>
    [JsonPropertyName("netted_futures_notional")]
    public string? NettedFuturesNotional { get; set; }
    /// <summary>
    /// Total basis gross market value of all XM-eligible positions (i.e. crypto underliers)
    /// </summary>
    [JsonPropertyName("total_gmv_basis")]
    public string? TotalGmvBasis { get; set; }
    /// <summary>
    /// Integrated Portfolio Margin cash balance
    /// </summary>
    [JsonPropertyName("ipm_cash_balance")]
    public string? IpmCashBalance { get; set; }
    [JsonPropertyName("integrated_scenario_addon")]
    public MarginAddOn? IntegratedScenarioAddon { get; set; }
    /// <summary>
    /// All integrated scenario add-ons
    /// </summary>
    [JsonPropertyName("all_integrated_scenario_addons")]
    public List<MarginAddOn>? AllIntegratedScenarioAddons { get; set; }
    /// <summary>
    /// Netted positions used in the model calculation
    /// </summary>
    [JsonPropertyName("xm_positions")]
    public List<XmPosition>? XmPositions { get; set; }
    public XmRiskNettingInfo() { }

    public XmRiskNettingInfo(Builder builder)
    {
      this.NodalMarginRequirement = builder.nodalMarginRequirement;
      this.PortfolioMarginRequirement = builder.portfolioMarginRequirement;
      this.IntegratedPortfolioMarginRequirement = builder.integratedPortfolioMarginRequirement;
      this.IneligibleFuturesMarginRequirement = builder.ineligibleFuturesMarginRequirement;
      this.PositionMarginRequirement = builder.positionMarginRequirement;
      this.PortfolioMarginAddon = builder.portfolioMarginAddon;
      this.IntegratedPositionMarginRequirement = builder.integratedPositionMarginRequirement;
      this.IntegratedPortfolioMarginAddon = builder.integratedPortfolioMarginAddon;
      this.NettedFuturesNotional = builder.nettedFuturesNotional;
      this.TotalGmvBasis = builder.totalGmvBasis;
      this.IpmCashBalance = builder.ipmCashBalance;
      this.IntegratedScenarioAddon = builder.integratedScenarioAddon;
      this.AllIntegratedScenarioAddons = builder.allIntegratedScenarioAddons;
      this.XmPositions = builder.xmPositions;
    }

    public class Builder
    {
#pragma warning disable SA1307, SA1401
      internal string? nodalMarginRequirement;
      internal string? portfolioMarginRequirement;
      internal string? integratedPortfolioMarginRequirement;
      internal string? ineligibleFuturesMarginRequirement;
      internal string? positionMarginRequirement;
      internal string? portfolioMarginAddon;
      internal string? integratedPositionMarginRequirement;
      internal string? integratedPortfolioMarginAddon;
      internal string? nettedFuturesNotional;
      internal string? totalGmvBasis;
      internal string? ipmCashBalance;
      internal MarginAddOn? integratedScenarioAddon;
      internal List<MarginAddOn>? allIntegratedScenarioAddons;
      internal List<XmPosition>? xmPositions;
#pragma warning restore SA1307, SA1401
      public Builder WithNodalMarginRequirement(string? nodalMarginRequirement)
      {
        this.nodalMarginRequirement = nodalMarginRequirement;
        return this;
      }
      public Builder WithPortfolioMarginRequirement(string? portfolioMarginRequirement)
      {
        this.portfolioMarginRequirement = portfolioMarginRequirement;
        return this;
      }
      public Builder WithIntegratedPortfolioMarginRequirement(string? integratedPortfolioMarginRequirement)
      {
        this.integratedPortfolioMarginRequirement = integratedPortfolioMarginRequirement;
        return this;
      }
      public Builder WithIneligibleFuturesMarginRequirement(string? ineligibleFuturesMarginRequirement)
      {
        this.ineligibleFuturesMarginRequirement = ineligibleFuturesMarginRequirement;
        return this;
      }
      public Builder WithPositionMarginRequirement(string? positionMarginRequirement)
      {
        this.positionMarginRequirement = positionMarginRequirement;
        return this;
      }
      public Builder WithPortfolioMarginAddon(string? portfolioMarginAddon)
      {
        this.portfolioMarginAddon = portfolioMarginAddon;
        return this;
      }
      public Builder WithIntegratedPositionMarginRequirement(string? integratedPositionMarginRequirement)
      {
        this.integratedPositionMarginRequirement = integratedPositionMarginRequirement;
        return this;
      }
      public Builder WithIntegratedPortfolioMarginAddon(string? integratedPortfolioMarginAddon)
      {
        this.integratedPortfolioMarginAddon = integratedPortfolioMarginAddon;
        return this;
      }
      public Builder WithNettedFuturesNotional(string? nettedFuturesNotional)
      {
        this.nettedFuturesNotional = nettedFuturesNotional;
        return this;
      }
      public Builder WithTotalGmvBasis(string? totalGmvBasis)
      {
        this.totalGmvBasis = totalGmvBasis;
        return this;
      }
      public Builder WithIpmCashBalance(string? ipmCashBalance)
      {
        this.ipmCashBalance = ipmCashBalance;
        return this;
      }
      public Builder WithIntegratedScenarioAddon(MarginAddOn? integratedScenarioAddon)
      {
        this.integratedScenarioAddon = integratedScenarioAddon;
        return this;
      }
      public Builder WithAllIntegratedScenarioAddons(List<MarginAddOn>? allIntegratedScenarioAddons)
      {
        this.allIntegratedScenarioAddons = allIntegratedScenarioAddons;
        return this;
      }
      public Builder WithXmPositions(List<XmPosition>? xmPositions)
      {
        this.xmPositions = xmPositions;
        return this;
      }
      public XmRiskNettingInfo Build()
      {
        return new XmRiskNettingInfo(this);
      }
    }
  }

}
