// <auto-generated/>
#nullable enable

/*
 * Copyright 2025-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */


namespace CoinbaseSdk.Prime.Model
{
  using System.Text.Json.Serialization;

  public class XmSummary
  {
    /// <summary>
    /// Cross Margin Margin Requirement (XmMR) notional
    /// </summary>
    [JsonPropertyName("margin_requirement")]
    public string? MarginRequirement { get; set; }
    /// <summary>
    /// Equity notional
    /// </summary>
    [JsonPropertyName("account_equity")]
    public string? AccountEquity { get; set; }
    /// <summary>
    /// Equity - XmMR (margin excess is &gt; 0)
    /// </summary>
    [JsonPropertyName("margin_excess_shortfall")]
    public string? MarginExcessShortfall { get; set; }
    /// <summary>
    /// Credit consumed from Cross Margin Credit Limit (XmCL)
    /// </summary>
    [JsonPropertyName("consumed_credit")]
    public string? ConsumedCredit { get; set; }
    /// <summary>
    /// XM Credit Limit (XmCL) is the maximum notional USD of total fiat and digital asset loans
    /// </summary>
    [JsonPropertyName("xm_credit_limit")]
    public string? XmCreditLimit { get; set; }
    /// <summary>
    /// XM Margin Limit (XmML) is the maximum notional USD deficit
    /// </summary>
    [JsonPropertyName("xm_margin_limit")]
    public string? XmMarginLimit { get; set; }
    /// <summary>
    /// Equity attributed by spot
    /// </summary>
    [JsonPropertyName("spot_equity")]
    public string? SpotEquity { get; set; }
    /// <summary>
    /// Equity attributed by futures
    /// </summary>
    [JsonPropertyName("futures_equity")]
    public string? FuturesEquity { get; set; }
    [JsonPropertyName("risk_netting_info")]
    public XmRiskNettingInfo? RiskNettingInfo { get; set; }
    public XmSummary() { }

    public XmSummary(Builder builder)
    {
      this.MarginRequirement = builder.marginRequirement;
      this.AccountEquity = builder.accountEquity;
      this.MarginExcessShortfall = builder.marginExcessShortfall;
      this.ConsumedCredit = builder.consumedCredit;
      this.XmCreditLimit = builder.xmCreditLimit;
      this.XmMarginLimit = builder.xmMarginLimit;
      this.SpotEquity = builder.spotEquity;
      this.FuturesEquity = builder.futuresEquity;
      this.RiskNettingInfo = builder.riskNettingInfo;
    }

    public class Builder
    {
#pragma warning disable SA1307, SA1401
      internal string? marginRequirement;
      internal string? accountEquity;
      internal string? marginExcessShortfall;
      internal string? consumedCredit;
      internal string? xmCreditLimit;
      internal string? xmMarginLimit;
      internal string? spotEquity;
      internal string? futuresEquity;
      internal XmRiskNettingInfo? riskNettingInfo;
#pragma warning restore SA1307, SA1401
      public Builder WithMarginRequirement(string? marginRequirement)
      {
        this.marginRequirement = marginRequirement;
        return this;
      }
      public Builder WithAccountEquity(string? accountEquity)
      {
        this.accountEquity = accountEquity;
        return this;
      }
      public Builder WithMarginExcessShortfall(string? marginExcessShortfall)
      {
        this.marginExcessShortfall = marginExcessShortfall;
        return this;
      }
      public Builder WithConsumedCredit(string? consumedCredit)
      {
        this.consumedCredit = consumedCredit;
        return this;
      }
      public Builder WithXmCreditLimit(string? xmCreditLimit)
      {
        this.xmCreditLimit = xmCreditLimit;
        return this;
      }
      public Builder WithXmMarginLimit(string? xmMarginLimit)
      {
        this.xmMarginLimit = xmMarginLimit;
        return this;
      }
      public Builder WithSpotEquity(string? spotEquity)
      {
        this.spotEquity = spotEquity;
        return this;
      }
      public Builder WithFuturesEquity(string? futuresEquity)
      {
        this.futuresEquity = futuresEquity;
        return this;
      }
      public Builder WithRiskNettingInfo(XmRiskNettingInfo? riskNettingInfo)
      {
        this.riskNettingInfo = riskNettingInfo;
        return this;
      }
      public XmSummary Build()
      {
        return new XmSummary(this);
      }
    }
  }

}
